$axure.loadCurrentPage({
  "url":"主页.html",
  "generationDate":new Date(1421557095950.67),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"isLogin"],
  "page":{
    "packageId":"0e3b2b6a7b8c4cbfae3fa1cdfe25d5a6",
    "type":"Axure:Page",
    "name":"主页",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
      "a":{
}},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"5500db7e1aa74b64ab93939236c7c3dc",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "limbo":true},
          "adaptiveStyles":{
            "a":{
              "limbo":false}},
          "masterId":"e423deecdca540d69784293e6582ba81"},
{
          "id":"083192dcc83a4e63865f7969ca396fa6",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "limbo":true},
          "adaptiveStyles":{
            "a":{
              "limbo":false}},
          "masterId":"95d57cbcfde44948b7548a4f84555e79"},
{
          "id":"fbb3899efd6c44c3aa7fc79fe4e0ff8d",
          "label":"轮播图",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":50},
            "size":{
              "width":200,
              "height":200},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
              "location":{
                "x":0,
                "y":55},
              "size":{
                "width":320,
                "height":90},
              "limbo":false}},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 浏览器",
                      "target":{
                        "targetType":"page",
                        "url":"浏览器.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "scrollbars":"horizontalAsNeeded",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"f5e9c136633b4d2bb89d67f02a752810",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[]}]},
{
          "id":"9081c3ee11ca43f98286800f182865d9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":144,
              "y":64},
            "size":{
              "width":40,
              "height":16},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
              "location":{
                "x":140,
                "y":92},
              "size":{
                "width":40,
                "height":16},
              "limbo":false}},
          "objects":[{
              "id":"60c30e8dc48d4e7aab21eb3bb35306bb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":144,
                  "y":64},
                "size":{
                  "width":40,
                  "height":16},
                "limbo":true},
              "adaptiveStyles":{
                "a":{
}}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "normal~a":"resources/images/transparent.gif"}},
{
          "id":"3d940294120a4bdd960ee4c32347a543",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":150},
            "size":{
              "width":100,
              "height":25},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
              "location":{
                "x":10,
                "y":155},
              "size":{
                "width":140,
                "height":125},
              "limbo":false}},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 项目大类型选择",
                      "target":{
                        "targetType":"page",
                        "url":"项目大类型选择.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"0ff253a87cbc4b17b6c92dd576952384",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":160,
              "y":150},
            "size":{
              "width":100,
              "height":25},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
              "location":{
                "x":170,
                "y":155},
              "size":{
                "width":141,
                "height":125},
              "limbo":false}},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 技师浏览",
                      "target":{
                        "targetType":"page",
                        "url":"技师浏览.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"ec472804eb334ee0b16dd756bf0a36a7",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":160,
              "y":280},
            "size":{
              "width":100,
              "height":25},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
              "location":{
                "x":170,
                "y":290},
              "size":{
                "width":141,
                "height":120},
              "limbo":false}}},
{
          "id":"a21e4f6bd73545679ca269841cb70ba7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":140,
              "y":14},
            "size":{
              "width":40,
              "height":23},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
              "size":{
                "width":40,
                "height":23},
              "limbo":false}},
          "objects":[{
              "id":"35569d0d038540f9962f15704da91a36",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":140,
                  "y":14},
                "size":{
                  "width":40,
                  "height":23},
                "limbo":true},
              "adaptiveStyles":{
                "a":{
}}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "normal~a":"resources/images/transparent.gif"}},
{
          "id":"cfca368464fe4b9aacaa9def5c22c5a8",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":170,
              "y":165},
            "size":{
              "width":100,
              "height":25},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
              "location":{
                "x":10,
                "y":290},
              "size":{
                "width":140,
                "height":120},
              "limbo":false}}}]}},
  "masters":{
    "e423deecdca540d69784293e6582ba81":{
      "packageId":"e423deecdca540d69784293e6582ba81",
      "type":"Axure:Master",
      "name":"下导航栏",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
        "a":{
}},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"46b38d34c95741f384d5e4d38e3120ee",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":0,
                "y":420},
              "size":{
                "width":320,
                "height":60}},
            "adaptiveStyles":{
              "a":{
                "location":{
                  "x":0,
                  "y":0},
                "size":{
                  "width":320,
                  "height":480}}},
            "objects":[{
                "id":"eee4e22156fe41d98e86bfcfbba3e560",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":0,
                    "y":420},
                  "size":{
                    "width":320,
                    "height":60}},
                "adaptiveStyles":{
                  "a":{
}}}],
            "images":{
              "normal~":"images/主页/u1.png",
              "normal~a":"images/主页/u1_a.png"}},
{
            "id":"a219148e8a9a42acb89b27adba3bd693",
            "label":"",
            "type":"button",
            "styleType":"button",
            "visible":true,
            "style":{
              "location":{
                "x":0,
                "y":420},
              "size":{
                "width":100,
                "height":25},
              "limbo":true},
            "adaptiveStyles":{
              "a":{
                "size":{
                  "width":64,
                  "height":60},
                "limbo":false}},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 主页",
                        "target":{
                          "targetType":"page",
                          "url":"主页.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true},
{
            "id":"6d76ed98f8af41ef971bb4aeeadd04f1",
            "label":"",
            "type":"button",
            "styleType":"button",
            "visible":true,
            "style":{
              "location":{
                "x":10,
                "y":430},
              "size":{
                "width":100,
                "height":25},
              "limbo":true},
            "adaptiveStyles":{
              "a":{
                "location":{
                  "x":64,
                  "y":420},
                "size":{
                  "width":64,
                  "height":60},
                "limbo":false}},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 订单",
                        "target":{
                          "targetType":"page",
                          "url":"订单.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true},
{
            "id":"5a6a8b09d0fa44cb996ec710d732c51a",
            "label":"",
            "type":"button",
            "styleType":"button",
            "visible":true,
            "style":{
              "location":{
                "x":20,
                "y":440},
              "size":{
                "width":100,
                "height":25},
              "limbo":true},
            "adaptiveStyles":{
              "a":{
                "location":{
                  "x":128,
                  "y":420},
                "size":{
                  "width":64,
                  "height":60},
                "limbo":false}},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 我的",
                        "target":{
                          "targetType":"page",
                          "url":"我的.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true},
{
            "id":"c346be56b3b148c394d01867f96020ed",
            "label":"",
            "type":"button",
            "styleType":"button",
            "visible":true,
            "style":{
              "location":{
                "x":30,
                "y":450},
              "size":{
                "width":100,
                "height":25},
              "limbo":true},
            "adaptiveStyles":{
              "a":{
                "location":{
                  "x":192,
                  "y":420},
                "size":{
                  "width":64,
                  "height":60},
                "limbo":false}},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 生活",
                        "target":{
                          "targetType":"page",
                          "url":"生活.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true},
{
            "id":"bee383944d00498cb4790c08da5a6c34",
            "label":"",
            "type":"button",
            "styleType":"button",
            "visible":true,
            "style":{
              "location":{
                "x":40,
                "y":460},
              "size":{
                "width":100,
                "height":25},
              "limbo":true},
            "adaptiveStyles":{
              "a":{
                "location":{
                  "x":256,
                  "y":420},
                "size":{
                  "width":64,
                  "height":60},
                "limbo":false}},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 更多",
                        "target":{
                          "targetType":"page",
                          "url":"更多.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true}]}},
    "95d57cbcfde44948b7548a4f84555e79":{
      "packageId":"95d57cbcfde44948b7548a4f84555e79",
      "type":"Axure:Master",
      "name":"上导航栏",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
        "a":{
}},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"3a8352b0bdb94ce9a3089c99ad30d525",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "size":{
                "width":200,
                "height":100},
              "limbo":true},
            "adaptiveStyles":{
              "a":{
                "size":{
                  "width":320,
                  "height":50},
                "limbo":false}},
            "objects":[{
                "id":"5e026ecd19c44faaaf17922e877148fb",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":200,
                    "height":100},
                  "limbo":true},
                "adaptiveStyles":{
                  "a":{
}}}],
            "images":{
              "normal~":"images/主页/u9.png",
              "normal~a":"images/主页/u9_a.png"}},
{
            "id":"daf03b54e1b54a3e931b529609a504e5",
            "label":"",
            "type":"button",
            "styleType":"button",
            "visible":true,
            "style":{
              "location":{
                "x":10,
                "y":12.5},
              "size":{
                "width":100,
                "height":25},
              "limbo":true},
            "adaptiveStyles":{
              "a":{
                "location":{
                  "x":10,
                  "y":14},
                "size":{
                  "width":70,
                  "height":23},
                "limbo":false}},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 选择城市",
                        "target":{
                          "targetType":"page",
                          "url":"选择城市.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true},
{
            "id":"9b46f5ced4cd494bb946afb473a1d17b",
            "label":"",
            "type":"button",
            "styleType":"button",
            "visible":true,
            "style":{
              "location":{
                "x":211,
                "y":13},
              "size":{
                "width":100,
                "height":25},
              "limbo":true},
            "adaptiveStyles":{
              "a":{
                "location":{
                  "x":240,
                  "y":13},
                "size":{
                  "width":71,
                  "height":25},
                "limbo":false}}}]}}},
  "objectPaths":{
    "5500db7e1aa74b64ab93939236c7c3dc":{
      "scriptId":"u0",
      "46b38d34c95741f384d5e4d38e3120ee":{
        "scriptId":"u1"},
      "eee4e22156fe41d98e86bfcfbba3e560":{
        "scriptId":"u2"},
      "a219148e8a9a42acb89b27adba3bd693":{
        "scriptId":"u3"},
      "6d76ed98f8af41ef971bb4aeeadd04f1":{
        "scriptId":"u4"},
      "5a6a8b09d0fa44cb996ec710d732c51a":{
        "scriptId":"u5"},
      "c346be56b3b148c394d01867f96020ed":{
        "scriptId":"u6"},
      "bee383944d00498cb4790c08da5a6c34":{
        "scriptId":"u7"}},
    "083192dcc83a4e63865f7969ca396fa6":{
      "scriptId":"u8",
      "3a8352b0bdb94ce9a3089c99ad30d525":{
        "scriptId":"u9"},
      "5e026ecd19c44faaaf17922e877148fb":{
        "scriptId":"u10"},
      "daf03b54e1b54a3e931b529609a504e5":{
        "scriptId":"u11"},
      "9b46f5ced4cd494bb946afb473a1d17b":{
        "scriptId":"u12"}},
    "fbb3899efd6c44c3aa7fc79fe4e0ff8d":{
      "scriptId":"u13"},
    "9081c3ee11ca43f98286800f182865d9":{
      "scriptId":"u14"},
    "60c30e8dc48d4e7aab21eb3bb35306bb":{
      "scriptId":"u15"},
    "3d940294120a4bdd960ee4c32347a543":{
      "scriptId":"u16"},
    "0ff253a87cbc4b17b6c92dd576952384":{
      "scriptId":"u17"},
    "ec472804eb334ee0b16dd756bf0a36a7":{
      "scriptId":"u18"},
    "a21e4f6bd73545679ca269841cb70ba7":{
      "scriptId":"u19"},
    "35569d0d038540f9962f15704da91a36":{
      "scriptId":"u20"},
    "cfca368464fe4b9aacaa9def5c22c5a8":{
      "scriptId":"u21"}}});