$axure.loadCurrentPage({
  "url":"首页.html",
  "generationDate":new Date(1420944053623.56),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"ffb14b61d0624e278e31f51a387574de",
    "type":"Axure:Page",
    "name":"首页",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
      "a":{
}},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"e4e09123b20c4d0aa7e7fae813002166",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
            "a":{
}},
          "masterId":"7c1029c1d457473e99700ff7187709fd"},
{
          "id":"6934c554077344b2bb40c52f5f8fe25f",
          "label":"轮播图",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":50},
            "size":{
              "width":200,
              "height":200},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
              "size":{
                "width":320,
                "height":90},
              "limbo":false}},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"0e087f1400744c84ba93cac9b2daae40",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[]}]},
{
          "id":"f7fda80f5ec844f1a7f68e9b0f4a873b",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":101,
              "y":117},
            "size":{
              "width":100,
              "height":16},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
              "location":{
                "x":117,
                "y":114},
              "size":{
                "width":9,
                "height":16},
              "limbo":false}},
          "objects":[{
              "id":"fe2e9f91fdea448db750bbc857f8b327",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":101,
                  "y":117},
                "size":{
                  "width":100,
                  "height":16},
                "limbo":true},
              "adaptiveStyles":{
                "a":{
}}}]},
{
          "id":"4246dff5a00a48bfb9d8ced1c848bf71",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":111,
              "y":127},
            "size":{
              "width":100,
              "height":16},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
              "location":{
                "x":136,
                "y":114},
              "size":{
                "width":9,
                "height":16},
              "limbo":false}},
          "objects":[{
              "id":"b6537fbbca154b508cc856bc1de237db",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":111,
                  "y":127},
                "size":{
                  "width":100,
                  "height":16},
                "limbo":true},
              "adaptiveStyles":{
                "a":{
}}}]},
{
          "id":"a2323f6e28c2489ca5f694218fd0fda4",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":121,
              "y":137},
            "size":{
              "width":100,
              "height":16},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
              "location":{
                "x":156,
                "y":114},
              "size":{
                "width":9,
                "height":16},
              "limbo":false}},
          "objects":[{
              "id":"1905ec6fd1d14718aefce8ccb2435d08",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":121,
                  "y":137},
                "size":{
                  "width":100,
                  "height":16},
                "limbo":true},
              "adaptiveStyles":{
                "a":{
}}}]},
{
          "id":"8d680b4b4a394150866e9608f894e7da",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":131,
              "y":147},
            "size":{
              "width":100,
              "height":16},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
              "location":{
                "x":174,
                "y":114},
              "size":{
                "width":9,
                "height":16},
              "limbo":false}},
          "objects":[{
              "id":"ea2844c9b0ad40eaba7bbfb39a0268a3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":131,
                  "y":147},
                "size":{
                  "width":100,
                  "height":16},
                "limbo":true},
              "adaptiveStyles":{
                "a":{
}}}]},
{
          "id":"5e0cb169cdec4c279672fe6140982b1b",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":141,
              "y":157},
            "size":{
              "width":100,
              "height":16},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
              "location":{
                "x":193,
                "y":114},
              "size":{
                "width":9,
                "height":16},
              "limbo":false}},
          "objects":[{
              "id":"d88d6e305c3f432c87c9e3b2d105a8c5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":141,
                  "y":157},
                "size":{
                  "width":100,
                  "height":16},
                "limbo":true},
              "adaptiveStyles":{
                "a":{
}}}]},
{
          "id":"e01b9db5846b4b83ab3ec0be8bfc14d5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":144,
              "y":64},
            "size":{
              "width":40,
              "height":16},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
              "size":{
                "width":40,
                "height":16},
              "limbo":false}},
          "objects":[{
              "id":"86a94f2a00c943cb80c51dcbc5f6a4e3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":144,
                  "y":64},
                "size":{
                  "width":40,
                  "height":16},
                "limbo":true},
              "adaptiveStyles":{
                "a":{
}}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "normal~a":"resources/images/transparent.gif"}},
{
          "id":"13ca87e461b04242b6bcc44277853e9f",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":150},
            "size":{
              "width":100,
              "height":25},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
              "size":{
                "width":140,
                "height":260},
              "limbo":false}}},
{
          "id":"c536ce80913349dc8a4a4030d7ebf860",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":160,
              "y":150},
            "size":{
              "width":100,
              "height":25},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
              "size":{
                "width":151,
                "height":130},
              "limbo":false}}},
{
          "id":"424a40f0f3ca4beeb0ee7460060cf80c",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":160,
              "y":280},
            "size":{
              "width":100,
              "height":25},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
              "location":{
                "x":160,
                "y":290},
              "size":{
                "width":151,
                "height":120},
              "limbo":false}}},
{
          "id":"6a96e2499beb4754b32dbdeb7e30ae75",
          "label":"轮播图",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":60},
            "size":{
              "width":200,
              "height":200},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
              "size":{
                "width":320,
                "height":90},
              "limbo":false}},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"dea2bd19bc87433f933acb140cdb1c28",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[]}]},
{
          "id":"ab90384732fd4b3b8c3cb7aa7b51a1c2",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":111,
              "y":127},
            "size":{
              "width":100,
              "height":16},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
              "size":{
                "width":9,
                "height":16},
              "limbo":false}},
          "objects":[{
              "id":"91c1a6bc11d54b40b9ed0c70aa2d9b9e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":111,
                  "y":127},
                "size":{
                  "width":100,
                  "height":16},
                "limbo":true},
              "adaptiveStyles":{
                "a":{
}}}]},
{
          "id":"c54453df76384322acb9b6272868e0d8",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":121,
              "y":137},
            "size":{
              "width":100,
              "height":16},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
              "size":{
                "width":9,
                "height":16},
              "limbo":false}},
          "objects":[{
              "id":"1e4a54d2638b4ff5b96ad7210840ccc6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":121,
                  "y":137},
                "size":{
                  "width":100,
                  "height":16},
                "limbo":true},
              "adaptiveStyles":{
                "a":{
}}}]},
{
          "id":"bae3056bdf1d4c7cb7ea1d4d23083ded",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":131,
              "y":147},
            "size":{
              "width":100,
              "height":16},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
              "size":{
                "width":9,
                "height":16},
              "limbo":false}},
          "objects":[{
              "id":"20d68273b36e462f9ae86ed13a1e7d0f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":131,
                  "y":147},
                "size":{
                  "width":100,
                  "height":16},
                "limbo":true},
              "adaptiveStyles":{
                "a":{
}}}]},
{
          "id":"56c70e8d1e464d7ca12be59d9f80372f",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":141,
              "y":157},
            "size":{
              "width":100,
              "height":16},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
              "size":{
                "width":9,
                "height":16},
              "limbo":false}},
          "objects":[{
              "id":"d02e718a77774373b5bd74750ef9bca3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":141,
                  "y":157},
                "size":{
                  "width":100,
                  "height":16},
                "limbo":true},
              "adaptiveStyles":{
                "a":{
}}}]},
{
          "id":"b6be08d23429473e9bf61482b7c12f03",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":151,
              "y":167},
            "size":{
              "width":100,
              "height":16},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
              "size":{
                "width":9,
                "height":16},
              "limbo":false}},
          "objects":[{
              "id":"ea323f6cf54f4cb69dffd1b8c5042f11",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":151,
                  "y":167},
                "size":{
                  "width":100,
                  "height":16},
                "limbo":true},
              "adaptiveStyles":{
                "a":{
}}}]},
{
          "id":"87405852565d4a75b7d16cc0ad16a737",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":154,
              "y":74},
            "size":{
              "width":40,
              "height":16},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
              "size":{
                "width":40,
                "height":16},
              "limbo":false}},
          "objects":[{
              "id":"90402b31e6f24ad287040f08ab879f3b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":154,
                  "y":74},
                "size":{
                  "width":40,
                  "height":16},
                "limbo":true},
              "adaptiveStyles":{
                "a":{
}}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "normal~a":"resources/images/transparent.gif"}},
{
          "id":"7ce9467e4500464ca067d2f71002c6eb",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":160},
            "size":{
              "width":100,
              "height":25},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
              "size":{
                "width":140,
                "height":260},
              "limbo":false}}},
{
          "id":"fda99a3f6ce243d7a742e66068e4e33a",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":170,
              "y":160},
            "size":{
              "width":100,
              "height":25},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
              "size":{
                "width":151,
                "height":130},
              "limbo":false}}},
{
          "id":"8096a6ff656c466487f48302548af258",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":170,
              "y":290},
            "size":{
              "width":100,
              "height":25},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
              "size":{
                "width":151,
                "height":120},
              "limbo":false}}}]}},
  "masters":{
    "7c1029c1d457473e99700ff7187709fd":{
      "packageId":"7c1029c1d457473e99700ff7187709fd",
      "type":"Axure:Master",
      "name":"panel",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
        "a":{
}},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"0ae1bd5e40274537b2856776be253905",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "size":{
                "width":320,
                "height":480}},
            "adaptiveStyles":{
              "a":{
}},
            "objects":[{
                "id":"de4dbd77e1084cf3b0bdfaca506459e7",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":320,
                    "height":480}},
                "adaptiveStyles":{
                  "a":{
}}}],
            "images":{
              "normal~":"images/首页/u1.png"}},
{
            "id":"a1d2b7acb03b42f39836d72995ce3c89",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "size":{
                "width":200,
                "height":100},
              "limbo":true},
            "adaptiveStyles":{
              "a":{
                "size":{
                  "width":320,
                  "height":50},
                "limbo":false}},
            "objects":[{
                "id":"c5d8dbd025e841768d05c5b8a25905f4",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":200,
                    "height":100},
                  "limbo":true},
                "adaptiveStyles":{
                  "a":{
}}}],
            "images":{
              "normal~":"images/main_page/u0.png",
              "normal~a":"images/main_page/u0_a.png"}},
{
            "id":"ed384f2863f744cd80eedbbfea843502",
            "label":"",
            "type":"button",
            "styleType":"button",
            "visible":true,
            "style":{
              "location":{
                "x":10,
                "y":12.5},
              "size":{
                "width":100,
                "height":25},
              "limbo":true},
            "adaptiveStyles":{
              "a":{
                "location":{
                  "x":10,
                  "y":14},
                "size":{
                  "width":70,
                  "height":23},
                "limbo":false}}},
{
            "id":"3044657053e64ccf9cb5c7fb481274dd",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":118,
                "y":18},
              "size":{
                "width":32,
                "height":16},
              "limbo":true},
            "adaptiveStyles":{
              "a":{
                "fontSize":"20px",
                "horizontalAlignment":"center",
                "location":{
                  "x":119,
                  "y":14},
                "size":{
                  "width":82,
                  "height":22},
                "limbo":false}},
            "objects":[{
                "id":"1f2bb3eca6fb419cbfa369719a5c4581",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":118,
                    "y":18},
                  "size":{
                    "width":32,
                    "height":16},
                  "limbo":true},
                "adaptiveStyles":{
                  "a":{
}}}],
            "images":{
              "normal~":"resources/images/transparent.gif",
              "normal~a":"resources/images/transparent.gif"}},
{
            "id":"0f6be40f8d104cf7b53b61366d48415e",
            "label":"",
            "type":"button",
            "styleType":"button",
            "visible":true,
            "style":{
              "location":{
                "x":211,
                "y":13},
              "size":{
                "width":100,
                "height":25},
              "limbo":true},
            "adaptiveStyles":{
              "a":{
                "location":{
                  "x":240,
                  "y":13},
                "size":{
                  "width":71,
                  "height":25},
                "limbo":false}}},
{
            "id":"869c2cb3ba004c9b91dfa63de40c7a62",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":10,
                "y":430},
              "size":{
                "width":100,
                "height":30},
              "limbo":true,
              "cornerRadiusTopLeft":"5"},
            "adaptiveStyles":{
              "a":{
                "location":{
                  "x":0,
                  "y":420},
                "size":{
                  "width":64,
                  "height":60},
                "limbo":false}},
            "objects":[{
                "id":"9079939acf26437fb18e74b43efebe36",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":10,
                    "y":430},
                  "size":{
                    "width":100,
                    "height":30},
                  "limbo":true,
                  "cornerRadiusTopLeft":"5"},
                "adaptiveStyles":{
                  "a":{
}}}],
            "images":{
              "normal~":"images/main_page/u8.png",
              "normal~a":"images/main_page/u8_a.png"}},
{
            "id":"b2c853906daa412e862059634839b109",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":10,
                "y":430},
              "size":{
                "width":100,
                "height":30},
              "limbo":true,
              "cornerRadiusTopLeft":"5"},
            "adaptiveStyles":{
              "a":{
                "location":{
                  "x":128,
                  "y":420},
                "size":{
                  "width":64,
                  "height":60},
                "limbo":false}},
            "objects":[{
                "id":"82cb0ff64bd6495c8fc1b58a8648d533",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":10,
                    "y":430},
                  "size":{
                    "width":100,
                    "height":30},
                  "limbo":true,
                  "cornerRadiusTopLeft":"5"},
                "adaptiveStyles":{
                  "a":{
}}}],
            "images":{
              "normal~":"images/main_page/u8.png",
              "normal~a":"images/main_page/u8_a.png"}},
{
            "id":"3c5ba3a4118f4f1da6ccdccd47f37e8d",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":20,
                "y":440},
              "size":{
                "width":100,
                "height":30},
              "limbo":true,
              "cornerRadiusTopLeft":"5"},
            "adaptiveStyles":{
              "a":{
                "location":{
                  "x":192,
                  "y":420},
                "size":{
                  "width":64,
                  "height":60},
                "limbo":false}},
            "objects":[{
                "id":"c0299d8cf9294db0b0162c530379d588",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":20,
                    "y":440},
                  "size":{
                    "width":100,
                    "height":30},
                  "limbo":true,
                  "cornerRadiusTopLeft":"5"},
                "adaptiveStyles":{
                  "a":{
}}}],
            "images":{
              "normal~":"images/main_page/u8.png",
              "normal~a":"images/main_page/u8_a.png"}},
{
            "id":"0a40416b361c4135abdda68390869716",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":30,
                "y":450},
              "size":{
                "width":100,
                "height":30},
              "limbo":true,
              "cornerRadiusTopLeft":"5"},
            "adaptiveStyles":{
              "a":{
                "location":{
                  "x":256,
                  "y":420},
                "size":{
                  "width":64,
                  "height":60},
                "limbo":false}},
            "objects":[{
                "id":"e689cb86f3374b06b9ac63cadbbc65f7",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":30,
                    "y":450},
                  "size":{
                    "width":100,
                    "height":30},
                  "limbo":true,
                  "cornerRadiusTopLeft":"5"},
                "adaptiveStyles":{
                  "a":{
}}}],
            "images":{
              "normal~":"images/main_page/u8.png",
              "normal~a":"images/main_page/u8_a.png"}},
{
            "id":"9f35eca92c9749919a66b9ac91074a28",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":150,
                "y":430},
              "size":{
                "width":100,
                "height":30},
              "limbo":true,
              "cornerRadiusTopLeft":"5"},
            "adaptiveStyles":{
              "a":{
                "location":{
                  "x":64,
                  "y":420},
                "size":{
                  "width":64,
                  "height":60},
                "limbo":false}},
            "objects":[{
                "id":"e79cc7b70f4941bdbdb838b7c5075a1b",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":150,
                    "y":430},
                  "size":{
                    "width":100,
                    "height":30},
                  "limbo":true,
                  "cornerRadiusTopLeft":"5"},
                "adaptiveStyles":{
                  "a":{
}}}],
            "images":{
              "normal~":"images/main_page/u8.png",
              "normal~a":"images/main_page/u8_a.png"}}]}}},
  "objectPaths":{
    "e4e09123b20c4d0aa7e7fae813002166":{
      "scriptId":"u0",
      "0ae1bd5e40274537b2856776be253905":{
        "scriptId":"u1"},
      "de4dbd77e1084cf3b0bdfaca506459e7":{
        "scriptId":"u2"},
      "a1d2b7acb03b42f39836d72995ce3c89":{
        "scriptId":"u3"},
      "c5d8dbd025e841768d05c5b8a25905f4":{
        "scriptId":"u4"},
      "ed384f2863f744cd80eedbbfea843502":{
        "scriptId":"u5"},
      "3044657053e64ccf9cb5c7fb481274dd":{
        "scriptId":"u6"},
      "1f2bb3eca6fb419cbfa369719a5c4581":{
        "scriptId":"u7"},
      "0f6be40f8d104cf7b53b61366d48415e":{
        "scriptId":"u8"},
      "869c2cb3ba004c9b91dfa63de40c7a62":{
        "scriptId":"u9"},
      "9079939acf26437fb18e74b43efebe36":{
        "scriptId":"u10"},
      "b2c853906daa412e862059634839b109":{
        "scriptId":"u11"},
      "82cb0ff64bd6495c8fc1b58a8648d533":{
        "scriptId":"u12"},
      "3c5ba3a4118f4f1da6ccdccd47f37e8d":{
        "scriptId":"u13"},
      "c0299d8cf9294db0b0162c530379d588":{
        "scriptId":"u14"},
      "0a40416b361c4135abdda68390869716":{
        "scriptId":"u15"},
      "e689cb86f3374b06b9ac63cadbbc65f7":{
        "scriptId":"u16"},
      "9f35eca92c9749919a66b9ac91074a28":{
        "scriptId":"u17"},
      "e79cc7b70f4941bdbdb838b7c5075a1b":{
        "scriptId":"u18"}},
    "6934c554077344b2bb40c52f5f8fe25f":{
      "scriptId":"u19"},
    "f7fda80f5ec844f1a7f68e9b0f4a873b":{
      "scriptId":"u20"},
    "fe2e9f91fdea448db750bbc857f8b327":{
      "scriptId":"u21"},
    "4246dff5a00a48bfb9d8ced1c848bf71":{
      "scriptId":"u22"},
    "b6537fbbca154b508cc856bc1de237db":{
      "scriptId":"u23"},
    "a2323f6e28c2489ca5f694218fd0fda4":{
      "scriptId":"u24"},
    "1905ec6fd1d14718aefce8ccb2435d08":{
      "scriptId":"u25"},
    "8d680b4b4a394150866e9608f894e7da":{
      "scriptId":"u26"},
    "ea2844c9b0ad40eaba7bbfb39a0268a3":{
      "scriptId":"u27"},
    "5e0cb169cdec4c279672fe6140982b1b":{
      "scriptId":"u28"},
    "d88d6e305c3f432c87c9e3b2d105a8c5":{
      "scriptId":"u29"},
    "e01b9db5846b4b83ab3ec0be8bfc14d5":{
      "scriptId":"u30"},
    "86a94f2a00c943cb80c51dcbc5f6a4e3":{
      "scriptId":"u31"},
    "13ca87e461b04242b6bcc44277853e9f":{
      "scriptId":"u32"},
    "c536ce80913349dc8a4a4030d7ebf860":{
      "scriptId":"u33"},
    "424a40f0f3ca4beeb0ee7460060cf80c":{
      "scriptId":"u34"},
    "6a96e2499beb4754b32dbdeb7e30ae75":{
      "scriptId":"u35"},
    "ab90384732fd4b3b8c3cb7aa7b51a1c2":{
      "scriptId":"u36"},
    "91c1a6bc11d54b40b9ed0c70aa2d9b9e":{
      "scriptId":"u37"},
    "c54453df76384322acb9b6272868e0d8":{
      "scriptId":"u38"},
    "1e4a54d2638b4ff5b96ad7210840ccc6":{
      "scriptId":"u39"},
    "bae3056bdf1d4c7cb7ea1d4d23083ded":{
      "scriptId":"u40"},
    "20d68273b36e462f9ae86ed13a1e7d0f":{
      "scriptId":"u41"},
    "56c70e8d1e464d7ca12be59d9f80372f":{
      "scriptId":"u42"},
    "d02e718a77774373b5bd74750ef9bca3":{
      "scriptId":"u43"},
    "b6be08d23429473e9bf61482b7c12f03":{
      "scriptId":"u44"},
    "ea323f6cf54f4cb69dffd1b8c5042f11":{
      "scriptId":"u45"},
    "87405852565d4a75b7d16cc0ad16a737":{
      "scriptId":"u46"},
    "90402b31e6f24ad287040f08ab879f3b":{
      "scriptId":"u47"},
    "7ce9467e4500464ca067d2f71002c6eb":{
      "scriptId":"u48"},
    "fda99a3f6ce243d7a742e66068e4e33a":{
      "scriptId":"u49"},
    "8096a6ff656c466487f48302548af258":{
      "scriptId":"u50"}}});