$axure.loadCurrentPage({
  "url":"技师展示界面选定服务入口.html",
  "generationDate":new Date(1421557100880.19),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"isLogin"],
  "page":{
    "packageId":"0c8cf3d010fe4539be40f62e5dadb46c",
    "type":"Axure:Page",
    "name":"技师展示界面选定服务入口",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
      "a":{
}},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"dc47beda7cc0447ca02f2b456890589d",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
            "a":{
}},
          "masterId":"c0462b19eeab412787c3050c808291eb"},
{
          "id":"ea3a8245a22d466faf4afbca6418e84c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":120,
              "y":14},
            "size":{
              "width":81,
              "height":23}},
          "adaptiveStyles":{
            "a":{
              "location":{
                "x":120,
                "y":14}}},
          "objects":[{
              "id":"18a9bcffb2c94f66abd2324077b0677a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":120,
                  "y":14},
                "size":{
                  "width":81,
                  "height":23}},
              "adaptiveStyles":{
                "a":{
}}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "normal~a":"resources/images/transparent.gif"}},
{
          "id":"fd3db6c451ae4fcb9e9d634d258c6215",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1,
              "y":50},
            "size":{
              "width":319,
              "height":160}},
          "adaptiveStyles":{
            "a":{
}},
          "objects":[{
              "id":"216a963b53884138b66d6f462bdd135f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1,
                  "y":50},
                "size":{
                  "width":319,
                  "height":160}},
              "adaptiveStyles":{
                "a":{
}}}],
          "images":{
            "normal~":"images/技师展示界面/u8.png"}},
{
          "id":"bed6f4871b6344db9eb0b7860e59864b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":60},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
            "a":{
}},
          "objects":[{
              "id":"bdd6d2501bba45faad4ca1fbd0e84573",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":60},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
                "a":{
}}}],
          "images":{
            "normal~":"images/技师展示界面/u10.png"}},
{
          "id":"372e3c098b7f43949429a981a517e413",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":60},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
            "a":{
              "size":{
                "width":53,
                "height":16}}},
          "objects":[{
              "id":"3975680cf81b4900a203eb9f9dae06cf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":60},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
                "a":{
}}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "normal~a":"resources/images/transparent.gif"}},
{
          "id":"44194e86f2c04b2faa33a90646c1bf3e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":86},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
            "a":{
              "size":{
                "width":53,
                "height":16}}},
          "objects":[{
              "id":"42633669293a44ea96b68394bdd970f8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":86},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
                "a":{
}}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "normal~a":"resources/images/transparent.gif"}},
{
          "id":"1b9f31f0c81a4af3aeca2c58ee972686",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":112},
            "size":{
              "width":80,
              "height":16}},
          "adaptiveStyles":{
            "a":{
              "size":{
                "width":80,
                "height":16}}},
          "objects":[{
              "id":"7596d1b0e4924881b51f924ba687edf9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":112},
                "size":{
                  "width":80,
                  "height":16}},
              "adaptiveStyles":{
                "a":{
}}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "normal~a":"resources/images/transparent.gif"}},
{
          "id":"89eee683ae134c97b6e439f097a9a1f7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":6,
              "y":138},
            "size":{
              "width":90,
              "height":32}},
          "adaptiveStyles":{
            "a":{
}},
          "objects":[{
              "id":"16856e0cc979456ab6a167b9b8130d6b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":6,
                  "y":138},
                "size":{
                  "width":90,
                  "height":32}},
              "adaptiveStyles":{
                "a":{
}}}],
          "images":{
            "normal~":"images/技师展示界面/u18.png"}},
{
          "id":"79d71d3655f84e2eb9916976b19c50a1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":122,
              "y":138},
            "size":{
              "width":90,
              "height":32}},
          "adaptiveStyles":{
            "a":{
}},
          "objects":[{
              "id":"232e13bc4ae847648ca6797d99172fa6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":122,
                  "y":138},
                "size":{
                  "width":90,
                  "height":32}},
              "adaptiveStyles":{
                "a":{
}}}],
          "images":{
            "normal~":"images/技师展示界面/u18.png"}},
{
          "id":"24271a5457044ea59a1ac6706f3d19d1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":226,
              "y":138},
            "size":{
              "width":90,
              "height":32}},
          "adaptiveStyles":{
            "a":{
}},
          "objects":[{
              "id":"c7df154a162d4f8c88a44fe454cdfe79",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":226,
                  "y":138},
                "size":{
                  "width":90,
                  "height":32}},
              "adaptiveStyles":{
                "a":{
}}}],
          "images":{
            "normal~":"images/技师展示界面/u18.png"}},
{
          "id":"3aa05d43f42d4dafa2a0fea3356c5d14",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":6,
              "y":174},
            "size":{
              "width":310,
              "height":30}},
          "adaptiveStyles":{
            "a":{
}},
          "objects":[{
              "id":"4d231d1ab28e4ed9b096127d8edfcf6e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":6,
                  "y":174},
                "size":{
                  "width":310,
                  "height":30}},
              "adaptiveStyles":{
                "a":{
}}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 客户平价界面",
                      "target":{
                        "targetType":"page",
                        "url":"客户平价界面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/技师展示界面/u24.png"}},
{
          "id":"61c1979b0d904f4dac6ae3c10595d518",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":210,
              "y":81.5},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
            "a":{
}},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 技师个人信息",
                      "target":{
                        "targetType":"page",
                        "url":"技师个人信息.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"a02ef390d50d4a30a667a6b4cc5e3abb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":6,
              "y":220},
            "size":{
              "width":310,
              "height":150}},
          "adaptiveStyles":{
            "a":{
}},
          "objects":[{
              "id":"f8814b097c2b4652b62eb1a2e6166b4b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":6,
                  "y":220},
                "size":{
                  "width":310,
                  "height":150}},
              "adaptiveStyles":{
                "a":{
}}}],
          "images":{
            "normal~":"images/技师展示界面/u40.png"}},
{
          "id":"d4ee960e9b1b490e977242e0d81ccb0d",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":400},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
            "a":{
}},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"82dfd57440004ee0b0b86e6760984ca3",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"cca71def257f4faa989543f5db7a03ea",
                  "label":"",
                  "parentDynamicPanel":"d4ee960e9b1b490e977242e0d81ccb0d",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":320,
                      "height":90}},
                  "adaptiveStyles":{
                    "a":{
}},
                  "objects":[{
                      "id":"79c5883a8da7404eb38671a87e51a190",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"d4ee960e9b1b490e977242e0d81ccb0d",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":320,
                          "height":90}},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"images/技师浏览/u14_a.png"}},
{
                  "id":"e019719e342d48a0bfafd959f7bdf2cf",
                  "label":"",
                  "parentDynamicPanel":"d4ee960e9b1b490e977242e0d81ccb0d",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":6,
                      "y":10},
                    "size":{
                      "width":74,
                      "height":70}},
                  "adaptiveStyles":{
                    "a":{
}},
                  "objects":[{
                      "id":"92ff1b23735f46149874a431a6484efb",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"d4ee960e9b1b490e977242e0d81ccb0d",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":6,
                          "y":10},
                        "size":{
                          "width":74,
                          "height":70}},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"images/项目大类型选择/u21.png"}},
{
                  "id":"daf3eed119744ce58a15c693c15c24b8",
                  "label":"",
                  "parentDynamicPanel":"d4ee960e9b1b490e977242e0d81ccb0d",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":90,
                      "y":14},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
                    "a":{
                      "size":{
                        "width":53,
                        "height":16}}},
                  "objects":[{
                      "id":"8a3ca10b7e5e4d28abaad108b29c08be",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"d4ee960e9b1b490e977242e0d81ccb0d",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":90,
                          "y":14},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "normal~a":"resources/images/transparent.gif"}},
{
                  "id":"b93bae512b224e58ab99de6112d2227b",
                  "label":"",
                  "parentDynamicPanel":"d4ee960e9b1b490e977242e0d81ccb0d",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":90,
                      "y":40},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
                    "a":{
                      "size":{
                        "width":53,
                        "height":16}}},
                  "objects":[{
                      "id":"8dd9f325e05d46fdb6bc0fd42f02a0ca",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"d4ee960e9b1b490e977242e0d81ccb0d",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":90,
                          "y":40},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "normal~a":"resources/images/transparent.gif"}},
{
                  "id":"beadcc9b64714f02813f2d9c31556cca",
                  "label":"",
                  "parentDynamicPanel":"d4ee960e9b1b490e977242e0d81ccb0d",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":90,
                      "y":66},
                    "size":{
                      "width":144,
                      "height":16}},
                  "adaptiveStyles":{
                    "a":{
                      "size":{
                        "width":144,
                        "height":16}}},
                  "objects":[{
                      "id":"7260079fba82457aab3d230f66a3cbc7",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"d4ee960e9b1b490e977242e0d81ccb0d",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":90,
                          "y":66},
                        "size":{
                          "width":144,
                          "height":16}},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "normal~a":"resources/images/transparent.gif"}},
{
                  "id":"284987d9505543078677a74dd43de21f",
                  "label":"",
                  "parentDynamicPanel":"d4ee960e9b1b490e977242e0d81ccb0d",
                  "type":"button",
                  "styleType":"button",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":220,
                      "y":30},
                    "size":{
                      "width":84,
                      "height":26}},
                  "adaptiveStyles":{
                    "a":{
}},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 项目详情",
                              "target":{
                                "targetType":"page",
                                "url":"项目详情.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true}]}]},
{
          "id":"c9f9db17dfeb4e92bb575cf5bb5d808c",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":580},
            "size":{
              "width":320,
              "height":40}},
          "adaptiveStyles":{
            "a":{
}},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 订单确认",
                      "target":{
                        "targetType":"page",
                        "url":"订单确认.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"7d3f218cfff04396b52bfdc20559b54b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":134,
              "y":380},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
            "a":{
              "location":{
                "x":134,
                "y":380}}},
          "objects":[{
              "id":"6b02c51766e142288890735a1239fdfc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":134,
                  "y":380},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
                "a":{
}}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "normal~a":"resources/images/transparent.gif"}},
{
          "id":"48d567ea46b2409b815685e387dce321",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":330,
              "y":437},
            "size":{
              "width":118,
              "height":16}},
          "adaptiveStyles":{
            "a":{
}},
          "objects":[{
              "id":"30a1f19d1b2e47139db6ef6d5da17711",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":330,
                  "y":437},
                "size":{
                  "width":118,
                  "height":16}},
              "adaptiveStyles":{
                "a":{
}}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a621af8e8fb34d33b1a5bb146d701434",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":490},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
            "a":{
}},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"378ff36555674cdd84db6f73be3be297",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"d0322c26f10d4e09b4a9e6557e8ff8b6",
                  "label":"",
                  "parentDynamicPanel":"a621af8e8fb34d33b1a5bb146d701434",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":320,
                      "height":90}},
                  "adaptiveStyles":{
                    "a":{
}},
                  "objects":[{
                      "id":"886c6fde88a84198bd4dc85ea707dd05",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"a621af8e8fb34d33b1a5bb146d701434",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":320,
                          "height":90}},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"images/技师浏览/u14_a.png"}},
{
                  "id":"09820920270949368e8d6a696a898c37",
                  "label":"",
                  "parentDynamicPanel":"a621af8e8fb34d33b1a5bb146d701434",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":6,
                      "y":10},
                    "size":{
                      "width":74,
                      "height":70}},
                  "adaptiveStyles":{
                    "a":{
}},
                  "objects":[{
                      "id":"7fbb473354ed41b7829baad843bc3d46",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"a621af8e8fb34d33b1a5bb146d701434",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":6,
                          "y":10},
                        "size":{
                          "width":74,
                          "height":70}},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"images/项目大类型选择/u21.png"}},
{
                  "id":"30b0e76e6ad54614acd61fbc14ce7a1d",
                  "label":"",
                  "parentDynamicPanel":"a621af8e8fb34d33b1a5bb146d701434",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":90,
                      "y":14},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
                    "a":{
                      "size":{
                        "width":53,
                        "height":16}}},
                  "objects":[{
                      "id":"087deb389013423da1340f21ba703cd7",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"a621af8e8fb34d33b1a5bb146d701434",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":90,
                          "y":14},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "normal~a":"resources/images/transparent.gif"}},
{
                  "id":"b16c92adb15347b49a4ff4762cad5972",
                  "label":"",
                  "parentDynamicPanel":"a621af8e8fb34d33b1a5bb146d701434",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":90,
                      "y":40},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
                    "a":{
                      "size":{
                        "width":53,
                        "height":16}}},
                  "objects":[{
                      "id":"03a7da5de6c6489ebb47e5666ed19731",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"a621af8e8fb34d33b1a5bb146d701434",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":90,
                          "y":40},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "normal~a":"resources/images/transparent.gif"}},
{
                  "id":"b8cd0f2d3f5d4f52a157270234888c91",
                  "label":"",
                  "parentDynamicPanel":"a621af8e8fb34d33b1a5bb146d701434",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":90,
                      "y":66},
                    "size":{
                      "width":144,
                      "height":16}},
                  "adaptiveStyles":{
                    "a":{
                      "size":{
                        "width":144,
                        "height":16}}},
                  "objects":[{
                      "id":"bbc74924297e48be9965488523d21615",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"a621af8e8fb34d33b1a5bb146d701434",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":90,
                          "y":66},
                        "size":{
                          "width":144,
                          "height":16}},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "normal~a":"resources/images/transparent.gif"}},
{
                  "id":"0df8308aa4dc43f5a25cce3f9808c673",
                  "label":"",
                  "parentDynamicPanel":"a621af8e8fb34d33b1a5bb146d701434",
                  "type":"button",
                  "styleType":"button",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":220,
                      "y":30},
                    "size":{
                      "width":84,
                      "height":26}},
                  "adaptiveStyles":{
                    "a":{
}},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 项目详情",
                              "target":{
                                "targetType":"page",
                                "url":"项目详情.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true}]}]}]}},
  "masters":{
    "c0462b19eeab412787c3050c808291eb":{
      "packageId":"c0462b19eeab412787c3050c808291eb",
      "type":"Axure:Master",
      "name":"上返回栏",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
        "a":{
}},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"193809c55b604a239711248fd3b92b17",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "size":{
                "width":320,
                "height":480}},
            "adaptiveStyles":{
              "a":{
}},
            "objects":[{
                "id":"fb301888262643c4b28fcad2d5ca7aa9",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":320,
                    "height":480}},
                "adaptiveStyles":{
                  "a":{
}}}],
            "images":{
              "normal~":"images/主页/u1_a.png"}},
{
            "id":"3a8352b0bdb94ce9a3089c99ad30d525",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "size":{
                "width":200,
                "height":100},
              "limbo":true},
            "adaptiveStyles":{
              "a":{
                "size":{
                  "width":320,
                  "height":50},
                "limbo":false}},
            "objects":[{
                "id":"5e026ecd19c44faaaf17922e877148fb",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":200,
                    "height":100},
                  "limbo":true},
                "adaptiveStyles":{
                  "a":{
}}}],
            "images":{
              "normal~":"images/主页/u9.png",
              "normal~a":"images/主页/u9_a.png"}},
{
            "id":"9b46f5ced4cd494bb946afb473a1d17b",
            "label":"",
            "type":"button",
            "styleType":"button",
            "visible":true,
            "style":{
              "location":{
                "x":211,
                "y":13},
              "size":{
                "width":100,
                "height":25},
              "limbo":true},
            "adaptiveStyles":{
              "a":{
                "location":{
                  "x":10,
                  "y":12.5},
                "size":{
                  "width":71,
                  "height":25},
                "limbo":false}},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 返回",
                        "target":{
                          "targetType":"backUrl",
                          "includeVariables":false},
                        "linkType":"current"}]}]}},
            "tabbable":true}]}}},
  "objectPaths":{
    "dc47beda7cc0447ca02f2b456890589d":{
      "scriptId":"u0",
      "193809c55b604a239711248fd3b92b17":{
        "scriptId":"u1"},
      "fb301888262643c4b28fcad2d5ca7aa9":{
        "scriptId":"u2"},
      "3a8352b0bdb94ce9a3089c99ad30d525":{
        "scriptId":"u3"},
      "5e026ecd19c44faaaf17922e877148fb":{
        "scriptId":"u4"},
      "9b46f5ced4cd494bb946afb473a1d17b":{
        "scriptId":"u5"}},
    "ea3a8245a22d466faf4afbca6418e84c":{
      "scriptId":"u6"},
    "18a9bcffb2c94f66abd2324077b0677a":{
      "scriptId":"u7"},
    "fd3db6c451ae4fcb9e9d634d258c6215":{
      "scriptId":"u8"},
    "216a963b53884138b66d6f462bdd135f":{
      "scriptId":"u9"},
    "bed6f4871b6344db9eb0b7860e59864b":{
      "scriptId":"u10"},
    "bdd6d2501bba45faad4ca1fbd0e84573":{
      "scriptId":"u11"},
    "372e3c098b7f43949429a981a517e413":{
      "scriptId":"u12"},
    "3975680cf81b4900a203eb9f9dae06cf":{
      "scriptId":"u13"},
    "44194e86f2c04b2faa33a90646c1bf3e":{
      "scriptId":"u14"},
    "42633669293a44ea96b68394bdd970f8":{
      "scriptId":"u15"},
    "1b9f31f0c81a4af3aeca2c58ee972686":{
      "scriptId":"u16"},
    "7596d1b0e4924881b51f924ba687edf9":{
      "scriptId":"u17"},
    "89eee683ae134c97b6e439f097a9a1f7":{
      "scriptId":"u18"},
    "16856e0cc979456ab6a167b9b8130d6b":{
      "scriptId":"u19"},
    "79d71d3655f84e2eb9916976b19c50a1":{
      "scriptId":"u20"},
    "232e13bc4ae847648ca6797d99172fa6":{
      "scriptId":"u21"},
    "24271a5457044ea59a1ac6706f3d19d1":{
      "scriptId":"u22"},
    "c7df154a162d4f8c88a44fe454cdfe79":{
      "scriptId":"u23"},
    "3aa05d43f42d4dafa2a0fea3356c5d14":{
      "scriptId":"u24"},
    "4d231d1ab28e4ed9b096127d8edfcf6e":{
      "scriptId":"u25"},
    "61c1979b0d904f4dac6ae3c10595d518":{
      "scriptId":"u26"},
    "a02ef390d50d4a30a667a6b4cc5e3abb":{
      "scriptId":"u27"},
    "f8814b097c2b4652b62eb1a2e6166b4b":{
      "scriptId":"u28"},
    "d4ee960e9b1b490e977242e0d81ccb0d":{
      "scriptId":"u29"},
    "cca71def257f4faa989543f5db7a03ea":{
      "scriptId":"u30"},
    "79c5883a8da7404eb38671a87e51a190":{
      "scriptId":"u31"},
    "e019719e342d48a0bfafd959f7bdf2cf":{
      "scriptId":"u32"},
    "92ff1b23735f46149874a431a6484efb":{
      "scriptId":"u33"},
    "daf3eed119744ce58a15c693c15c24b8":{
      "scriptId":"u34"},
    "8a3ca10b7e5e4d28abaad108b29c08be":{
      "scriptId":"u35"},
    "b93bae512b224e58ab99de6112d2227b":{
      "scriptId":"u36"},
    "8dd9f325e05d46fdb6bc0fd42f02a0ca":{
      "scriptId":"u37"},
    "beadcc9b64714f02813f2d9c31556cca":{
      "scriptId":"u38"},
    "7260079fba82457aab3d230f66a3cbc7":{
      "scriptId":"u39"},
    "284987d9505543078677a74dd43de21f":{
      "scriptId":"u40"},
    "c9f9db17dfeb4e92bb575cf5bb5d808c":{
      "scriptId":"u41"},
    "7d3f218cfff04396b52bfdc20559b54b":{
      "scriptId":"u42"},
    "6b02c51766e142288890735a1239fdfc":{
      "scriptId":"u43"},
    "48d567ea46b2409b815685e387dce321":{
      "scriptId":"u44"},
    "30a1f19d1b2e47139db6ef6d5da17711":{
      "scriptId":"u45"},
    "a621af8e8fb34d33b1a5bb146d701434":{
      "scriptId":"u46"},
    "d0322c26f10d4e09b4a9e6557e8ff8b6":{
      "scriptId":"u47"},
    "886c6fde88a84198bd4dc85ea707dd05":{
      "scriptId":"u48"},
    "09820920270949368e8d6a696a898c37":{
      "scriptId":"u49"},
    "7fbb473354ed41b7829baad843bc3d46":{
      "scriptId":"u50"},
    "30b0e76e6ad54614acd61fbc14ce7a1d":{
      "scriptId":"u51"},
    "087deb389013423da1340f21ba703cd7":{
      "scriptId":"u52"},
    "b16c92adb15347b49a4ff4762cad5972":{
      "scriptId":"u53"},
    "03a7da5de6c6489ebb47e5666ed19731":{
      "scriptId":"u54"},
    "b8cd0f2d3f5d4f52a157270234888c91":{
      "scriptId":"u55"},
    "bbc74924297e48be9965488523d21615":{
      "scriptId":"u56"},
    "0df8308aa4dc43f5a25cce3f9808c673":{
      "scriptId":"u57"}}});