$axure.loadCurrentPage({
  "url":"预约界面.html",
  "generationDate":new Date(1421557098929.87),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"isLogin"],
  "page":{
    "packageId":"b5148b4c059644b392dea308724152a9",
    "type":"Axure:Page",
    "name":"预约界面",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
      "a":{
}},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"37ee421c117843de9cbc9fda27d45822",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
            "a":{
}},
          "masterId":"c0462b19eeab412787c3050c808291eb"},
{
          "id":"928d40c706784ca2ac2630fef9136c8f",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":70},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
            "a":{
}},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 登录界面",
                      "target":{
                        "targetType":"page",
                        "url":"登录界面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"dfc2e8a6ed1c4ef88d903d552f14855a",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"09923f58c78a4b6eb3ddf693928a7bb2",
                  "label":"",
                  "parentDynamicPanel":"928d40c706784ca2ac2630fef9136c8f",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":270,
                      "height":40}},
                  "adaptiveStyles":{
                    "a":{
}},
                  "objects":[{
                      "id":"cff8f688ab004cdab5a3e835eb99abed",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"928d40c706784ca2ac2630fef9136c8f",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":270,
                          "height":40}},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"images/预约界面/u7.png"}},
{
                  "id":"48d109bfe00a4439a08957b22ea8d9aa",
                  "label":"",
                  "parentDynamicPanel":"928d40c706784ca2ac2630fef9136c8f",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":10,
                      "y":5},
                    "size":{
                      "width":30,
                      "height":30}},
                  "adaptiveStyles":{
                    "a":{
}},
                  "objects":[{
                      "id":"ece87334ac4d40c59a0f6d5ee5b2f6c5",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"928d40c706784ca2ac2630fef9136c8f",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":10,
                          "y":5},
                        "size":{
                          "width":30,
                          "height":30}},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"images/预约界面/u9.png"}},
{
                  "id":"8ad1fc80fb2b4aa7b2213854331499d3",
                  "label":"",
                  "parentDynamicPanel":"928d40c706784ca2ac2630fef9136c8f",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":50,
                      "y":12},
                    "size":{
                      "width":40,
                      "height":16}},
                  "adaptiveStyles":{
                    "a":{
                      "size":{
                        "width":40,
                        "height":16}}},
                  "objects":[{
                      "id":"897f80106ea94dca9d2ee34f7e8f0156",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"928d40c706784ca2ac2630fef9136c8f",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":50,
                          "y":12},
                        "size":{
                          "width":40,
                          "height":16}},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "normal~a":"resources/images/transparent.gif"}}]}]},
{
          "id":"e7566480dcfe41f195cfd679769d2969",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":150},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
            "a":{
}},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"0273901e31ba4a76888cadb80f852a08",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"ee13027a2f664f70849f2e1fd788866f",
                  "label":"",
                  "parentDynamicPanel":"e7566480dcfe41f195cfd679769d2969",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":270,
                      "height":40}},
                  "adaptiveStyles":{
                    "a":{
}},
                  "objects":[{
                      "id":"332123244d314ae584d7c87fa7b79617",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e7566480dcfe41f195cfd679769d2969",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":270,
                          "height":40}},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"images/预约界面/u7.png"}},
{
                  "id":"ff69d637c6604b2195c71c50f025a456",
                  "label":"",
                  "parentDynamicPanel":"e7566480dcfe41f195cfd679769d2969",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":10,
                      "y":5},
                    "size":{
                      "width":30,
                      "height":30}},
                  "adaptiveStyles":{
                    "a":{
}},
                  "objects":[{
                      "id":"d8b0219615574c2faffe3b7ebae8f39c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e7566480dcfe41f195cfd679769d2969",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":10,
                          "y":5},
                        "size":{
                          "width":30,
                          "height":30}},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"images/预约界面/u9.png"}},
{
                  "id":"f28717c94df9467bbb359caa07fed58d",
                  "label":"",
                  "parentDynamicPanel":"e7566480dcfe41f195cfd679769d2969",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":50,
                      "y":12},
                    "size":{
                      "width":79,
                      "height":16}},
                  "adaptiveStyles":{
                    "a":{
                      "size":{
                        "width":79,
                        "height":16}}},
                  "objects":[{
                      "id":"ca7bd6ad31394fe3959e0e1dc23236fe",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e7566480dcfe41f195cfd679769d2969",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":50,
                          "y":12},
                        "size":{
                          "width":79,
                          "height":16}},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "normal~a":"resources/images/transparent.gif"}}]}]},
{
          "id":"8f58a7054b2c45a888091b82c386cc20",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":191},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
            "a":{
}},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 服务地址",
                      "target":{
                        "targetType":"page",
                        "url":"服务地址.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"0864b84dfa5b444c90fb84ddf2029d50",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"3b44cf1937e44986b8497d7ed54f61fd",
                  "label":"",
                  "parentDynamicPanel":"8f58a7054b2c45a888091b82c386cc20",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":270,
                      "height":40}},
                  "adaptiveStyles":{
                    "a":{
}},
                  "objects":[{
                      "id":"0570094d0b0e4d139310e630a5ea78a8",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"8f58a7054b2c45a888091b82c386cc20",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":270,
                          "height":40}},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"images/预约界面/u7.png"}},
{
                  "id":"d19b7cd9ec6c4fb29fbcf82ad22d33a9",
                  "label":"",
                  "parentDynamicPanel":"8f58a7054b2c45a888091b82c386cc20",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":10,
                      "y":5},
                    "size":{
                      "width":30,
                      "height":30}},
                  "adaptiveStyles":{
                    "a":{
}},
                  "objects":[{
                      "id":"07abc3bfe26c4afdaaf08e1354720413",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"8f58a7054b2c45a888091b82c386cc20",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":10,
                          "y":5},
                        "size":{
                          "width":30,
                          "height":30}},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"images/预约界面/u9.png"}},
{
                  "id":"4fbeb57063d6448599cbaa3d624969f1",
                  "label":"",
                  "parentDynamicPanel":"8f58a7054b2c45a888091b82c386cc20",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":50,
                      "y":12},
                    "size":{
                      "width":79,
                      "height":16}},
                  "adaptiveStyles":{
                    "a":{
                      "size":{
                        "width":79,
                        "height":16}}},
                  "objects":[{
                      "id":"3e71dae701ed4935bc6e6d69b1541f20",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"8f58a7054b2c45a888091b82c386cc20",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":50,
                          "y":12},
                        "size":{
                          "width":79,
                          "height":16}},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "normal~a":"resources/images/transparent.gif"}}]}]},
{
          "id":"42027f3eae05456ba409bac262458b3a",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":270},
            "size":{
              "width":270,
              "height":40}},
          "adaptiveStyles":{
            "a":{
}},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 基于LBS的推荐技师",
                      "target":{
                        "targetType":"page",
                        "url":"基于lbs的推荐技师.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"5cd8a1166cc141a1b15e5d44607d010d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":120,
              "y":14},
            "size":{
              "width":81,
              "height":23}},
          "adaptiveStyles":{
            "a":{
              "location":{
                "x":120,
                "y":14},
              "size":{
                "width":81,
                "height":23}}},
          "objects":[{
              "id":"68061fa2e9204639a9fbe9d2c8623f18",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":120,
                  "y":14},
                "size":{
                  "width":81,
                  "height":23}},
              "adaptiveStyles":{
                "a":{
}}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "normal~a":"resources/images/transparent.gif"}},
{
          "id":"334d7b1948db4fb8b6c24dfd05ffd790",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":358,
              "y":270},
            "size":{
              "width":183,
              "height":16}},
          "adaptiveStyles":{
            "a":{
              "size":{
                "width":183,
                "height":16}}},
          "objects":[{
              "id":"144a2b3d2ec045e5a095769256560623",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":358,
                  "y":270},
                "size":{
                  "width":183,
                  "height":16}},
              "adaptiveStyles":{
                "a":{
}}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "normal~a":"resources/images/transparent.gif"}}]}},
  "masters":{
    "c0462b19eeab412787c3050c808291eb":{
      "packageId":"c0462b19eeab412787c3050c808291eb",
      "type":"Axure:Master",
      "name":"上返回栏",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
        "a":{
}},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"193809c55b604a239711248fd3b92b17",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "size":{
                "width":320,
                "height":480}},
            "adaptiveStyles":{
              "a":{
}},
            "objects":[{
                "id":"fb301888262643c4b28fcad2d5ca7aa9",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":320,
                    "height":480}},
                "adaptiveStyles":{
                  "a":{
}}}],
            "images":{
              "normal~":"images/主页/u1_a.png"}},
{
            "id":"3a8352b0bdb94ce9a3089c99ad30d525",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "size":{
                "width":200,
                "height":100},
              "limbo":true},
            "adaptiveStyles":{
              "a":{
                "size":{
                  "width":320,
                  "height":50},
                "limbo":false}},
            "objects":[{
                "id":"5e026ecd19c44faaaf17922e877148fb",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":200,
                    "height":100},
                  "limbo":true},
                "adaptiveStyles":{
                  "a":{
}}}],
            "images":{
              "normal~":"images/主页/u9.png",
              "normal~a":"images/主页/u9_a.png"}},
{
            "id":"9b46f5ced4cd494bb946afb473a1d17b",
            "label":"",
            "type":"button",
            "styleType":"button",
            "visible":true,
            "style":{
              "location":{
                "x":211,
                "y":13},
              "size":{
                "width":100,
                "height":25},
              "limbo":true},
            "adaptiveStyles":{
              "a":{
                "location":{
                  "x":10,
                  "y":12.5},
                "size":{
                  "width":71,
                  "height":25},
                "limbo":false}},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 返回",
                        "target":{
                          "targetType":"backUrl",
                          "includeVariables":false},
                        "linkType":"current"}]}]}},
            "tabbable":true}]}}},
  "objectPaths":{
    "37ee421c117843de9cbc9fda27d45822":{
      "scriptId":"u0",
      "193809c55b604a239711248fd3b92b17":{
        "scriptId":"u1"},
      "fb301888262643c4b28fcad2d5ca7aa9":{
        "scriptId":"u2"},
      "3a8352b0bdb94ce9a3089c99ad30d525":{
        "scriptId":"u3"},
      "5e026ecd19c44faaaf17922e877148fb":{
        "scriptId":"u4"},
      "9b46f5ced4cd494bb946afb473a1d17b":{
        "scriptId":"u5"}},
    "928d40c706784ca2ac2630fef9136c8f":{
      "scriptId":"u6"},
    "09923f58c78a4b6eb3ddf693928a7bb2":{
      "scriptId":"u7"},
    "cff8f688ab004cdab5a3e835eb99abed":{
      "scriptId":"u8"},
    "48d109bfe00a4439a08957b22ea8d9aa":{
      "scriptId":"u9"},
    "ece87334ac4d40c59a0f6d5ee5b2f6c5":{
      "scriptId":"u10"},
    "8ad1fc80fb2b4aa7b2213854331499d3":{
      "scriptId":"u11"},
    "897f80106ea94dca9d2ee34f7e8f0156":{
      "scriptId":"u12"},
    "e7566480dcfe41f195cfd679769d2969":{
      "scriptId":"u13"},
    "ee13027a2f664f70849f2e1fd788866f":{
      "scriptId":"u14"},
    "332123244d314ae584d7c87fa7b79617":{
      "scriptId":"u15"},
    "ff69d637c6604b2195c71c50f025a456":{
      "scriptId":"u16"},
    "d8b0219615574c2faffe3b7ebae8f39c":{
      "scriptId":"u17"},
    "f28717c94df9467bbb359caa07fed58d":{
      "scriptId":"u18"},
    "ca7bd6ad31394fe3959e0e1dc23236fe":{
      "scriptId":"u19"},
    "8f58a7054b2c45a888091b82c386cc20":{
      "scriptId":"u20"},
    "3b44cf1937e44986b8497d7ed54f61fd":{
      "scriptId":"u21"},
    "0570094d0b0e4d139310e630a5ea78a8":{
      "scriptId":"u22"},
    "d19b7cd9ec6c4fb29fbcf82ad22d33a9":{
      "scriptId":"u23"},
    "07abc3bfe26c4afdaaf08e1354720413":{
      "scriptId":"u24"},
    "4fbeb57063d6448599cbaa3d624969f1":{
      "scriptId":"u25"},
    "3e71dae701ed4935bc6e6d69b1541f20":{
      "scriptId":"u26"},
    "42027f3eae05456ba409bac262458b3a":{
      "scriptId":"u27"},
    "5cd8a1166cc141a1b15e5d44607d010d":{
      "scriptId":"u28"},
    "68061fa2e9204639a9fbe9d2c8623f18":{
      "scriptId":"u29"},
    "334d7b1948db4fb8b6c24dfd05ffd790":{
      "scriptId":"u30"},
    "144a2b3d2ec045e5a095769256560623":{
      "scriptId":"u31"}}});