$axure.loadCurrentPage({
  "url":"技师展示界面.html",
  "generationDate":new Date(1421169786276.51),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"isLogin"],
  "page":{
    "packageId":"6303fc8fd6e541f6acce096c66c9325b",
    "type":"Axure:Page",
    "name":"技师展示界面",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
      "a":{
}},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"dc47beda7cc0447ca02f2b456890589d",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
            "a":{
}},
          "masterId":"c0462b19eeab412787c3050c808291eb"},
{
          "id":"ea3a8245a22d466faf4afbca6418e84c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":120,
              "y":14},
            "size":{
              "width":81,
              "height":23}},
          "adaptiveStyles":{
            "a":{
              "location":{
                "x":120,
                "y":14}}},
          "objects":[{
              "id":"18a9bcffb2c94f66abd2324077b0677a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":120,
                  "y":14},
                "size":{
                  "width":81,
                  "height":23}},
              "adaptiveStyles":{
                "a":{
}}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "normal~a":"resources/images/transparent.gif"}},
{
          "id":"fd3db6c451ae4fcb9e9d634d258c6215",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1,
              "y":50},
            "size":{
              "width":319,
              "height":160}},
          "adaptiveStyles":{
            "a":{
}},
          "objects":[{
              "id":"216a963b53884138b66d6f462bdd135f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1,
                  "y":50},
                "size":{
                  "width":319,
                  "height":160}},
              "adaptiveStyles":{
                "a":{
}}}],
          "images":{
            "normal~":"images/技师展示界面/u6.png"}},
{
          "id":"bed6f4871b6344db9eb0b7860e59864b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":60},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
            "a":{
}},
          "objects":[{
              "id":"bdd6d2501bba45faad4ca1fbd0e84573",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":60},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
                "a":{
}}}],
          "images":{
            "normal~":"images/技师展示界面/u8.png"}},
{
          "id":"372e3c098b7f43949429a981a517e413",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":60},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
            "a":{
              "size":{
                "width":53,
                "height":16}}},
          "objects":[{
              "id":"3975680cf81b4900a203eb9f9dae06cf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":60},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
                "a":{
}}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "normal~a":"resources/images/transparent.gif"}},
{
          "id":"44194e86f2c04b2faa33a90646c1bf3e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":86},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
            "a":{
              "size":{
                "width":53,
                "height":16}}},
          "objects":[{
              "id":"42633669293a44ea96b68394bdd970f8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":86},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
                "a":{
}}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "normal~a":"resources/images/transparent.gif"}},
{
          "id":"1b9f31f0c81a4af3aeca2c58ee972686",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":112},
            "size":{
              "width":80,
              "height":16}},
          "adaptiveStyles":{
            "a":{
              "size":{
                "width":80,
                "height":16}}},
          "objects":[{
              "id":"7596d1b0e4924881b51f924ba687edf9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":112},
                "size":{
                  "width":80,
                  "height":16}},
              "adaptiveStyles":{
                "a":{
}}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "normal~a":"resources/images/transparent.gif"}},
{
          "id":"89eee683ae134c97b6e439f097a9a1f7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":6,
              "y":138},
            "size":{
              "width":90,
              "height":32}},
          "adaptiveStyles":{
            "a":{
}},
          "objects":[{
              "id":"16856e0cc979456ab6a167b9b8130d6b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":6,
                  "y":138},
                "size":{
                  "width":90,
                  "height":32}},
              "adaptiveStyles":{
                "a":{
}}}],
          "images":{
            "normal~":"images/技师展示界面/u16.png"}},
{
          "id":"79d71d3655f84e2eb9916976b19c50a1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":122,
              "y":138},
            "size":{
              "width":90,
              "height":32}},
          "adaptiveStyles":{
            "a":{
}},
          "objects":[{
              "id":"232e13bc4ae847648ca6797d99172fa6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":122,
                  "y":138},
                "size":{
                  "width":90,
                  "height":32}},
              "adaptiveStyles":{
                "a":{
}}}],
          "images":{
            "normal~":"images/技师展示界面/u16.png"}},
{
          "id":"24271a5457044ea59a1ac6706f3d19d1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":226,
              "y":138},
            "size":{
              "width":90,
              "height":32}},
          "adaptiveStyles":{
            "a":{
}},
          "objects":[{
              "id":"c7df154a162d4f8c88a44fe454cdfe79",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":226,
                  "y":138},
                "size":{
                  "width":90,
                  "height":32}},
              "adaptiveStyles":{
                "a":{
}}}],
          "images":{
            "normal~":"images/技师展示界面/u16.png"}},
{
          "id":"3aa05d43f42d4dafa2a0fea3356c5d14",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":6,
              "y":174},
            "size":{
              "width":310,
              "height":30}},
          "adaptiveStyles":{
            "a":{
}},
          "objects":[{
              "id":"4d231d1ab28e4ed9b096127d8edfcf6e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":6,
                  "y":174},
                "size":{
                  "width":310,
                  "height":30}},
              "adaptiveStyles":{
                "a":{
}}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 客户平价界面",
                      "target":{
                        "targetType":"page",
                        "url":"客户平价界面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/技师展示界面/u22.png"}},
{
          "id":"61c1979b0d904f4dac6ae3c10595d518",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":210,
              "y":81.5},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
            "a":{
}},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 技师个人信息",
                      "target":{
                        "targetType":"page",
                        "url":"技师个人信息.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"145c2ef29b5b4f348190b6b0cdb248e1",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":380},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
            "a":{
}},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"e8d6d24a45b441568a3b23bbb2b139a6",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"4da4e2f6713d4885ac3ac558f563a393",
                  "label":"",
                  "parentDynamicPanel":"145c2ef29b5b4f348190b6b0cdb248e1",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":320,
                      "height":70}},
                  "adaptiveStyles":{
                    "a":{
}},
                  "objects":[{
                      "id":"916cc3aa9ede4ad6a748c35a4f346f77",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"145c2ef29b5b4f348190b6b0cdb248e1",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":320,
                          "height":70}},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"images/技师展示界面/u26.png"}},
{
                  "id":"0b24a83e244f49e48b3f90ad25255d55",
                  "label":"",
                  "parentDynamicPanel":"145c2ef29b5b4f348190b6b0cdb248e1",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":134,
                      "y":10},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
                    "a":{
                      "size":{
                        "width":53,
                        "height":16}}},
                  "objects":[{
                      "id":"afa23e18ec1b418bb9ac17eb2e0e3669",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"145c2ef29b5b4f348190b6b0cdb248e1",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":134,
                          "y":10},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "normal~a":"resources/images/transparent.gif"}},
{
                  "id":"3cb9a72af2174fdc834e1442045658a3",
                  "label":"",
                  "parentDynamicPanel":"145c2ef29b5b4f348190b6b0cdb248e1",
                  "type":"radioButton",
                  "styleType":"radioButton",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":10,
                      "y":44},
                    "size":{
                      "width":100,
                      "height":16}},
                  "adaptiveStyles":{
                    "a":{
}},
                  "objects":[{
                      "id":"bb2502d8c709485ba29bf18c239a843f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"145c2ef29b5b4f348190b6b0cdb248e1",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":10,
                          "y":44},
                        "size":{
                          "width":100,
                          "height":16}},
                      "adaptiveStyles":{
                        "a":{
}}}]},
{
                  "id":"e5a48b5e463148d7bd9c333d7723f106",
                  "label":"",
                  "parentDynamicPanel":"145c2ef29b5b4f348190b6b0cdb248e1",
                  "type":"radioButton",
                  "styleType":"radioButton",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":116,
                      "y":44},
                    "size":{
                      "width":100,
                      "height":16}},
                  "adaptiveStyles":{
                    "a":{
}},
                  "objects":[{
                      "id":"fb05bcd956dc440e95a49508d2264a6c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"145c2ef29b5b4f348190b6b0cdb248e1",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":116,
                          "y":44},
                        "size":{
                          "width":100,
                          "height":16}},
                      "adaptiveStyles":{
                        "a":{
}}}]},
{
                  "id":"02f85c48871d4c19aec406ae144ae6d8",
                  "label":"",
                  "parentDynamicPanel":"145c2ef29b5b4f348190b6b0cdb248e1",
                  "type":"radioButton",
                  "styleType":"radioButton",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":216,
                      "y":44},
                    "size":{
                      "width":124,
                      "height":16}},
                  "adaptiveStyles":{
                    "a":{
}},
                  "objects":[{
                      "id":"6311fd91e4aa4d22a0545bbe76457068",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"145c2ef29b5b4f348190b6b0cdb248e1",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":216,
                          "y":44},
                        "size":{
                          "width":124,
                          "height":16}},
                      "adaptiveStyles":{
                        "a":{
}}}]}]}]},
{
          "id":"461308d1b68d4c3bb811136601e0ef7b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":368,
              "y":304},
            "size":{
              "width":287,
              "height":32}},
          "adaptiveStyles":{
            "a":{
              "size":{
                "width":287,
                "height":32}}},
          "objects":[{
              "id":"0848663845f343f3ae185c0001f5d026",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":368,
                  "y":304},
                "size":{
                  "width":287,
                  "height":32}},
              "adaptiveStyles":{
                "a":{
}}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "normal~a":"resources/images/transparent.gif"}},
{
          "id":"a02ef390d50d4a30a667a6b4cc5e3abb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":6,
              "y":220},
            "size":{
              "width":310,
              "height":150}},
          "adaptiveStyles":{
            "a":{
}},
          "objects":[{
              "id":"f8814b097c2b4652b62eb1a2e6166b4b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":6,
                  "y":220},
                "size":{
                  "width":310,
                  "height":150}},
              "adaptiveStyles":{
                "a":{
}}}],
          "images":{
            "normal~":"images/技师展示界面/u38.png"}},
{
          "id":"d4ee960e9b1b490e977242e0d81ccb0d",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":450},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
            "a":{
}},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"82dfd57440004ee0b0b86e6760984ca3",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"cca71def257f4faa989543f5db7a03ea",
                  "label":"",
                  "parentDynamicPanel":"d4ee960e9b1b490e977242e0d81ccb0d",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":320,
                      "height":90}},
                  "adaptiveStyles":{
                    "a":{
}},
                  "objects":[{
                      "id":"79c5883a8da7404eb38671a87e51a190",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"d4ee960e9b1b490e977242e0d81ccb0d",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":320,
                          "height":90}},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"images/技师浏览/u12_a.png"}},
{
                  "id":"e019719e342d48a0bfafd959f7bdf2cf",
                  "label":"",
                  "parentDynamicPanel":"d4ee960e9b1b490e977242e0d81ccb0d",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":6,
                      "y":10},
                    "size":{
                      "width":74,
                      "height":70}},
                  "adaptiveStyles":{
                    "a":{
}},
                  "objects":[{
                      "id":"92ff1b23735f46149874a431a6484efb",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"d4ee960e9b1b490e977242e0d81ccb0d",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":6,
                          "y":10},
                        "size":{
                          "width":74,
                          "height":70}},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"images/技师展示界面/u43.png"}},
{
                  "id":"daf3eed119744ce58a15c693c15c24b8",
                  "label":"",
                  "parentDynamicPanel":"d4ee960e9b1b490e977242e0d81ccb0d",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":90,
                      "y":14},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
                    "a":{
                      "size":{
                        "width":53,
                        "height":16}}},
                  "objects":[{
                      "id":"8a3ca10b7e5e4d28abaad108b29c08be",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"d4ee960e9b1b490e977242e0d81ccb0d",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":90,
                          "y":14},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "normal~a":"resources/images/transparent.gif"}},
{
                  "id":"b93bae512b224e58ab99de6112d2227b",
                  "label":"",
                  "parentDynamicPanel":"d4ee960e9b1b490e977242e0d81ccb0d",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":90,
                      "y":40},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
                    "a":{
                      "size":{
                        "width":53,
                        "height":16}}},
                  "objects":[{
                      "id":"8dd9f325e05d46fdb6bc0fd42f02a0ca",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"d4ee960e9b1b490e977242e0d81ccb0d",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":90,
                          "y":40},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "normal~a":"resources/images/transparent.gif"}},
{
                  "id":"beadcc9b64714f02813f2d9c31556cca",
                  "label":"",
                  "parentDynamicPanel":"d4ee960e9b1b490e977242e0d81ccb0d",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":90,
                      "y":66},
                    "size":{
                      "width":144,
                      "height":16}},
                  "adaptiveStyles":{
                    "a":{
                      "size":{
                        "width":144,
                        "height":16}}},
                  "objects":[{
                      "id":"7260079fba82457aab3d230f66a3cbc7",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"d4ee960e9b1b490e977242e0d81ccb0d",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":90,
                          "y":66},
                        "size":{
                          "width":144,
                          "height":16}},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "normal~a":"resources/images/transparent.gif"}},
{
                  "id":"284987d9505543078677a74dd43de21f",
                  "label":"",
                  "parentDynamicPanel":"d4ee960e9b1b490e977242e0d81ccb0d",
                  "type":"button",
                  "styleType":"button",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":216,
                      "y":30},
                    "size":{
                      "width":84,
                      "height":26}},
                  "adaptiveStyles":{
                    "a":{
}}}]}]},
{
          "id":"c9f9db17dfeb4e92bb575cf5bb5d808c",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":560},
            "size":{
              "width":320,
              "height":40}},
          "adaptiveStyles":{
            "a":{
}}}]}},
  "masters":{
    "c0462b19eeab412787c3050c808291eb":{
      "packageId":"c0462b19eeab412787c3050c808291eb",
      "type":"Axure:Master",
      "name":"上返回栏",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
        "a":{
}},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"3a8352b0bdb94ce9a3089c99ad30d525",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "size":{
                "width":200,
                "height":100},
              "limbo":true},
            "adaptiveStyles":{
              "a":{
                "size":{
                  "width":320,
                  "height":50},
                "limbo":false}},
            "objects":[{
                "id":"5e026ecd19c44faaaf17922e877148fb",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":200,
                    "height":100},
                  "limbo":true},
                "adaptiveStyles":{
                  "a":{
}}}],
            "images":{
              "normal~":"images/主页/u9.png",
              "normal~a":"images/主页/u9_a.png"}},
{
            "id":"9b46f5ced4cd494bb946afb473a1d17b",
            "label":"",
            "type":"button",
            "styleType":"button",
            "visible":true,
            "style":{
              "location":{
                "x":211,
                "y":13},
              "size":{
                "width":100,
                "height":25},
              "limbo":true},
            "adaptiveStyles":{
              "a":{
                "location":{
                  "x":10,
                  "y":12.5},
                "size":{
                  "width":71,
                  "height":25},
                "limbo":false}},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 返回",
                        "target":{
                          "targetType":"backUrl",
                          "includeVariables":false},
                        "linkType":"current"}]}]}},
            "tabbable":true}]}}},
  "objectPaths":{
    "dc47beda7cc0447ca02f2b456890589d":{
      "scriptId":"u0",
      "3a8352b0bdb94ce9a3089c99ad30d525":{
        "scriptId":"u1"},
      "5e026ecd19c44faaaf17922e877148fb":{
        "scriptId":"u2"},
      "9b46f5ced4cd494bb946afb473a1d17b":{
        "scriptId":"u3"}},
    "ea3a8245a22d466faf4afbca6418e84c":{
      "scriptId":"u4"},
    "18a9bcffb2c94f66abd2324077b0677a":{
      "scriptId":"u5"},
    "fd3db6c451ae4fcb9e9d634d258c6215":{
      "scriptId":"u6"},
    "216a963b53884138b66d6f462bdd135f":{
      "scriptId":"u7"},
    "bed6f4871b6344db9eb0b7860e59864b":{
      "scriptId":"u8"},
    "bdd6d2501bba45faad4ca1fbd0e84573":{
      "scriptId":"u9"},
    "372e3c098b7f43949429a981a517e413":{
      "scriptId":"u10"},
    "3975680cf81b4900a203eb9f9dae06cf":{
      "scriptId":"u11"},
    "44194e86f2c04b2faa33a90646c1bf3e":{
      "scriptId":"u12"},
    "42633669293a44ea96b68394bdd970f8":{
      "scriptId":"u13"},
    "1b9f31f0c81a4af3aeca2c58ee972686":{
      "scriptId":"u14"},
    "7596d1b0e4924881b51f924ba687edf9":{
      "scriptId":"u15"},
    "89eee683ae134c97b6e439f097a9a1f7":{
      "scriptId":"u16"},
    "16856e0cc979456ab6a167b9b8130d6b":{
      "scriptId":"u17"},
    "79d71d3655f84e2eb9916976b19c50a1":{
      "scriptId":"u18"},
    "232e13bc4ae847648ca6797d99172fa6":{
      "scriptId":"u19"},
    "24271a5457044ea59a1ac6706f3d19d1":{
      "scriptId":"u20"},
    "c7df154a162d4f8c88a44fe454cdfe79":{
      "scriptId":"u21"},
    "3aa05d43f42d4dafa2a0fea3356c5d14":{
      "scriptId":"u22"},
    "4d231d1ab28e4ed9b096127d8edfcf6e":{
      "scriptId":"u23"},
    "61c1979b0d904f4dac6ae3c10595d518":{
      "scriptId":"u24"},
    "145c2ef29b5b4f348190b6b0cdb248e1":{
      "scriptId":"u25"},
    "4da4e2f6713d4885ac3ac558f563a393":{
      "scriptId":"u26"},
    "916cc3aa9ede4ad6a748c35a4f346f77":{
      "scriptId":"u27"},
    "0b24a83e244f49e48b3f90ad25255d55":{
      "scriptId":"u28"},
    "afa23e18ec1b418bb9ac17eb2e0e3669":{
      "scriptId":"u29"},
    "3cb9a72af2174fdc834e1442045658a3":{
      "scriptId":"u30"},
    "bb2502d8c709485ba29bf18c239a843f":{
      "scriptId":"u31"},
    "e5a48b5e463148d7bd9c333d7723f106":{
      "scriptId":"u32"},
    "fb05bcd956dc440e95a49508d2264a6c":{
      "scriptId":"u33"},
    "02f85c48871d4c19aec406ae144ae6d8":{
      "scriptId":"u34"},
    "6311fd91e4aa4d22a0545bbe76457068":{
      "scriptId":"u35"},
    "461308d1b68d4c3bb811136601e0ef7b":{
      "scriptId":"u36"},
    "0848663845f343f3ae185c0001f5d026":{
      "scriptId":"u37"},
    "a02ef390d50d4a30a667a6b4cc5e3abb":{
      "scriptId":"u38"},
    "f8814b097c2b4652b62eb1a2e6166b4b":{
      "scriptId":"u39"},
    "d4ee960e9b1b490e977242e0d81ccb0d":{
      "scriptId":"u40"},
    "cca71def257f4faa989543f5db7a03ea":{
      "scriptId":"u41"},
    "79c5883a8da7404eb38671a87e51a190":{
      "scriptId":"u42"},
    "e019719e342d48a0bfafd959f7bdf2cf":{
      "scriptId":"u43"},
    "92ff1b23735f46149874a431a6484efb":{
      "scriptId":"u44"},
    "daf3eed119744ce58a15c693c15c24b8":{
      "scriptId":"u45"},
    "8a3ca10b7e5e4d28abaad108b29c08be":{
      "scriptId":"u46"},
    "b93bae512b224e58ab99de6112d2227b":{
      "scriptId":"u47"},
    "8dd9f325e05d46fdb6bc0fd42f02a0ca":{
      "scriptId":"u48"},
    "beadcc9b64714f02813f2d9c31556cca":{
      "scriptId":"u49"},
    "7260079fba82457aab3d230f66a3cbc7":{
      "scriptId":"u50"},
    "284987d9505543078677a74dd43de21f":{
      "scriptId":"u51"},
    "c9f9db17dfeb4e92bb575cf5bb5d808c":{
      "scriptId":"u52"}}});