$axure.loadCurrentPage({
  "url":"项目详情.html",
  "generationDate":new Date(1421169787340.53),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"isLogin"],
  "page":{
    "packageId":"a0c696457af1489c8bd07ec36b6e8505",
    "type":"Axure:Page",
    "name":"项目详情",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
      "a":{
}},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"7376719b1ff249eb938acb82d0957a35",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
            "a":{
}},
          "masterId":"c0462b19eeab412787c3050c808291eb"},
{
          "id":"42d07ef0dd914ae3b3142fe9e5aca859",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":120,
              "y":14},
            "size":{
              "width":81,
              "height":23}},
          "adaptiveStyles":{
            "a":{
              "location":{
                "x":120,
                "y":14}}},
          "objects":[{
              "id":"d0a69f6c27dc43e7b09ccdb8cebdf818",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":120,
                  "y":14},
                "size":{
                  "width":81,
                  "height":23}},
              "adaptiveStyles":{
                "a":{
}}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "normal~a":"resources/images/transparent.gif"}},
{
          "id":"6186f7f53e3b4bbdbee6cf97e3082bbc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":60},
            "size":{
              "width":320,
              "height":80}},
          "adaptiveStyles":{
            "a":{
}},
          "objects":[{
              "id":"4044d784a7e342e58c88fd7265f2ed19",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":60},
                "size":{
                  "width":320,
                  "height":80}},
              "adaptiveStyles":{
                "a":{
}}}],
          "images":{
            "normal~":"images/项目详情/u6.png"}},
{
          "id":"a8ed8e4a3e0e49638906a83a76ae74e7",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":240,
              "y":13},
            "size":{
              "width":60,
              "height":24}},
          "adaptiveStyles":{
            "a":{
}}},
{
          "id":"c90448a145cb4b54afbf89236b99c56d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":150},
            "size":{
              "width":320,
              "height":160}},
          "adaptiveStyles":{
            "a":{
}},
          "objects":[{
              "id":"7b0246fa2c5841b081259bc100d9c6e4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":150},
                "size":{
                  "width":320,
                  "height":160}},
              "adaptiveStyles":{
                "a":{
}}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 单个流程介绍",
                      "target":{
                        "targetType":"page",
                        "url":"单个流程介绍.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/项目详情/u9.png"}},
{
          "id":"e1b67749cc6d4816af6a5cb42da31709",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":320},
            "size":{
              "width":320,
              "height":100}},
          "adaptiveStyles":{
            "a":{
}},
          "objects":[{
              "id":"8bb471adecc149edade9b31bdb879f91",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":320},
                "size":{
                  "width":320,
                  "height":100}},
              "adaptiveStyles":{
                "a":{
}}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 单个产品介绍",
                      "target":{
                        "targetType":"page",
                        "url":"单个产品介绍.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/技师个人信息/u12.png"}},
{
          "id":"150956e3671e4cc089454dd7bd20207d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":358,
              "y":274},
            "size":{
              "width":210,
              "height":16}},
          "adaptiveStyles":{
            "a":{
              "size":{
                "width":210,
                "height":16}}},
          "objects":[{
              "id":"4a74aa33acba4a0ea06941f0dbd0e1ad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":358,
                  "y":274},
                "size":{
                  "width":210,
                  "height":16}},
              "adaptiveStyles":{
                "a":{
}}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "normal~a":"resources/images/transparent.gif"}},
{
          "id":"728e1ac719eb4260b764f0970754be3f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":8,
              "y":430},
            "size":{
              "width":166,
              "height":16}},
          "adaptiveStyles":{
            "a":{
              "size":{
                "width":166,
                "height":16}}},
          "objects":[{
              "id":"01fab8ad35424a3682a12a58ccef19d9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":8,
                  "y":430},
                "size":{
                  "width":166,
                  "height":16}},
              "adaptiveStyles":{
                "a":{
}}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "normal~a":"resources/images/transparent.gif"}},
{
          "id":"09915af40d30456898d26ec79763319b",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":465},
            "size":{
              "width":320,
              "height":35}},
          "adaptiveStyles":{
            "a":{
}},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 技师展示界面",
                      "target":{
                        "targetType":"page",
                        "url":"技师展示界面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
    "c0462b19eeab412787c3050c808291eb":{
      "packageId":"c0462b19eeab412787c3050c808291eb",
      "type":"Axure:Master",
      "name":"上返回栏",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
        "a":{
}},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"3a8352b0bdb94ce9a3089c99ad30d525",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "size":{
                "width":200,
                "height":100},
              "limbo":true},
            "adaptiveStyles":{
              "a":{
                "size":{
                  "width":320,
                  "height":50},
                "limbo":false}},
            "objects":[{
                "id":"5e026ecd19c44faaaf17922e877148fb",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":200,
                    "height":100},
                  "limbo":true},
                "adaptiveStyles":{
                  "a":{
}}}],
            "images":{
              "normal~":"images/主页/u9.png",
              "normal~a":"images/主页/u9_a.png"}},
{
            "id":"9b46f5ced4cd494bb946afb473a1d17b",
            "label":"",
            "type":"button",
            "styleType":"button",
            "visible":true,
            "style":{
              "location":{
                "x":211,
                "y":13},
              "size":{
                "width":100,
                "height":25},
              "limbo":true},
            "adaptiveStyles":{
              "a":{
                "location":{
                  "x":10,
                  "y":12.5},
                "size":{
                  "width":71,
                  "height":25},
                "limbo":false}},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 返回",
                        "target":{
                          "targetType":"backUrl",
                          "includeVariables":false},
                        "linkType":"current"}]}]}},
            "tabbable":true}]}}},
  "objectPaths":{
    "7376719b1ff249eb938acb82d0957a35":{
      "scriptId":"u0",
      "3a8352b0bdb94ce9a3089c99ad30d525":{
        "scriptId":"u1"},
      "5e026ecd19c44faaaf17922e877148fb":{
        "scriptId":"u2"},
      "9b46f5ced4cd494bb946afb473a1d17b":{
        "scriptId":"u3"}},
    "42d07ef0dd914ae3b3142fe9e5aca859":{
      "scriptId":"u4"},
    "d0a69f6c27dc43e7b09ccdb8cebdf818":{
      "scriptId":"u5"},
    "6186f7f53e3b4bbdbee6cf97e3082bbc":{
      "scriptId":"u6"},
    "4044d784a7e342e58c88fd7265f2ed19":{
      "scriptId":"u7"},
    "a8ed8e4a3e0e49638906a83a76ae74e7":{
      "scriptId":"u8"},
    "c90448a145cb4b54afbf89236b99c56d":{
      "scriptId":"u9"},
    "7b0246fa2c5841b081259bc100d9c6e4":{
      "scriptId":"u10"},
    "e1b67749cc6d4816af6a5cb42da31709":{
      "scriptId":"u11"},
    "8bb471adecc149edade9b31bdb879f91":{
      "scriptId":"u12"},
    "150956e3671e4cc089454dd7bd20207d":{
      "scriptId":"u13"},
    "4a74aa33acba4a0ea06941f0dbd0e1ad":{
      "scriptId":"u14"},
    "728e1ac719eb4260b764f0970754be3f":{
      "scriptId":"u15"},
    "01fab8ad35424a3682a12a58ccef19d9":{
      "scriptId":"u16"},
    "09915af40d30456898d26ec79763319b":{
      "scriptId":"u17"}}});