$axure.loadCurrentPage({
  "url":"生活.html",
  "generationDate":new Date(1421169782440.14),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"isLogin"],
  "page":{
    "packageId":"cd80bb75c1924368aedd6a394b00d5d3",
    "type":"Axure:Page",
    "name":"生活",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
      "a":{
}},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"def0b3b5610449efaf144ae01050cd3a",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "limbo":true},
          "adaptiveStyles":{
            "a":{
              "limbo":false}},
          "masterId":"e423deecdca540d69784293e6582ba81"},
{
          "id":"f3b8a9bb528145778c48e3f665c264db",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "limbo":true},
          "adaptiveStyles":{
            "a":{
              "limbo":false}},
          "masterId":"95d57cbcfde44948b7548a4f84555e79"},
{
          "id":"bbc58e5423904da8a40e5d69d258a583",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":144,
              "y":17},
            "size":{
              "width":27,
              "height":16},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
              "fontSize":"20px",
              "location":{
                "x":140,
                "y":14},
              "size":{
                "width":41,
                "height":23},
              "limbo":false}},
          "objects":[{
              "id":"a3e9736fbd0c405f9134d9a9f7ba1019",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":144,
                  "y":17},
                "size":{
                  "width":27,
                  "height":16},
                "limbo":true},
              "adaptiveStyles":{
                "a":{
}}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "normal~a":"resources/images/transparent.gif"}},
{
          "id":"092897d4ab964879983c20cf6c423ac8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":60},
            "size":{
              "width":320,
              "height":280}},
          "adaptiveStyles":{
            "a":{
}},
          "objects":[{
              "id":"ebaade050bcb4b20a8070f162e0bf2b4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":60},
                "size":{
                  "width":320,
                  "height":280}},
              "adaptiveStyles":{
                "a":{
}}}],
          "images":{
            "normal~":"images/生活/u15.png"}},
{
          "id":"63a1ac8c35d8454a9166e37025b7b569",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":70},
            "size":{
              "width":300,
              "height":120}},
          "adaptiveStyles":{
            "a":{
}},
          "objects":[{
              "id":"f09dbc70685e4621a495b635fb831161",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":70},
                "size":{
                  "width":300,
                  "height":120}},
              "adaptiveStyles":{
                "a":{
}}}],
          "images":{
            "normal~":"images/生活/u17.png"}},
{
          "id":"307f613c22b64e348f436e4fa2ce4360",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":210},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
            "a":{
              "size":{
                "width":27,
                "height":16}}},
          "objects":[{
              "id":"02881728eaf3463d8e8f5eb15f379082",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":210},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
                "a":{
}}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "normal~a":"resources/images/transparent.gif"}},
{
          "id":"3ce2d8c9bc3944db9c46fcee018a874f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":236},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
            "a":{
              "size":{
                "width":27,
                "height":16}}},
          "objects":[{
              "id":"b29d4c6c30f14979a5f447d9b6f2bcb3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":236},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
                "a":{
}}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "normal~a":"resources/images/transparent.gif"}},
{
          "id":"b1fbd84d9da44bc9900702fe12f8b288",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":270},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
            "a":{
              "size":{
                "width":53,
                "height":16}}},
          "objects":[{
              "id":"04facfdf6ed345d29f15ec30c8591994",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":270},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
                "a":{
}}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "normal~a":"resources/images/transparent.gif"}},
{
          "id":"9cbc4ec9b11d459186af7af74f5de631",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":295},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
            "a":{
}}}]}},
  "masters":{
    "e423deecdca540d69784293e6582ba81":{
      "packageId":"e423deecdca540d69784293e6582ba81",
      "type":"Axure:Master",
      "name":"下导航栏",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
        "a":{
}},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"46b38d34c95741f384d5e4d38e3120ee",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":0,
                "y":420},
              "size":{
                "width":320,
                "height":60}},
            "adaptiveStyles":{
              "a":{
                "location":{
                  "x":0,
                  "y":0},
                "size":{
                  "width":320,
                  "height":480}}},
            "objects":[{
                "id":"eee4e22156fe41d98e86bfcfbba3e560",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":0,
                    "y":420},
                  "size":{
                    "width":320,
                    "height":60}},
                "adaptiveStyles":{
                  "a":{
}}}],
            "images":{
              "normal~":"images/主页/u1.png",
              "normal~a":"images/主页/u1_a.png"}},
{
            "id":"a219148e8a9a42acb89b27adba3bd693",
            "label":"",
            "type":"button",
            "styleType":"button",
            "visible":true,
            "style":{
              "location":{
                "x":0,
                "y":420},
              "size":{
                "width":100,
                "height":25},
              "limbo":true},
            "adaptiveStyles":{
              "a":{
                "size":{
                  "width":64,
                  "height":60},
                "limbo":false}},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 主页",
                        "target":{
                          "targetType":"page",
                          "url":"主页.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true},
{
            "id":"6d76ed98f8af41ef971bb4aeeadd04f1",
            "label":"",
            "type":"button",
            "styleType":"button",
            "visible":true,
            "style":{
              "location":{
                "x":10,
                "y":430},
              "size":{
                "width":100,
                "height":25},
              "limbo":true},
            "adaptiveStyles":{
              "a":{
                "location":{
                  "x":64,
                  "y":420},
                "size":{
                  "width":64,
                  "height":60},
                "limbo":false}},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 订单",
                        "target":{
                          "targetType":"page",
                          "url":"订单.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true},
{
            "id":"5a6a8b09d0fa44cb996ec710d732c51a",
            "label":"",
            "type":"button",
            "styleType":"button",
            "visible":true,
            "style":{
              "location":{
                "x":20,
                "y":440},
              "size":{
                "width":100,
                "height":25},
              "limbo":true},
            "adaptiveStyles":{
              "a":{
                "location":{
                  "x":128,
                  "y":420},
                "size":{
                  "width":64,
                  "height":60},
                "limbo":false}},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 我的",
                        "target":{
                          "targetType":"page",
                          "url":"我的.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true},
{
            "id":"c346be56b3b148c394d01867f96020ed",
            "label":"",
            "type":"button",
            "styleType":"button",
            "visible":true,
            "style":{
              "location":{
                "x":30,
                "y":450},
              "size":{
                "width":100,
                "height":25},
              "limbo":true},
            "adaptiveStyles":{
              "a":{
                "location":{
                  "x":192,
                  "y":420},
                "size":{
                  "width":64,
                  "height":60},
                "limbo":false}},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 生活",
                        "target":{
                          "targetType":"page",
                          "url":"生活.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true},
{
            "id":"bee383944d00498cb4790c08da5a6c34",
            "label":"",
            "type":"button",
            "styleType":"button",
            "visible":true,
            "style":{
              "location":{
                "x":40,
                "y":460},
              "size":{
                "width":100,
                "height":25},
              "limbo":true},
            "adaptiveStyles":{
              "a":{
                "location":{
                  "x":256,
                  "y":420},
                "size":{
                  "width":64,
                  "height":60},
                "limbo":false}},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 更多",
                        "target":{
                          "targetType":"page",
                          "url":"更多.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true}]}},
    "95d57cbcfde44948b7548a4f84555e79":{
      "packageId":"95d57cbcfde44948b7548a4f84555e79",
      "type":"Axure:Master",
      "name":"上导航栏",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
        "a":{
}},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"3a8352b0bdb94ce9a3089c99ad30d525",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "size":{
                "width":200,
                "height":100},
              "limbo":true},
            "adaptiveStyles":{
              "a":{
                "size":{
                  "width":320,
                  "height":50},
                "limbo":false}},
            "objects":[{
                "id":"5e026ecd19c44faaaf17922e877148fb",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":200,
                    "height":100},
                  "limbo":true},
                "adaptiveStyles":{
                  "a":{
}}}],
            "images":{
              "normal~":"images/主页/u9.png",
              "normal~a":"images/主页/u9_a.png"}},
{
            "id":"daf03b54e1b54a3e931b529609a504e5",
            "label":"",
            "type":"button",
            "styleType":"button",
            "visible":true,
            "style":{
              "location":{
                "x":10,
                "y":12.5},
              "size":{
                "width":100,
                "height":25},
              "limbo":true},
            "adaptiveStyles":{
              "a":{
                "location":{
                  "x":10,
                  "y":14},
                "size":{
                  "width":70,
                  "height":23},
                "limbo":false}},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 选择城市",
                        "target":{
                          "targetType":"page",
                          "url":"选择城市.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true},
{
            "id":"9b46f5ced4cd494bb946afb473a1d17b",
            "label":"",
            "type":"button",
            "styleType":"button",
            "visible":true,
            "style":{
              "location":{
                "x":211,
                "y":13},
              "size":{
                "width":100,
                "height":25},
              "limbo":true},
            "adaptiveStyles":{
              "a":{
                "location":{
                  "x":240,
                  "y":13},
                "size":{
                  "width":71,
                  "height":25},
                "limbo":false}}}]}}},
  "objectPaths":{
    "def0b3b5610449efaf144ae01050cd3a":{
      "scriptId":"u0",
      "46b38d34c95741f384d5e4d38e3120ee":{
        "scriptId":"u1"},
      "eee4e22156fe41d98e86bfcfbba3e560":{
        "scriptId":"u2"},
      "a219148e8a9a42acb89b27adba3bd693":{
        "scriptId":"u3"},
      "6d76ed98f8af41ef971bb4aeeadd04f1":{
        "scriptId":"u4"},
      "5a6a8b09d0fa44cb996ec710d732c51a":{
        "scriptId":"u5"},
      "c346be56b3b148c394d01867f96020ed":{
        "scriptId":"u6"},
      "bee383944d00498cb4790c08da5a6c34":{
        "scriptId":"u7"}},
    "f3b8a9bb528145778c48e3f665c264db":{
      "scriptId":"u8",
      "3a8352b0bdb94ce9a3089c99ad30d525":{
        "scriptId":"u9"},
      "5e026ecd19c44faaaf17922e877148fb":{
        "scriptId":"u10"},
      "daf03b54e1b54a3e931b529609a504e5":{
        "scriptId":"u11"},
      "9b46f5ced4cd494bb946afb473a1d17b":{
        "scriptId":"u12"}},
    "bbc58e5423904da8a40e5d69d258a583":{
      "scriptId":"u13"},
    "a3e9736fbd0c405f9134d9a9f7ba1019":{
      "scriptId":"u14"},
    "092897d4ab964879983c20cf6c423ac8":{
      "scriptId":"u15"},
    "ebaade050bcb4b20a8070f162e0bf2b4":{
      "scriptId":"u16"},
    "63a1ac8c35d8454a9166e37025b7b569":{
      "scriptId":"u17"},
    "f09dbc70685e4621a495b635fb831161":{
      "scriptId":"u18"},
    "307f613c22b64e348f436e4fa2ce4360":{
      "scriptId":"u19"},
    "02881728eaf3463d8e8f5eb15f379082":{
      "scriptId":"u20"},
    "3ce2d8c9bc3944db9c46fcee018a874f":{
      "scriptId":"u21"},
    "b29d4c6c30f14979a5f447d9b6f2bcb3":{
      "scriptId":"u22"},
    "b1fbd84d9da44bc9900702fe12f8b288":{
      "scriptId":"u23"},
    "04facfdf6ed345d29f15ec30c8591994":{
      "scriptId":"u24"},
    "9cbc4ec9b11d459186af7af74f5de631":{
      "scriptId":"u25"}}});