$axure.loadCurrentPage({
  "url":"浏览器.html",
  "generationDate":new Date(1421169789031.7),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"isLogin"],
  "page":{
    "packageId":"7ed00d200b6f4ee386b34d53df5dc8bd",
    "type":"Axure:Page",
    "name":"浏览器",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
      "a":{
}},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"1bc6230dcbc44d6285487c09d159ab56",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":440}},
          "adaptiveStyles":{
            "a":{
}},
          "masterId":"52ee8f3ceac7427591e65387d4ad55e3"},
{
          "id":"dec161a9835e459b9703d5cca4b12302",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":10},
            "size":{
              "width":300,
              "height":420}},
          "adaptiveStyles":{
            "a":{
}},
          "objects":[{
              "id":"100aca82d8ba4f469124ed3ac7057778",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":10},
                "size":{
                  "width":300,
                  "height":420}},
              "adaptiveStyles":{
                "a":{
}}}],
          "images":{
            "normal~":"images/浏览器/u7.png"}}]}},
  "masters":{
    "52ee8f3ceac7427591e65387d4ad55e3":{
      "packageId":"52ee8f3ceac7427591e65387d4ad55e3",
      "type":"Axure:Master",
      "name":"浏览器底导航栏",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
        "a":{
}},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"969da570c0754d46aab9ef185820f2e9",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":0,
                "y":440},
              "size":{
                "width":320,
                "height":40}},
            "adaptiveStyles":{
              "a":{
}},
            "objects":[{
                "id":"c2ffe21ef1514ea7987ef7fddc6ca934",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":0,
                    "y":440},
                  "size":{
                    "width":320,
                    "height":40}},
                "adaptiveStyles":{
                  "a":{
}}}],
            "images":{
              "normal~":"images/订单/u15_a.png"}},
{
            "id":"b4fd103904ed416490dc192678eba5e2",
            "label":"",
            "type":"button",
            "styleType":"button",
            "visible":true,
            "style":{
              "location":{
                "x":10,
                "y":448},
              "size":{
                "width":60,
                "height":25}},
            "adaptiveStyles":{
              "a":{
}},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 返回",
                        "target":{
                          "targetType":"backUrl",
                          "includeVariables":false},
                        "linkType":"current"}]}]}},
            "tabbable":true},
{
            "id":"334bc3d49c4a4be6986c74660162b40b",
            "label":"",
            "type":"button",
            "styleType":"button",
            "visible":true,
            "style":{
              "location":{
                "x":90,
                "y":448},
              "size":{
                "width":60,
                "height":25}},
            "adaptiveStyles":{
              "a":{
}},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 返回",
                        "target":{
                          "targetType":"backUrl",
                          "includeVariables":false},
                        "linkType":"current"}]}]}},
            "tabbable":true},
{
            "id":"1eb29815b01a418bada419582403b646",
            "label":"",
            "type":"button",
            "styleType":"button",
            "visible":true,
            "style":{
              "location":{
                "x":170,
                "y":448},
              "size":{
                "width":60,
                "height":25}},
            "adaptiveStyles":{
              "a":{
}},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 重新加载",
                        "target":{
                          "targetType":"reloadPage",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true},
{
            "id":"12acd01b39ef412888d57e215966046b",
            "label":"",
            "type":"button",
            "styleType":"button",
            "visible":true,
            "style":{
              "location":{
                "x":250,
                "y":447.5},
              "size":{
                "width":60,
                "height":25}},
            "adaptiveStyles":{
              "a":{
}}}]}}},
  "objectPaths":{
    "1bc6230dcbc44d6285487c09d159ab56":{
      "scriptId":"u0",
      "969da570c0754d46aab9ef185820f2e9":{
        "scriptId":"u1"},
      "c2ffe21ef1514ea7987ef7fddc6ca934":{
        "scriptId":"u2"},
      "b4fd103904ed416490dc192678eba5e2":{
        "scriptId":"u3"},
      "334bc3d49c4a4be6986c74660162b40b":{
        "scriptId":"u4"},
      "1eb29815b01a418bada419582403b646":{
        "scriptId":"u5"},
      "12acd01b39ef412888d57e215966046b":{
        "scriptId":"u6"}},
    "dec161a9835e459b9703d5cca4b12302":{
      "scriptId":"u7"},
    "100aca82d8ba4f469124ed3ac7057778":{
      "scriptId":"u8"}}});