$axure.loadCurrentPage({
  "url":"客户平价界面.html",
  "generationDate":new Date(1421169786972.48),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"isLogin"],
  "page":{
    "packageId":"57378fb78dd343879fef46a51183a3df",
    "type":"Axure:Page",
    "name":"客户平价界面",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
      "a":{
}},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"4c3d73866976452a85d79de7dbb11643",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
            "a":{
}},
          "masterId":"c0462b19eeab412787c3050c808291eb"},
{
          "id":"55496bdaea814bc099d9232f86b8c48a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":120,
              "y":14},
            "size":{
              "width":81,
              "height":23}},
          "adaptiveStyles":{
            "a":{
              "location":{
                "x":120,
                "y":14}}},
          "objects":[{
              "id":"002b562d8fe84066a6631d9ea8fbf2f6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":120,
                  "y":14},
                "size":{
                  "width":81,
                  "height":23}},
              "adaptiveStyles":{
                "a":{
}}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "normal~a":"resources/images/transparent.gif"}},
{
          "id":"2eede03f65684b278b5331688575e56e",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":96},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
            "a":{
}},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"eec052e6d09e44579b2bd75d14864f59",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"7ea09f4e80394e65b5e9768bf59ef8cf",
                  "label":"",
                  "parentDynamicPanel":"2eede03f65684b278b5331688575e56e",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":320,
                      "height":190}},
                  "adaptiveStyles":{
                    "a":{
}},
                  "objects":[{
                      "id":"0466be96b5314834beaa1f6a1b1e8555",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2eede03f65684b278b5331688575e56e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":320,
                          "height":190}},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"images/客户平价界面/u7.png"}},
{
                  "id":"b16c44affe024b53b37c532e9e15870b",
                  "label":"",
                  "parentDynamicPanel":"2eede03f65684b278b5331688575e56e",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":20,
                      "y":10},
                    "size":{
                      "width":50,
                      "height":50}},
                  "adaptiveStyles":{
                    "a":{
}},
                  "objects":[{
                      "id":"188f7bad97dd4c6fb849f246b26d1927",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2eede03f65684b278b5331688575e56e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":20,
                          "y":10},
                        "size":{
                          "width":50,
                          "height":50}},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"images/我的/u17.png"}},
{
                  "id":"64a66f2a4b284cf29ff6a1a876541750",
                  "label":"",
                  "parentDynamicPanel":"2eede03f65684b278b5331688575e56e",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":80,
                      "y":10},
                    "size":{
                      "width":114,
                      "height":16}},
                  "adaptiveStyles":{
                    "a":{
                      "size":{
                        "width":114,
                        "height":16}}},
                  "objects":[{
                      "id":"905cb5c88ad64526adf8687e5d5d5e85",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2eede03f65684b278b5331688575e56e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":80,
                          "y":10},
                        "size":{
                          "width":114,
                          "height":16}},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "normal~a":"resources/images/transparent.gif"}},
{
                  "id":"00e23a65a7d14b7696fe542506c68c0d",
                  "label":"",
                  "parentDynamicPanel":"2eede03f65684b278b5331688575e56e",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":80,
                      "y":44},
                    "size":{
                      "width":196,
                      "height":48}},
                  "adaptiveStyles":{
                    "a":{
                      "size":{
                        "width":196,
                        "height":48}}},
                  "objects":[{
                      "id":"d33a20faa5244e54b453ddb39eafa8bd",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2eede03f65684b278b5331688575e56e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":80,
                          "y":44},
                        "size":{
                          "width":196,
                          "height":48}},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "normal~a":"resources/images/transparent.gif"}},
{
                  "id":"a47b37f068504e05abe92616c246fa0b",
                  "label":"",
                  "parentDynamicPanel":"2eede03f65684b278b5331688575e56e",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":50,
                      "y":92},
                    "size":{
                      "width":50,
                      "height":50}},
                  "adaptiveStyles":{
                    "a":{
}},
                  "objects":[{
                      "id":"d7956027dc1545e08c4eb7ca1abc1403",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2eede03f65684b278b5331688575e56e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":50,
                          "y":92},
                        "size":{
                          "width":50,
                          "height":50}},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"images/我的/u17.png"}},
{
                  "id":"95858efb0f514c7e9e4d06dd6e2cf2a3",
                  "label":"",
                  "parentDynamicPanel":"2eede03f65684b278b5331688575e56e",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":135,
                      "y":92},
                    "size":{
                      "width":50,
                      "height":50}},
                  "adaptiveStyles":{
                    "a":{
}},
                  "objects":[{
                      "id":"3813e87d1a3c4901b27fca47362dfec3",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2eede03f65684b278b5331688575e56e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":135,
                          "y":92},
                        "size":{
                          "width":50,
                          "height":50}},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"images/我的/u17.png"}},
{
                  "id":"96c6bd8608bd451f8e86a3e9a753f6d7",
                  "label":"",
                  "parentDynamicPanel":"2eede03f65684b278b5331688575e56e",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":220,
                      "y":92},
                    "size":{
                      "width":50,
                      "height":50}},
                  "adaptiveStyles":{
                    "a":{
}},
                  "objects":[{
                      "id":"fbde965644a4422bb61197dc77bcd80c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2eede03f65684b278b5331688575e56e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":220,
                          "y":92},
                        "size":{
                          "width":50,
                          "height":50}},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"images/我的/u17.png"}},
{
                  "id":"7ba3568c727a4cc5b3a6394ba050f216",
                  "label":"",
                  "parentDynamicPanel":"2eede03f65684b278b5331688575e56e",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":50,
                      "y":160},
                    "size":{
                      "width":90,
                      "height":16}},
                  "adaptiveStyles":{
                    "a":{
                      "size":{
                        "width":90,
                        "height":16}}},
                  "objects":[{
                      "id":"8f0a12e4e3c2418ca8a7bc7abb103a5c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2eede03f65684b278b5331688575e56e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":50,
                          "y":160},
                        "size":{
                          "width":90,
                          "height":16}},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "normal~a":"resources/images/transparent.gif"}}]}]},
{
          "id":"2d42c02045184067b1c2ffeda261eaf5",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":287},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
            "a":{
}},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"7f78a8c2a58349bd96e66a6ef354b5a6",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"b5d9d22bcccc4089a499ff848da21070",
                  "label":"",
                  "parentDynamicPanel":"2d42c02045184067b1c2ffeda261eaf5",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":320,
                      "height":190}},
                  "adaptiveStyles":{
                    "a":{
}},
                  "objects":[{
                      "id":"26b0e9e6f16b4a418b5be3e896c10f6e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2d42c02045184067b1c2ffeda261eaf5",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":320,
                          "height":190}},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"images/客户平价界面/u7.png"}},
{
                  "id":"e89e401230ee44bb84ab381889c81d4d",
                  "label":"",
                  "parentDynamicPanel":"2d42c02045184067b1c2ffeda261eaf5",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":20,
                      "y":10},
                    "size":{
                      "width":50,
                      "height":50}},
                  "adaptiveStyles":{
                    "a":{
}},
                  "objects":[{
                      "id":"be6b3aed462e4493aab6d9392b9f8c20",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2d42c02045184067b1c2ffeda261eaf5",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":20,
                          "y":10},
                        "size":{
                          "width":50,
                          "height":50}},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"images/我的/u17.png"}},
{
                  "id":"a411d65a89c64d62ae3684fe7fcfe785",
                  "label":"",
                  "parentDynamicPanel":"2d42c02045184067b1c2ffeda261eaf5",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":80,
                      "y":10},
                    "size":{
                      "width":114,
                      "height":16}},
                  "adaptiveStyles":{
                    "a":{
                      "size":{
                        "width":114,
                        "height":16}}},
                  "objects":[{
                      "id":"27eb03648757421d85181952f8a1a070",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2d42c02045184067b1c2ffeda261eaf5",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":80,
                          "y":10},
                        "size":{
                          "width":114,
                          "height":16}},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "normal~a":"resources/images/transparent.gif"}},
{
                  "id":"e770fa9acd414a3f9fffdd1236407c9b",
                  "label":"",
                  "parentDynamicPanel":"2d42c02045184067b1c2ffeda261eaf5",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":80,
                      "y":44},
                    "size":{
                      "width":196,
                      "height":48}},
                  "adaptiveStyles":{
                    "a":{
                      "size":{
                        "width":196,
                        "height":48}}},
                  "objects":[{
                      "id":"f6e498de13724c1b9f813e3968eac5df",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2d42c02045184067b1c2ffeda261eaf5",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":80,
                          "y":44},
                        "size":{
                          "width":196,
                          "height":48}},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "normal~a":"resources/images/transparent.gif"}},
{
                  "id":"31ebb4a09c2e410299a584a5b7442595",
                  "label":"",
                  "parentDynamicPanel":"2d42c02045184067b1c2ffeda261eaf5",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":50,
                      "y":92},
                    "size":{
                      "width":50,
                      "height":50}},
                  "adaptiveStyles":{
                    "a":{
}},
                  "objects":[{
                      "id":"4997d67212f9442dba80b086de8ecafa",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2d42c02045184067b1c2ffeda261eaf5",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":50,
                          "y":92},
                        "size":{
                          "width":50,
                          "height":50}},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"images/我的/u17.png"}},
{
                  "id":"75967bfda0d146fb9d526ade44fe3055",
                  "label":"",
                  "parentDynamicPanel":"2d42c02045184067b1c2ffeda261eaf5",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":135,
                      "y":92},
                    "size":{
                      "width":50,
                      "height":50}},
                  "adaptiveStyles":{
                    "a":{
}},
                  "objects":[{
                      "id":"f031351dff5742f591a1a1bfcf43f927",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2d42c02045184067b1c2ffeda261eaf5",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":135,
                          "y":92},
                        "size":{
                          "width":50,
                          "height":50}},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"images/我的/u17.png"}},
{
                  "id":"e1f5bece1c7443f9a4e2705cf305845c",
                  "label":"",
                  "parentDynamicPanel":"2d42c02045184067b1c2ffeda261eaf5",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":220,
                      "y":92},
                    "size":{
                      "width":50,
                      "height":50}},
                  "adaptiveStyles":{
                    "a":{
}},
                  "objects":[{
                      "id":"2506d738d0114b5d94202e65c3d5afb6",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2d42c02045184067b1c2ffeda261eaf5",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":220,
                          "y":92},
                        "size":{
                          "width":50,
                          "height":50}},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"images/我的/u17.png"}},
{
                  "id":"a7f1250a8201428a825360183046b2a8",
                  "label":"",
                  "parentDynamicPanel":"2d42c02045184067b1c2ffeda261eaf5",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":50,
                      "y":160},
                    "size":{
                      "width":90,
                      "height":16}},
                  "adaptiveStyles":{
                    "a":{
                      "size":{
                        "width":90,
                        "height":16}}},
                  "objects":[{
                      "id":"fbfbe925b42048ccaee1ad69fbfd4f60",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2d42c02045184067b1c2ffeda261eaf5",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":50,
                          "y":160},
                        "size":{
                          "width":90,
                          "height":16}},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "normal~a":"resources/images/transparent.gif"}}]}]},
{
          "id":"0565366bf26e42c097c3cc585e3aac44",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1,
              "y":50},
            "size":{
              "width":319,
              "height":46}},
          "adaptiveStyles":{
            "a":{
}},
          "objects":[{
              "id":"681e79d5ebcc4c90973db5a71f6e7d84",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1,
                  "y":50},
                "size":{
                  "width":319,
                  "height":46}},
              "adaptiveStyles":{
                "a":{
}}}],
          "images":{
            "normal~":"images/客户平价界面/u40.png"}},
{
          "id":"552144feb54b437cad9754019ad482dd",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":1,
              "y":50},
            "size":{
              "width":80,
              "height":46}},
          "adaptiveStyles":{
            "a":{
}}},
{
          "id":"65d427f6d7ad499494c9cdbbe97ed0bb",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":81,
              "y":50},
            "size":{
              "width":80,
              "height":46}},
          "adaptiveStyles":{
            "a":{
}}},
{
          "id":"fdd890821faf4461a30571d9c5aa154e",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":160,
              "y":50},
            "size":{
              "width":80,
              "height":46}},
          "adaptiveStyles":{
            "a":{
}}},
{
          "id":"6592537e7673414b85230ee8940f93fd",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":240,
              "y":50},
            "size":{
              "width":80,
              "height":46}},
          "adaptiveStyles":{
            "a":{
}}}]}},
  "masters":{
    "c0462b19eeab412787c3050c808291eb":{
      "packageId":"c0462b19eeab412787c3050c808291eb",
      "type":"Axure:Master",
      "name":"上返回栏",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
        "a":{
}},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"3a8352b0bdb94ce9a3089c99ad30d525",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "size":{
                "width":200,
                "height":100},
              "limbo":true},
            "adaptiveStyles":{
              "a":{
                "size":{
                  "width":320,
                  "height":50},
                "limbo":false}},
            "objects":[{
                "id":"5e026ecd19c44faaaf17922e877148fb",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":200,
                    "height":100},
                  "limbo":true},
                "adaptiveStyles":{
                  "a":{
}}}],
            "images":{
              "normal~":"images/主页/u9.png",
              "normal~a":"images/主页/u9_a.png"}},
{
            "id":"9b46f5ced4cd494bb946afb473a1d17b",
            "label":"",
            "type":"button",
            "styleType":"button",
            "visible":true,
            "style":{
              "location":{
                "x":211,
                "y":13},
              "size":{
                "width":100,
                "height":25},
              "limbo":true},
            "adaptiveStyles":{
              "a":{
                "location":{
                  "x":10,
                  "y":12.5},
                "size":{
                  "width":71,
                  "height":25},
                "limbo":false}},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 返回",
                        "target":{
                          "targetType":"backUrl",
                          "includeVariables":false},
                        "linkType":"current"}]}]}},
            "tabbable":true}]}}},
  "objectPaths":{
    "4c3d73866976452a85d79de7dbb11643":{
      "scriptId":"u0",
      "3a8352b0bdb94ce9a3089c99ad30d525":{
        "scriptId":"u1"},
      "5e026ecd19c44faaaf17922e877148fb":{
        "scriptId":"u2"},
      "9b46f5ced4cd494bb946afb473a1d17b":{
        "scriptId":"u3"}},
    "55496bdaea814bc099d9232f86b8c48a":{
      "scriptId":"u4"},
    "002b562d8fe84066a6631d9ea8fbf2f6":{
      "scriptId":"u5"},
    "2eede03f65684b278b5331688575e56e":{
      "scriptId":"u6"},
    "7ea09f4e80394e65b5e9768bf59ef8cf":{
      "scriptId":"u7"},
    "0466be96b5314834beaa1f6a1b1e8555":{
      "scriptId":"u8"},
    "b16c44affe024b53b37c532e9e15870b":{
      "scriptId":"u9"},
    "188f7bad97dd4c6fb849f246b26d1927":{
      "scriptId":"u10"},
    "64a66f2a4b284cf29ff6a1a876541750":{
      "scriptId":"u11"},
    "905cb5c88ad64526adf8687e5d5d5e85":{
      "scriptId":"u12"},
    "00e23a65a7d14b7696fe542506c68c0d":{
      "scriptId":"u13"},
    "d33a20faa5244e54b453ddb39eafa8bd":{
      "scriptId":"u14"},
    "a47b37f068504e05abe92616c246fa0b":{
      "scriptId":"u15"},
    "d7956027dc1545e08c4eb7ca1abc1403":{
      "scriptId":"u16"},
    "95858efb0f514c7e9e4d06dd6e2cf2a3":{
      "scriptId":"u17"},
    "3813e87d1a3c4901b27fca47362dfec3":{
      "scriptId":"u18"},
    "96c6bd8608bd451f8e86a3e9a753f6d7":{
      "scriptId":"u19"},
    "fbde965644a4422bb61197dc77bcd80c":{
      "scriptId":"u20"},
    "7ba3568c727a4cc5b3a6394ba050f216":{
      "scriptId":"u21"},
    "8f0a12e4e3c2418ca8a7bc7abb103a5c":{
      "scriptId":"u22"},
    "2d42c02045184067b1c2ffeda261eaf5":{
      "scriptId":"u23"},
    "b5d9d22bcccc4089a499ff848da21070":{
      "scriptId":"u24"},
    "26b0e9e6f16b4a418b5be3e896c10f6e":{
      "scriptId":"u25"},
    "e89e401230ee44bb84ab381889c81d4d":{
      "scriptId":"u26"},
    "be6b3aed462e4493aab6d9392b9f8c20":{
      "scriptId":"u27"},
    "a411d65a89c64d62ae3684fe7fcfe785":{
      "scriptId":"u28"},
    "27eb03648757421d85181952f8a1a070":{
      "scriptId":"u29"},
    "e770fa9acd414a3f9fffdd1236407c9b":{
      "scriptId":"u30"},
    "f6e498de13724c1b9f813e3968eac5df":{
      "scriptId":"u31"},
    "31ebb4a09c2e410299a584a5b7442595":{
      "scriptId":"u32"},
    "4997d67212f9442dba80b086de8ecafa":{
      "scriptId":"u33"},
    "75967bfda0d146fb9d526ade44fe3055":{
      "scriptId":"u34"},
    "f031351dff5742f591a1a1bfcf43f927":{
      "scriptId":"u35"},
    "e1f5bece1c7443f9a4e2705cf305845c":{
      "scriptId":"u36"},
    "2506d738d0114b5d94202e65c3d5afb6":{
      "scriptId":"u37"},
    "a7f1250a8201428a825360183046b2a8":{
      "scriptId":"u38"},
    "fbfbe925b42048ccaee1ad69fbfd4f60":{
      "scriptId":"u39"},
    "0565366bf26e42c097c3cc585e3aac44":{
      "scriptId":"u40"},
    "681e79d5ebcc4c90973db5a71f6e7d84":{
      "scriptId":"u41"},
    "552144feb54b437cad9754019ad482dd":{
      "scriptId":"u42"},
    "65d427f6d7ad499494c9cdbbe97ed0bb":{
      "scriptId":"u43"},
    "fdd890821faf4461a30571d9c5aa154e":{
      "scriptId":"u44"},
    "6592537e7673414b85230ee8940f93fd":{
      "scriptId":"u45"}}});