$axure.loadCurrentPage({
  "url":"技师个人信息.html",
  "generationDate":new Date(1421557101167.23),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"isLogin"],
  "page":{
    "packageId":"99f8d8adbcde4fc982c065c0c64d3de8",
    "type":"Axure:Page",
    "name":"技师个人信息",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
      "a":{
}},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"8a1f3383dc71446bbb2dcf6fc434c2bc",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
            "a":{
}},
          "masterId":"c0462b19eeab412787c3050c808291eb"},
{
          "id":"f16151be0c5740da9044e09c55298b72",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":120,
              "y":14},
            "size":{
              "width":81,
              "height":23}},
          "adaptiveStyles":{
            "a":{
              "location":{
                "x":120,
                "y":14}}},
          "objects":[{
              "id":"92bfc8c23b424c6ebe793ea616c87839",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":120,
                  "y":14},
                "size":{
                  "width":81,
                  "height":23}},
              "adaptiveStyles":{
                "a":{
}}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "normal~a":"resources/images/transparent.gif"}},
{
          "id":"4ef5e1439d104ac5b9fcc96e5c852c34",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":136,
              "y":70},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
            "a":{
              "location":{
                "x":136,
                "y":70}}},
          "objects":[{
              "id":"d97f01caa4334133bdd2f33309ab4191",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":136,
                  "y":70},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
                "a":{
}}}],
          "images":{
            "normal~":"images/我的/u17.png",
            "normal~a":"images/我的/u17.png"}},
{
          "id":"9cc37f900f0740c197e8ba7a6cca47ef",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":134,
              "y":130},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
            "a":{
              "size":{
                "width":53,
                "height":16}}},
          "objects":[{
              "id":"7acc43077c65486ba4be5c35ad597ae9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":134,
                  "y":130},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
                "a":{
}}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "normal~a":"resources/images/transparent.gif"}},
{
          "id":"df5e89dc43594900bf0888c20db1301c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":134,
              "y":156},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
            "a":{
              "size":{
                "width":53,
                "height":16}}},
          "objects":[{
              "id":"27420622eb5b4d549633f36898d174d5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":134,
                  "y":156},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
                "a":{
}}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "normal~a":"resources/images/transparent.gif"}},
{
          "id":"fed81aebd8044ab7b782122ead3df521",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":190},
            "size":{
              "width":320,
              "height":100}},
          "adaptiveStyles":{
            "a":{
}},
          "objects":[{
              "id":"958a53ac41f648daa7c3539fc484d307",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":190},
                "size":{
                  "width":320,
                  "height":100}},
              "adaptiveStyles":{
                "a":{
}}}],
          "images":{
            "normal~":"images/技师个人信息/u14.png"}},
{
          "id":"a1dae30e82694905a777d831b0b5d358",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":290},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
            "a":{
}},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"20fedf7cbf4b47119393089a5e4745a6",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"f18e87648ad143bf89cd4fbbae27e03e",
                  "label":"",
                  "parentDynamicPanel":"a1dae30e82694905a777d831b0b5d358",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":320,
                      "height":70}},
                  "adaptiveStyles":{
                    "a":{
}},
                  "objects":[{
                      "id":"1c1fab6e98a445f7a647941956978de6",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"a1dae30e82694905a777d831b0b5d358",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":320,
                          "height":70}},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"images/技师展示界面/u28.png"}},
{
                  "id":"69f55932a2b74051bef69cd950f1d71c",
                  "label":"",
                  "parentDynamicPanel":"a1dae30e82694905a777d831b0b5d358",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":20,
                      "y":10},
                    "size":{
                      "width":50,
                      "height":50}},
                  "adaptiveStyles":{
                    "a":{
}},
                  "objects":[{
                      "id":"ca688c10eb72412a8485670404c0462a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"a1dae30e82694905a777d831b0b5d358",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":20,
                          "y":10},
                        "size":{
                          "width":50,
                          "height":50}},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"images/我的/u17.png"}}]}]},
{
          "id":"ce4efab7ac1c456ea7e180ca87a992ae",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":361},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
            "a":{
}},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"cebc66d619254cbc9bb7174b9dfbd562",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"e6a70e31f6f34eb398c7c5097d11f872",
                  "label":"",
                  "parentDynamicPanel":"ce4efab7ac1c456ea7e180ca87a992ae",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":320,
                      "height":70}},
                  "adaptiveStyles":{
                    "a":{
}},
                  "objects":[{
                      "id":"f0917ffa4c814e048e0342ed6e150267",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ce4efab7ac1c456ea7e180ca87a992ae",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":320,
                          "height":70}},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"images/技师展示界面/u28.png"}},
{
                  "id":"789d7e78c9fb4263a40f665ce5f3a582",
                  "label":"",
                  "parentDynamicPanel":"ce4efab7ac1c456ea7e180ca87a992ae",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":20,
                      "y":10},
                    "size":{
                      "width":50,
                      "height":50}},
                  "adaptiveStyles":{
                    "a":{
}},
                  "objects":[{
                      "id":"358fc26848ed43119b8484b16badde2a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ce4efab7ac1c456ea7e180ca87a992ae",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":20,
                          "y":10},
                        "size":{
                          "width":50,
                          "height":50}},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"images/我的/u17.png"}}]}]}]}},
  "masters":{
    "c0462b19eeab412787c3050c808291eb":{
      "packageId":"c0462b19eeab412787c3050c808291eb",
      "type":"Axure:Master",
      "name":"上返回栏",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
        "a":{
}},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"193809c55b604a239711248fd3b92b17",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "size":{
                "width":320,
                "height":480}},
            "adaptiveStyles":{
              "a":{
}},
            "objects":[{
                "id":"fb301888262643c4b28fcad2d5ca7aa9",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":320,
                    "height":480}},
                "adaptiveStyles":{
                  "a":{
}}}],
            "images":{
              "normal~":"images/主页/u1_a.png"}},
{
            "id":"3a8352b0bdb94ce9a3089c99ad30d525",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "size":{
                "width":200,
                "height":100},
              "limbo":true},
            "adaptiveStyles":{
              "a":{
                "size":{
                  "width":320,
                  "height":50},
                "limbo":false}},
            "objects":[{
                "id":"5e026ecd19c44faaaf17922e877148fb",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":200,
                    "height":100},
                  "limbo":true},
                "adaptiveStyles":{
                  "a":{
}}}],
            "images":{
              "normal~":"images/主页/u9.png",
              "normal~a":"images/主页/u9_a.png"}},
{
            "id":"9b46f5ced4cd494bb946afb473a1d17b",
            "label":"",
            "type":"button",
            "styleType":"button",
            "visible":true,
            "style":{
              "location":{
                "x":211,
                "y":13},
              "size":{
                "width":100,
                "height":25},
              "limbo":true},
            "adaptiveStyles":{
              "a":{
                "location":{
                  "x":10,
                  "y":12.5},
                "size":{
                  "width":71,
                  "height":25},
                "limbo":false}},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 返回",
                        "target":{
                          "targetType":"backUrl",
                          "includeVariables":false},
                        "linkType":"current"}]}]}},
            "tabbable":true}]}}},
  "objectPaths":{
    "8a1f3383dc71446bbb2dcf6fc434c2bc":{
      "scriptId":"u0",
      "193809c55b604a239711248fd3b92b17":{
        "scriptId":"u1"},
      "fb301888262643c4b28fcad2d5ca7aa9":{
        "scriptId":"u2"},
      "3a8352b0bdb94ce9a3089c99ad30d525":{
        "scriptId":"u3"},
      "5e026ecd19c44faaaf17922e877148fb":{
        "scriptId":"u4"},
      "9b46f5ced4cd494bb946afb473a1d17b":{
        "scriptId":"u5"}},
    "f16151be0c5740da9044e09c55298b72":{
      "scriptId":"u6"},
    "92bfc8c23b424c6ebe793ea616c87839":{
      "scriptId":"u7"},
    "4ef5e1439d104ac5b9fcc96e5c852c34":{
      "scriptId":"u8"},
    "d97f01caa4334133bdd2f33309ab4191":{
      "scriptId":"u9"},
    "9cc37f900f0740c197e8ba7a6cca47ef":{
      "scriptId":"u10"},
    "7acc43077c65486ba4be5c35ad597ae9":{
      "scriptId":"u11"},
    "df5e89dc43594900bf0888c20db1301c":{
      "scriptId":"u12"},
    "27420622eb5b4d549633f36898d174d5":{
      "scriptId":"u13"},
    "fed81aebd8044ab7b782122ead3df521":{
      "scriptId":"u14"},
    "958a53ac41f648daa7c3539fc484d307":{
      "scriptId":"u15"},
    "a1dae30e82694905a777d831b0b5d358":{
      "scriptId":"u16"},
    "f18e87648ad143bf89cd4fbbae27e03e":{
      "scriptId":"u17"},
    "1c1fab6e98a445f7a647941956978de6":{
      "scriptId":"u18"},
    "69f55932a2b74051bef69cd950f1d71c":{
      "scriptId":"u19"},
    "ca688c10eb72412a8485670404c0462a":{
      "scriptId":"u20"},
    "ce4efab7ac1c456ea7e180ca87a992ae":{
      "scriptId":"u21"},
    "e6a70e31f6f34eb398c7c5097d11f872":{
      "scriptId":"u22"},
    "f0917ffa4c814e048e0342ed6e150267":{
      "scriptId":"u23"},
    "789d7e78c9fb4263a40f665ce5f3a582":{
      "scriptId":"u24"},
    "358fc26848ed43119b8484b16badde2a":{
      "scriptId":"u25"}}});