$axure.loadCurrentPage({
  "url":"选择城市.html",
  "generationDate":new Date(1421557097802.76),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"isLogin"],
  "page":{
    "packageId":"b113d86c92c649a5b6acf0e87989d446",
    "type":"Axure:Page",
    "name":"选择城市",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
      "a":{
}},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"8df9b2932cc045a081490227d36e8544",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":200,
              "height":100},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
              "size":{
                "width":320,
                "height":480},
              "limbo":false}},
          "objects":[{
              "id":"2f0c4aa234bd4d2c96689980d144ae4f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":200,
                  "height":100},
                "limbo":true},
              "adaptiveStyles":{
                "a":{
}}}],
          "images":{
            "normal~":"images/主页/u9.png",
            "normal~a":"images/主页/u1_a.png"}},
{
          "id":"976694b8eba545eb8f4bcd65a5de1d0b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":200,
              "height":100},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
              "size":{
                "width":320,
                "height":50},
              "limbo":false}},
          "objects":[{
              "id":"9f4be36f375f41b0abddd61335fd00af",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":200,
                  "height":100},
                "limbo":true},
              "adaptiveStyles":{
                "a":{
}}}],
          "images":{
            "normal~":"images/主页/u9.png",
            "normal~a":"images/主页/u9_a.png"}},
{
          "id":"e273f4fd5f11430ea033ea8f76e742be",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":144,
              "y":17},
            "size":{
              "width":53,
              "height":16},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
              "fontSize":"18px",
              "location":{
                "x":124,
                "y":14},
              "size":{
                "width":73,
                "height":21},
              "limbo":false}},
          "objects":[{
              "id":"9b1532b1014743ce8fe904b4f5937bdf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":144,
                  "y":17},
                "size":{
                  "width":53,
                  "height":16},
                "limbo":true},
              "adaptiveStyles":{
                "a":{
}}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "normal~a":"resources/images/transparent.gif"}},
{
          "id":"d2fc9fad8977468483970c2889193c60",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":10},
            "size":{
              "width":100,
              "height":25},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
              "size":{
                "width":60,
                "height":30},
              "limbo":false}},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 返回",
                      "target":{
                        "targetType":"backUrl",
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"8bf6cdb6c4214ca8ba85af3b7fe235ac",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":60},
            "size":{
              "width":80,
              "height":16},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
              "size":{
                "width":80,
                "height":16},
              "limbo":false}},
          "objects":[{
              "id":"713b24168904440da6e558a946c59444",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":60},
                "size":{
                  "width":80,
                  "height":16},
                "limbo":true},
              "adaptiveStyles":{
                "a":{
}}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "normal~a":"resources/images/transparent.gif"}},
{
          "id":"78c9f56d23434872af853a3e50b33977",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":70},
            "size":{
              "width":92,
              "height":16},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
              "location":{
                "x":10,
                "y":120},
              "size":{
                "width":92,
                "height":16},
              "limbo":false}},
          "objects":[{
              "id":"b1f56f4187b94a68bf46e041bfccc4eb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":70},
                "size":{
                  "width":92,
                  "height":16},
                "limbo":true},
              "adaptiveStyles":{
                "a":{
}}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "normal~a":"resources/images/transparent.gif"}},
{
          "id":"46a85b6c45bf43e88792df5000543111",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":78},
            "size":{
              "width":200,
              "height":100},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
              "horizontalAlignment":"left",
              "size":{
                "width":320,
                "height":32},
              "limbo":false}},
          "objects":[{
              "id":"7256b53d89fa4a46b6a45ca89568af2d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":78},
                "size":{
                  "width":200,
                  "height":100},
                "limbo":true},
              "adaptiveStyles":{
                "a":{
}}}],
          "images":{
            "normal~":"images/主页/u9.png",
            "normal~a":"images/选择城市/u11_a.png"}},
{
          "id":"7cb4f3bb2d1c493b91b7ca00370397a3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":88},
            "size":{
              "width":200,
              "height":100},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
              "horizontalAlignment":"left",
              "location":{
                "x":0,
                "y":204},
              "size":{
                "width":320,
                "height":32},
              "limbo":false}},
          "objects":[{
              "id":"87f38946c27e4f7f913db446dcc761e8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":88},
                "size":{
                  "width":200,
                  "height":100},
                "limbo":true},
              "adaptiveStyles":{
                "a":{
}}}],
          "images":{
            "normal~":"images/主页/u9.png",
            "normal~a":"images/选择城市/u11_a.png"}},
{
          "id":"1482d0d308804151b255bfa83c4b26be",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":98},
            "size":{
              "width":200,
              "height":100},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
              "horizontalAlignment":"left",
              "location":{
                "x":0,
                "y":172},
              "size":{
                "width":320,
                "height":32},
              "limbo":false}},
          "objects":[{
              "id":"2c615884dbc94ffe9cc1c1224d226f1b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":98},
                "size":{
                  "width":200,
                  "height":100},
                "limbo":true},
              "adaptiveStyles":{
                "a":{
}}}],
          "images":{
            "normal~":"images/主页/u9.png",
            "normal~a":"images/选择城市/u11_a.png"}},
{
          "id":"1e2bc9bb05544fb5baa7e0072ce4257d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":108},
            "size":{
              "width":200,
              "height":100},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
              "horizontalAlignment":"left",
              "location":{
                "x":0,
                "y":140},
              "size":{
                "width":320,
                "height":32},
              "limbo":false}},
          "objects":[{
              "id":"39b39abc165b4343a075fbcd82d9389f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":108},
                "size":{
                  "width":200,
                  "height":100},
                "limbo":true},
              "adaptiveStyles":{
                "a":{
}}}],
          "images":{
            "normal~":"images/主页/u9.png",
            "normal~a":"images/选择城市/u11_a.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "8df9b2932cc045a081490227d36e8544":{
      "scriptId":"u0"},
    "2f0c4aa234bd4d2c96689980d144ae4f":{
      "scriptId":"u1"},
    "976694b8eba545eb8f4bcd65a5de1d0b":{
      "scriptId":"u2"},
    "9f4be36f375f41b0abddd61335fd00af":{
      "scriptId":"u3"},
    "e273f4fd5f11430ea033ea8f76e742be":{
      "scriptId":"u4"},
    "9b1532b1014743ce8fe904b4f5937bdf":{
      "scriptId":"u5"},
    "d2fc9fad8977468483970c2889193c60":{
      "scriptId":"u6"},
    "8bf6cdb6c4214ca8ba85af3b7fe235ac":{
      "scriptId":"u7"},
    "713b24168904440da6e558a946c59444":{
      "scriptId":"u8"},
    "78c9f56d23434872af853a3e50b33977":{
      "scriptId":"u9"},
    "b1f56f4187b94a68bf46e041bfccc4eb":{
      "scriptId":"u10"},
    "46a85b6c45bf43e88792df5000543111":{
      "scriptId":"u11"},
    "7256b53d89fa4a46b6a45ca89568af2d":{
      "scriptId":"u12"},
    "7cb4f3bb2d1c493b91b7ca00370397a3":{
      "scriptId":"u13"},
    "87f38946c27e4f7f913db446dcc761e8":{
      "scriptId":"u14"},
    "1482d0d308804151b255bfa83c4b26be":{
      "scriptId":"u15"},
    "2c615884dbc94ffe9cc1c1224d226f1b":{
      "scriptId":"u16"},
    "1e2bc9bb05544fb5baa7e0072ce4257d":{
      "scriptId":"u17"},
    "39b39abc165b4343a075fbcd82d9389f":{
      "scriptId":"u18"}}});