$axure.loadCurrentPage({
  "url":"更多.html",
  "generationDate":new Date(1421557097545.78),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"isLogin"],
  "page":{
    "packageId":"8130a8d91c374794a1560024bdce133a",
    "type":"Axure:Page",
    "name":"更多",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
      "a":{
}},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"b2dc721e0aa24721b8f50315f6ef1ab5",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "limbo":true},
          "adaptiveStyles":{
            "a":{
              "limbo":false}},
          "masterId":"e423deecdca540d69784293e6582ba81"},
{
          "id":"fac54d7d72a94d95a04f849fe3b1446f",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "limbo":true},
          "adaptiveStyles":{
            "a":{
              "limbo":false}},
          "masterId":"95d57cbcfde44948b7548a4f84555e79"},
{
          "id":"ecd76b6ab9f54566be5a16e07d05ebfa",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":144,
              "y":17},
            "size":{
              "width":27,
              "height":16},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
              "fontSize":"20px",
              "location":{
                "x":140,
                "y":14},
              "size":{
                "width":41,
                "height":23},
              "limbo":false}},
          "objects":[{
              "id":"1f7d167b89564f3fba0bf760e9074e0e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":144,
                  "y":17},
                "size":{
                  "width":27,
                  "height":16},
                "limbo":true},
              "adaptiveStyles":{
                "a":{
}}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "normal~a":"resources/images/transparent.gif"}},
{
          "id":"ea36e5f97d424d1f81d0e6b5bb876a27",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":70},
            "size":{
              "width":10,
              "height":10},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
              "limbo":false}},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"7ad89c57e009433d8c508e2ea7b97759",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"6011247193294cbd8ef8cd85d53632da",
                  "label":"",
                  "parentDynamicPanel":"ea36e5f97d424d1f81d0e6b5bb876a27",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":200,
                      "height":100},
                    "limbo":true},
                  "adaptiveStyles":{
                    "a":{
                      "horizontalAlignment":"left",
                      "size":{
                        "width":320,
                        "height":40},
                      "limbo":false}},
                  "objects":[{
                      "id":"1055b70e8e8b4ec79e16a772312c86f1",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ea36e5f97d424d1f81d0e6b5bb876a27",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":200,
                          "height":100},
                        "limbo":true},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"images/主页/u9.png",
                    "normal~a":"images/订单/u15_a.png"}},
{
                  "id":"68077ec9e1214713a6051284492aa6e9",
                  "label":"",
                  "parentDynamicPanel":"ea36e5f97d424d1f81d0e6b5bb876a27",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":210,
                      "y":5},
                    "size":{
                      "width":100,
                      "height":30},
                    "limbo":true,
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
                    "a":{
                      "location":{
                        "x":270,
                        "y":8},
                      "size":{
                        "width":30,
                        "height":25},
                      "limbo":false,
                      "borderWidth":"-1",
                      "linePattern":"none"}},
                  "objects":[{
                      "id":"71d40f07b58244bc9942499958cf9384",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ea36e5f97d424d1f81d0e6b5bb876a27",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":210,
                          "y":5},
                        "size":{
                          "width":100,
                          "height":30},
                        "limbo":true,
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"images/我的/u29.png",
                    "normal~a":"images/我的/u29_a.png"}}]}]},
{
          "id":"3d9e75ce39494bb29bd68317d59cc9bf",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":138},
            "size":{
              "width":10,
              "height":10},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
              "limbo":false}},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"9a2eb7f8f2d64dcdaaee540d9858b06a",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"ef6c8f680a554d59a884b3a793fd91d3",
                  "label":"",
                  "parentDynamicPanel":"3d9e75ce39494bb29bd68317d59cc9bf",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"left",
                    "size":{
                      "width":200,
                      "height":100},
                    "limbo":true},
                  "adaptiveStyles":{
                    "a":{
                      "size":{
                        "width":320,
                        "height":40},
                      "limbo":false}},
                  "objects":[{
                      "id":"bea212773e574f72accf149a6827724b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"3d9e75ce39494bb29bd68317d59cc9bf",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"left",
                        "size":{
                          "width":200,
                          "height":100},
                        "limbo":true},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"images/主页/u9.png",
                    "normal~a":"images/订单/u15_a.png"}},
{
                  "id":"26fecfc6eb49447485ad5f375aa63813",
                  "label":"",
                  "parentDynamicPanel":"3d9e75ce39494bb29bd68317d59cc9bf",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":270,
                      "y":8},
                    "size":{
                      "width":100,
                      "height":30},
                    "limbo":true,
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
                    "a":{
                      "size":{
                        "width":30,
                        "height":25},
                      "limbo":false,
                      "borderWidth":"-1",
                      "linePattern":"none"}},
                  "objects":[{
                      "id":"d89d583cd2864a078e9ef95b1fab2648",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"3d9e75ce39494bb29bd68317d59cc9bf",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":270,
                          "y":8},
                        "size":{
                          "width":100,
                          "height":30},
                        "limbo":true,
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"images/我的/u29.png",
                    "normal~a":"images/我的/u29_a.png"}}]}]},
{
          "id":"c72fddd7e8b34dc792d1fe28ca983e38",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":178},
            "size":{
              "width":10,
              "height":10},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
              "limbo":false}},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"36e62b919b904cbfbb4f3833fbf90ace",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"ff3717aac5c243b0b56ecf749f44d051",
                  "label":"",
                  "parentDynamicPanel":"c72fddd7e8b34dc792d1fe28ca983e38",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"left",
                    "size":{
                      "width":200,
                      "height":100},
                    "limbo":true},
                  "adaptiveStyles":{
                    "a":{
                      "size":{
                        "width":320,
                        "height":40},
                      "limbo":false}},
                  "objects":[{
                      "id":"259df4e93d8f4a53af48c1dcffa89467",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c72fddd7e8b34dc792d1fe28ca983e38",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"left",
                        "size":{
                          "width":200,
                          "height":100},
                        "limbo":true},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"images/主页/u9.png",
                    "normal~a":"images/订单/u15_a.png"}},
{
                  "id":"325ef6b6735d4884a5d231f77881495d",
                  "label":"",
                  "parentDynamicPanel":"c72fddd7e8b34dc792d1fe28ca983e38",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":270,
                      "y":8},
                    "size":{
                      "width":100,
                      "height":30},
                    "limbo":true,
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
                    "a":{
                      "size":{
                        "width":30,
                        "height":25},
                      "limbo":false,
                      "borderWidth":"-1",
                      "linePattern":"none"}},
                  "objects":[{
                      "id":"8d6cab29d9b04f1e83cc90ecd87f9f89",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c72fddd7e8b34dc792d1fe28ca983e38",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":270,
                          "y":8},
                        "size":{
                          "width":100,
                          "height":30},
                        "limbo":true,
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"images/我的/u29.png",
                    "normal~a":"images/我的/u29_a.png"}}]}]},
{
          "id":"2f539fdf73f54090ae606f0e9b93ff81",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":218},
            "size":{
              "width":10,
              "height":10},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
              "limbo":false}},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"367af804b75d461a83ec2cdeead1c8ca",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"c53c888df885432c85a03fe63ac3cb59",
                  "label":"",
                  "parentDynamicPanel":"2f539fdf73f54090ae606f0e9b93ff81",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"left",
                    "size":{
                      "width":200,
                      "height":100},
                    "limbo":true},
                  "adaptiveStyles":{
                    "a":{
                      "size":{
                        "width":320,
                        "height":40},
                      "limbo":false}},
                  "objects":[{
                      "id":"6058f7ebf9594005bc2be7b9a2ed7fb3",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2f539fdf73f54090ae606f0e9b93ff81",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"left",
                        "size":{
                          "width":200,
                          "height":100},
                        "limbo":true},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"images/主页/u9.png",
                    "normal~a":"images/订单/u15_a.png"}},
{
                  "id":"e58810fa69184a63b55f649dc44f55bf",
                  "label":"",
                  "parentDynamicPanel":"2f539fdf73f54090ae606f0e9b93ff81",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":270,
                      "y":8},
                    "size":{
                      "width":100,
                      "height":30},
                    "limbo":true,
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
                    "a":{
                      "size":{
                        "width":30,
                        "height":25},
                      "limbo":false,
                      "borderWidth":"-1",
                      "linePattern":"none"}},
                  "objects":[{
                      "id":"54031ecb436d491a99304b618ec8a5c9",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2f539fdf73f54090ae606f0e9b93ff81",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":270,
                          "y":8},
                        "size":{
                          "width":100,
                          "height":30},
                        "limbo":true,
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"images/我的/u29.png",
                    "normal~a":"images/我的/u29_a.png"}}]}]},
{
          "id":"261c828d23644f64954c42cbb55d0d8a",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":268},
            "size":{
              "width":10,
              "height":10},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
              "location":{
                "x":0,
                "y":258},
              "limbo":false}},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"22c380cdc5224cb5ae54993520f8c128",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"5e106de156594170aa6e1ae6c8f5f00c",
                  "label":"",
                  "parentDynamicPanel":"261c828d23644f64954c42cbb55d0d8a",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"left",
                    "size":{
                      "width":200,
                      "height":100},
                    "limbo":true},
                  "adaptiveStyles":{
                    "a":{
                      "size":{
                        "width":320,
                        "height":40},
                      "limbo":false}},
                  "objects":[{
                      "id":"a5c2023f6bc448f7a19583785935f807",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"261c828d23644f64954c42cbb55d0d8a",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"left",
                        "size":{
                          "width":200,
                          "height":100},
                        "limbo":true},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"images/主页/u9.png",
                    "normal~a":"images/订单/u15_a.png"}},
{
                  "id":"f06454cf55654c289afc46d45b23481f",
                  "label":"",
                  "parentDynamicPanel":"261c828d23644f64954c42cbb55d0d8a",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":270,
                      "y":8},
                    "size":{
                      "width":100,
                      "height":30},
                    "limbo":true,
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
                    "a":{
                      "size":{
                        "width":30,
                        "height":25},
                      "limbo":false,
                      "borderWidth":"-1",
                      "linePattern":"none"}},
                  "objects":[{
                      "id":"5fa44012628f443e88e5526e2bcff481",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"261c828d23644f64954c42cbb55d0d8a",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":270,
                          "y":8},
                        "size":{
                          "width":100,
                          "height":30},
                        "limbo":true,
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"images/我的/u29.png",
                    "normal~a":"images/我的/u29_a.png"}}]}]},
{
          "id":"7906f8f97e1145489a25dcb64c4cab80",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":258},
            "size":{
              "width":10,
              "height":10},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
              "location":{
                "x":0,
                "y":297},
              "limbo":false}},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"6687473e9b8448cf9c3ec8a5be115943",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"ddf8068fe4e94db8bff266fadbcdfd6e",
                  "label":"",
                  "parentDynamicPanel":"7906f8f97e1145489a25dcb64c4cab80",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"left",
                    "size":{
                      "width":200,
                      "height":100},
                    "limbo":true},
                  "adaptiveStyles":{
                    "a":{
                      "size":{
                        "width":320,
                        "height":40},
                      "limbo":false}},
                  "objects":[{
                      "id":"94fbada15c4f4a4aac9a3fdca6027008",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"7906f8f97e1145489a25dcb64c4cab80",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"left",
                        "size":{
                          "width":200,
                          "height":100},
                        "limbo":true},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"images/主页/u9.png",
                    "normal~a":"images/订单/u15_a.png"}},
{
                  "id":"ad12bf1506ea4855b699ce015861cc4e",
                  "label":"",
                  "parentDynamicPanel":"7906f8f97e1145489a25dcb64c4cab80",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":270,
                      "y":8},
                    "size":{
                      "width":100,
                      "height":30},
                    "limbo":true,
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
                    "a":{
                      "size":{
                        "width":30,
                        "height":25},
                      "limbo":false,
                      "borderWidth":"-1",
                      "linePattern":"none"}},
                  "objects":[{
                      "id":"27ecea83a4584ca1bc217ae9c439749c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"7906f8f97e1145489a25dcb64c4cab80",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":270,
                          "y":8},
                        "size":{
                          "width":100,
                          "height":30},
                        "limbo":true,
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"images/我的/u29.png",
                    "normal~a":"images/我的/u29_a.png"}}]}]}]}},
  "masters":{
    "e423deecdca540d69784293e6582ba81":{
      "packageId":"e423deecdca540d69784293e6582ba81",
      "type":"Axure:Master",
      "name":"下导航栏",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
        "a":{
}},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"46b38d34c95741f384d5e4d38e3120ee",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":0,
                "y":420},
              "size":{
                "width":320,
                "height":60}},
            "adaptiveStyles":{
              "a":{
                "location":{
                  "x":0,
                  "y":0},
                "size":{
                  "width":320,
                  "height":480}}},
            "objects":[{
                "id":"eee4e22156fe41d98e86bfcfbba3e560",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":0,
                    "y":420},
                  "size":{
                    "width":320,
                    "height":60}},
                "adaptiveStyles":{
                  "a":{
}}}],
            "images":{
              "normal~":"images/主页/u1.png",
              "normal~a":"images/主页/u1_a.png"}},
{
            "id":"a219148e8a9a42acb89b27adba3bd693",
            "label":"",
            "type":"button",
            "styleType":"button",
            "visible":true,
            "style":{
              "location":{
                "x":0,
                "y":420},
              "size":{
                "width":100,
                "height":25},
              "limbo":true},
            "adaptiveStyles":{
              "a":{
                "size":{
                  "width":64,
                  "height":60},
                "limbo":false}},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 主页",
                        "target":{
                          "targetType":"page",
                          "url":"主页.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true},
{
            "id":"6d76ed98f8af41ef971bb4aeeadd04f1",
            "label":"",
            "type":"button",
            "styleType":"button",
            "visible":true,
            "style":{
              "location":{
                "x":10,
                "y":430},
              "size":{
                "width":100,
                "height":25},
              "limbo":true},
            "adaptiveStyles":{
              "a":{
                "location":{
                  "x":64,
                  "y":420},
                "size":{
                  "width":64,
                  "height":60},
                "limbo":false}},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 订单",
                        "target":{
                          "targetType":"page",
                          "url":"订单.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true},
{
            "id":"5a6a8b09d0fa44cb996ec710d732c51a",
            "label":"",
            "type":"button",
            "styleType":"button",
            "visible":true,
            "style":{
              "location":{
                "x":20,
                "y":440},
              "size":{
                "width":100,
                "height":25},
              "limbo":true},
            "adaptiveStyles":{
              "a":{
                "location":{
                  "x":128,
                  "y":420},
                "size":{
                  "width":64,
                  "height":60},
                "limbo":false}},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 我的",
                        "target":{
                          "targetType":"page",
                          "url":"我的.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true},
{
            "id":"c346be56b3b148c394d01867f96020ed",
            "label":"",
            "type":"button",
            "styleType":"button",
            "visible":true,
            "style":{
              "location":{
                "x":30,
                "y":450},
              "size":{
                "width":100,
                "height":25},
              "limbo":true},
            "adaptiveStyles":{
              "a":{
                "location":{
                  "x":192,
                  "y":420},
                "size":{
                  "width":64,
                  "height":60},
                "limbo":false}},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 生活",
                        "target":{
                          "targetType":"page",
                          "url":"生活.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true},
{
            "id":"bee383944d00498cb4790c08da5a6c34",
            "label":"",
            "type":"button",
            "styleType":"button",
            "visible":true,
            "style":{
              "location":{
                "x":40,
                "y":460},
              "size":{
                "width":100,
                "height":25},
              "limbo":true},
            "adaptiveStyles":{
              "a":{
                "location":{
                  "x":256,
                  "y":420},
                "size":{
                  "width":64,
                  "height":60},
                "limbo":false}},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 更多",
                        "target":{
                          "targetType":"page",
                          "url":"更多.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true}]}},
    "95d57cbcfde44948b7548a4f84555e79":{
      "packageId":"95d57cbcfde44948b7548a4f84555e79",
      "type":"Axure:Master",
      "name":"上导航栏",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
        "a":{
}},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"3a8352b0bdb94ce9a3089c99ad30d525",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "size":{
                "width":200,
                "height":100},
              "limbo":true},
            "adaptiveStyles":{
              "a":{
                "size":{
                  "width":320,
                  "height":50},
                "limbo":false}},
            "objects":[{
                "id":"5e026ecd19c44faaaf17922e877148fb",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":200,
                    "height":100},
                  "limbo":true},
                "adaptiveStyles":{
                  "a":{
}}}],
            "images":{
              "normal~":"images/主页/u9.png",
              "normal~a":"images/主页/u9_a.png"}},
{
            "id":"daf03b54e1b54a3e931b529609a504e5",
            "label":"",
            "type":"button",
            "styleType":"button",
            "visible":true,
            "style":{
              "location":{
                "x":10,
                "y":12.5},
              "size":{
                "width":100,
                "height":25},
              "limbo":true},
            "adaptiveStyles":{
              "a":{
                "location":{
                  "x":10,
                  "y":14},
                "size":{
                  "width":70,
                  "height":23},
                "limbo":false}},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 选择城市",
                        "target":{
                          "targetType":"page",
                          "url":"选择城市.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true},
{
            "id":"9b46f5ced4cd494bb946afb473a1d17b",
            "label":"",
            "type":"button",
            "styleType":"button",
            "visible":true,
            "style":{
              "location":{
                "x":211,
                "y":13},
              "size":{
                "width":100,
                "height":25},
              "limbo":true},
            "adaptiveStyles":{
              "a":{
                "location":{
                  "x":240,
                  "y":13},
                "size":{
                  "width":71,
                  "height":25},
                "limbo":false}}}]}}},
  "objectPaths":{
    "b2dc721e0aa24721b8f50315f6ef1ab5":{
      "scriptId":"u0",
      "46b38d34c95741f384d5e4d38e3120ee":{
        "scriptId":"u1"},
      "eee4e22156fe41d98e86bfcfbba3e560":{
        "scriptId":"u2"},
      "a219148e8a9a42acb89b27adba3bd693":{
        "scriptId":"u3"},
      "6d76ed98f8af41ef971bb4aeeadd04f1":{
        "scriptId":"u4"},
      "5a6a8b09d0fa44cb996ec710d732c51a":{
        "scriptId":"u5"},
      "c346be56b3b148c394d01867f96020ed":{
        "scriptId":"u6"},
      "bee383944d00498cb4790c08da5a6c34":{
        "scriptId":"u7"}},
    "fac54d7d72a94d95a04f849fe3b1446f":{
      "scriptId":"u8",
      "3a8352b0bdb94ce9a3089c99ad30d525":{
        "scriptId":"u9"},
      "5e026ecd19c44faaaf17922e877148fb":{
        "scriptId":"u10"},
      "daf03b54e1b54a3e931b529609a504e5":{
        "scriptId":"u11"},
      "9b46f5ced4cd494bb946afb473a1d17b":{
        "scriptId":"u12"}},
    "ecd76b6ab9f54566be5a16e07d05ebfa":{
      "scriptId":"u13"},
    "1f7d167b89564f3fba0bf760e9074e0e":{
      "scriptId":"u14"},
    "ea36e5f97d424d1f81d0e6b5bb876a27":{
      "scriptId":"u15"},
    "6011247193294cbd8ef8cd85d53632da":{
      "scriptId":"u16"},
    "1055b70e8e8b4ec79e16a772312c86f1":{
      "scriptId":"u17"},
    "68077ec9e1214713a6051284492aa6e9":{
      "scriptId":"u18"},
    "71d40f07b58244bc9942499958cf9384":{
      "scriptId":"u19"},
    "3d9e75ce39494bb29bd68317d59cc9bf":{
      "scriptId":"u20"},
    "ef6c8f680a554d59a884b3a793fd91d3":{
      "scriptId":"u21"},
    "bea212773e574f72accf149a6827724b":{
      "scriptId":"u22"},
    "26fecfc6eb49447485ad5f375aa63813":{
      "scriptId":"u23"},
    "d89d583cd2864a078e9ef95b1fab2648":{
      "scriptId":"u24"},
    "c72fddd7e8b34dc792d1fe28ca983e38":{
      "scriptId":"u25"},
    "ff3717aac5c243b0b56ecf749f44d051":{
      "scriptId":"u26"},
    "259df4e93d8f4a53af48c1dcffa89467":{
      "scriptId":"u27"},
    "325ef6b6735d4884a5d231f77881495d":{
      "scriptId":"u28"},
    "8d6cab29d9b04f1e83cc90ecd87f9f89":{
      "scriptId":"u29"},
    "2f539fdf73f54090ae606f0e9b93ff81":{
      "scriptId":"u30"},
    "c53c888df885432c85a03fe63ac3cb59":{
      "scriptId":"u31"},
    "6058f7ebf9594005bc2be7b9a2ed7fb3":{
      "scriptId":"u32"},
    "e58810fa69184a63b55f649dc44f55bf":{
      "scriptId":"u33"},
    "54031ecb436d491a99304b618ec8a5c9":{
      "scriptId":"u34"},
    "261c828d23644f64954c42cbb55d0d8a":{
      "scriptId":"u35"},
    "5e106de156594170aa6e1ae6c8f5f00c":{
      "scriptId":"u36"},
    "a5c2023f6bc448f7a19583785935f807":{
      "scriptId":"u37"},
    "f06454cf55654c289afc46d45b23481f":{
      "scriptId":"u38"},
    "5fa44012628f443e88e5526e2bcff481":{
      "scriptId":"u39"},
    "7906f8f97e1145489a25dcb64c4cab80":{
      "scriptId":"u40"},
    "ddf8068fe4e94db8bff266fadbcdfd6e":{
      "scriptId":"u41"},
    "94fbada15c4f4a4aac9a3fdca6027008":{
      "scriptId":"u42"},
    "ad12bf1506ea4855b699ce015861cc4e":{
      "scriptId":"u43"},
    "27ecea83a4584ca1bc217ae9c439749c":{
      "scriptId":"u44"}}});