$axure.loadCurrentPage({
  "url":"服务地址.html",
  "generationDate":new Date(1421557099467.96),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"isLogin"],
  "page":{
    "packageId":"d4d62c19375e406ba448e607d6b0dbef",
    "type":"Axure:Page",
    "name":"服务地址",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
      "a":{
}},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"32c66c17779a493f8ccc610422e762c4",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
            "a":{
}},
          "masterId":"c0462b19eeab412787c3050c808291eb"},
{
          "id":"99e0563cd1254762bfab7cb519231543",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":120,
              "y":14},
            "size":{
              "width":81,
              "height":23}},
          "adaptiveStyles":{
            "a":{
              "location":{
                "x":120,
                "y":14},
              "size":{
                "width":81,
                "height":23}}},
          "objects":[{
              "id":"9a1a4cebdcaa45a193e34f0990e6d028",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":120,
                  "y":14},
                "size":{
                  "width":81,
                  "height":23}},
              "adaptiveStyles":{
                "a":{
}}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "normal~a":"resources/images/transparent.gif"}},
{
          "id":"ce957f7af1ee4aaba544254faa19f7c3",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":240,
              "y":12},
            "size":{
              "width":60,
              "height":25}},
          "adaptiveStyles":{
            "a":{
}},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 预约界面",
                      "target":{
                        "targetType":"page",
                        "url":"预约界面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"4912610aaf0644818d605ae1158a76fb",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":70},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
            "a":{
}},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 大地址联想",
                      "target":{
                        "targetType":"page",
                        "url":"大地址联想.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"507cdae6af14409f81d0d6fefbd2c619",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"e641c0411e804600b8161b38b2a7b26e",
                  "label":"",
                  "parentDynamicPanel":"4912610aaf0644818d605ae1158a76fb",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":270,
                      "height":40}},
                  "adaptiveStyles":{
                    "a":{
}},
                  "objects":[{
                      "id":"e9d8c72c542444139266d822642b83e6",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"4912610aaf0644818d605ae1158a76fb",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":270,
                          "height":40}},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"images/预约界面/u7.png"}},
{
                  "id":"1bd9e9ba807f42419ea0bd9f0bc75dc6",
                  "label":"",
                  "parentDynamicPanel":"4912610aaf0644818d605ae1158a76fb",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":10,
                      "y":5},
                    "size":{
                      "width":30,
                      "height":30}},
                  "adaptiveStyles":{
                    "a":{
}},
                  "objects":[{
                      "id":"638acf7f3d1546828ec9e5e62df6b832",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"4912610aaf0644818d605ae1158a76fb",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":10,
                          "y":5},
                        "size":{
                          "width":30,
                          "height":30}},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"images/预约界面/u9.png"}},
{
                  "id":"1bbb3d914323494584bc2d7f8761032b",
                  "label":"",
                  "parentDynamicPanel":"4912610aaf0644818d605ae1158a76fb",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":50,
                      "y":12},
                    "size":{
                      "width":79,
                      "height":16}},
                  "adaptiveStyles":{
                    "a":{
                      "size":{
                        "width":79,
                        "height":16}}},
                  "objects":[{
                      "id":"3a34e2ff9cd24725bf9efb70ff4e97c6",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"4912610aaf0644818d605ae1158a76fb",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":50,
                          "y":12},
                        "size":{
                          "width":79,
                          "height":16}},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "normal~a":"resources/images/transparent.gif"}}]}]},
{
          "id":"0ca40a046b2b4aadb79f3cca7ac7a79b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":134},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
            "a":{
              "size":{
                "width":53,
                "height":16}}},
          "objects":[{
              "id":"02052f567fc3441b8c8e053f5428dd9f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":134},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
                "a":{
}}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "normal~a":"resources/images/transparent.gif"}},
{
          "id":"50c2ac3459b44d0fa763a45bf5fa5c50",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":170},
            "size":{
              "width":270,
              "height":30}},
          "adaptiveStyles":{
            "a":{
}}},
{
          "id":"29df81dd4d6d4bad84509401c3d692e5",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":190,
              "y":220},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
            "a":{
}}}]}},
  "masters":{
    "c0462b19eeab412787c3050c808291eb":{
      "packageId":"c0462b19eeab412787c3050c808291eb",
      "type":"Axure:Master",
      "name":"上返回栏",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
        "a":{
}},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"193809c55b604a239711248fd3b92b17",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "size":{
                "width":320,
                "height":480}},
            "adaptiveStyles":{
              "a":{
}},
            "objects":[{
                "id":"fb301888262643c4b28fcad2d5ca7aa9",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":320,
                    "height":480}},
                "adaptiveStyles":{
                  "a":{
}}}],
            "images":{
              "normal~":"images/主页/u1_a.png"}},
{
            "id":"3a8352b0bdb94ce9a3089c99ad30d525",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "size":{
                "width":200,
                "height":100},
              "limbo":true},
            "adaptiveStyles":{
              "a":{
                "size":{
                  "width":320,
                  "height":50},
                "limbo":false}},
            "objects":[{
                "id":"5e026ecd19c44faaaf17922e877148fb",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":200,
                    "height":100},
                  "limbo":true},
                "adaptiveStyles":{
                  "a":{
}}}],
            "images":{
              "normal~":"images/主页/u9.png",
              "normal~a":"images/主页/u9_a.png"}},
{
            "id":"9b46f5ced4cd494bb946afb473a1d17b",
            "label":"",
            "type":"button",
            "styleType":"button",
            "visible":true,
            "style":{
              "location":{
                "x":211,
                "y":13},
              "size":{
                "width":100,
                "height":25},
              "limbo":true},
            "adaptiveStyles":{
              "a":{
                "location":{
                  "x":10,
                  "y":12.5},
                "size":{
                  "width":71,
                  "height":25},
                "limbo":false}},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 返回",
                        "target":{
                          "targetType":"backUrl",
                          "includeVariables":false},
                        "linkType":"current"}]}]}},
            "tabbable":true}]}}},
  "objectPaths":{
    "32c66c17779a493f8ccc610422e762c4":{
      "scriptId":"u0",
      "193809c55b604a239711248fd3b92b17":{
        "scriptId":"u1"},
      "fb301888262643c4b28fcad2d5ca7aa9":{
        "scriptId":"u2"},
      "3a8352b0bdb94ce9a3089c99ad30d525":{
        "scriptId":"u3"},
      "5e026ecd19c44faaaf17922e877148fb":{
        "scriptId":"u4"},
      "9b46f5ced4cd494bb946afb473a1d17b":{
        "scriptId":"u5"}},
    "99e0563cd1254762bfab7cb519231543":{
      "scriptId":"u6"},
    "9a1a4cebdcaa45a193e34f0990e6d028":{
      "scriptId":"u7"},
    "ce957f7af1ee4aaba544254faa19f7c3":{
      "scriptId":"u8"},
    "4912610aaf0644818d605ae1158a76fb":{
      "scriptId":"u9"},
    "e641c0411e804600b8161b38b2a7b26e":{
      "scriptId":"u10"},
    "e9d8c72c542444139266d822642b83e6":{
      "scriptId":"u11"},
    "1bd9e9ba807f42419ea0bd9f0bc75dc6":{
      "scriptId":"u12"},
    "638acf7f3d1546828ec9e5e62df6b832":{
      "scriptId":"u13"},
    "1bbb3d914323494584bc2d7f8761032b":{
      "scriptId":"u14"},
    "3a34e2ff9cd24725bf9efb70ff4e97c6":{
      "scriptId":"u15"},
    "0ca40a046b2b4aadb79f3cca7ac7a79b":{
      "scriptId":"u16"},
    "02052f567fc3441b8c8e053f5428dd9f":{
      "scriptId":"u17"},
    "50c2ac3459b44d0fa763a45bf5fa5c50":{
      "scriptId":"u18"},
    "29df81dd4d6d4bad84509401c3d692e5":{
      "scriptId":"u19"}}});