$axure.loadCurrentPage({
  "url":"兑换优惠码.html",
  "generationDate":new Date(1421557103053.38),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"isLogin"],
  "page":{
    "packageId":"57ed1ec248c540cea1b70630452378ee",
    "type":"Axure:Page",
    "name":"兑换优惠码",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
      "a":{
}},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"19fed7a1a8b048f29ac84e3178c993e8",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
            "a":{
}},
          "masterId":"c0462b19eeab412787c3050c808291eb"},
{
          "id":"225b8de050a54a969a0296d181610f3b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":110,
              "y":12},
            "size":{
              "width":101,
              "height":23}},
          "adaptiveStyles":{
            "a":{
              "size":{
                "width":101,
                "height":23}}},
          "objects":[{
              "id":"7cf4e971d95c48f39075608ce1144ace",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":110,
                  "y":12},
                "size":{
                  "width":101,
                  "height":23}},
              "adaptiveStyles":{
                "a":{
}}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "normal~a":"resources/images/transparent.gif"}},
{
          "id":"6684b26b6e78421e90890c357d28b39c",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":170},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
            "a":{
}}},
{
          "id":"35ffa04e4ce64abf95f2fcaa7067d942",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":225},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
            "a":{
}}}]}},
  "masters":{
    "c0462b19eeab412787c3050c808291eb":{
      "packageId":"c0462b19eeab412787c3050c808291eb",
      "type":"Axure:Master",
      "name":"上返回栏",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
        "a":{
}},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"193809c55b604a239711248fd3b92b17",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "size":{
                "width":320,
                "height":480}},
            "adaptiveStyles":{
              "a":{
}},
            "objects":[{
                "id":"fb301888262643c4b28fcad2d5ca7aa9",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":320,
                    "height":480}},
                "adaptiveStyles":{
                  "a":{
}}}],
            "images":{
              "normal~":"images/主页/u1_a.png"}},
{
            "id":"3a8352b0bdb94ce9a3089c99ad30d525",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "size":{
                "width":200,
                "height":100},
              "limbo":true},
            "adaptiveStyles":{
              "a":{
                "size":{
                  "width":320,
                  "height":50},
                "limbo":false}},
            "objects":[{
                "id":"5e026ecd19c44faaaf17922e877148fb",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":200,
                    "height":100},
                  "limbo":true},
                "adaptiveStyles":{
                  "a":{
}}}],
            "images":{
              "normal~":"images/主页/u9.png",
              "normal~a":"images/主页/u9_a.png"}},
{
            "id":"9b46f5ced4cd494bb946afb473a1d17b",
            "label":"",
            "type":"button",
            "styleType":"button",
            "visible":true,
            "style":{
              "location":{
                "x":211,
                "y":13},
              "size":{
                "width":100,
                "height":25},
              "limbo":true},
            "adaptiveStyles":{
              "a":{
                "location":{
                  "x":10,
                  "y":12.5},
                "size":{
                  "width":71,
                  "height":25},
                "limbo":false}},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 返回",
                        "target":{
                          "targetType":"backUrl",
                          "includeVariables":false},
                        "linkType":"current"}]}]}},
            "tabbable":true}]}}},
  "objectPaths":{
    "19fed7a1a8b048f29ac84e3178c993e8":{
      "scriptId":"u0",
      "193809c55b604a239711248fd3b92b17":{
        "scriptId":"u1"},
      "fb301888262643c4b28fcad2d5ca7aa9":{
        "scriptId":"u2"},
      "3a8352b0bdb94ce9a3089c99ad30d525":{
        "scriptId":"u3"},
      "5e026ecd19c44faaaf17922e877148fb":{
        "scriptId":"u4"},
      "9b46f5ced4cd494bb946afb473a1d17b":{
        "scriptId":"u5"}},
    "225b8de050a54a969a0296d181610f3b":{
      "scriptId":"u6"},
    "7cf4e971d95c48f39075608ce1144ace":{
      "scriptId":"u7"},
    "6684b26b6e78421e90890c357d28b39c":{
      "scriptId":"u8"},
    "35ffa04e4ce64abf95f2fcaa7067d942":{
      "scriptId":"u9"}}});