$axure.loadCurrentPage({
  "url":"选择优惠券.html",
  "generationDate":new Date(1421557102731.35),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"isLogin"],
  "page":{
    "packageId":"2592da1fafed4e3cb0623e0d30fbaf4b",
    "type":"Axure:Page",
    "name":"选择优惠券",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
      "a":{
}},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"f13e1caf332440a29f2b2779dd8a1618",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
            "a":{
}},
          "masterId":"c0462b19eeab412787c3050c808291eb"},
{
          "id":"a19fcb81cbe14192922a054b9d1a386d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":130,
              "y":14},
            "size":{
              "width":61,
              "height":23}},
          "adaptiveStyles":{
            "a":{
              "size":{
                "width":61,
                "height":23}}},
          "objects":[{
              "id":"ab3e67c904a24569addd096132098c3a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":130,
                  "y":14},
                "size":{
                  "width":61,
                  "height":23}},
              "adaptiveStyles":{
                "a":{
}}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "normal~a":"resources/images/transparent.gif"}},
{
          "id":"1f671d2bccbc4270902bfe375c593ff5",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":60},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
            "a":{
}},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"e37879a3067c4474a437aebea90beb30",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"39c27a82260d4fa8971288afd7e1d422",
                  "label":"",
                  "parentDynamicPanel":"1f671d2bccbc4270902bfe375c593ff5",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":320,
                      "height":80}},
                  "adaptiveStyles":{
                    "a":{
}},
                  "objects":[{
                      "id":"811a9898d62e4edcbfcf29d91e54c760",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1f671d2bccbc4270902bfe375c593ff5",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":320,
                          "height":80}},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"images/项目详情/u8.png"}},
{
                  "id":"8a606b36aa66436f9f37c444c6ff2d39",
                  "label":"",
                  "parentDynamicPanel":"1f671d2bccbc4270902bfe375c593ff5",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"48px",
                    "location":{
                      "x":12,
                      "y":12},
                    "size":{
                      "width":128,
                      "height":55}},
                  "adaptiveStyles":{
                    "a":{
                      "size":{
                        "width":128,
                        "height":55}}},
                  "objects":[{
                      "id":"bbe224c442bc4b19a9d948fd9c7f0495",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1f671d2bccbc4270902bfe375c593ff5",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"48px",
                        "location":{
                          "x":12,
                          "y":12},
                        "size":{
                          "width":128,
                          "height":55}},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "normal~a":"resources/images/transparent.gif"}},
{
                  "id":"ae2365ff94b0473dbc3c7cf71e84801f",
                  "label":"",
                  "parentDynamicPanel":"1f671d2bccbc4270902bfe375c593ff5",
                  "type":"button",
                  "styleType":"button",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":210,
                      "y":27.5},
                    "size":{
                      "width":100,
                      "height":25}},
                  "adaptiveStyles":{
                    "a":{
}}}]}]},
{
          "id":"5f2120e5124f47b99636cbcab0476759",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":150},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
            "a":{
}},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"67994e5073864252a389cb6d6f4370a8",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"7022a7380c2744c5a9788f785994eb26",
                  "label":"",
                  "parentDynamicPanel":"5f2120e5124f47b99636cbcab0476759",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":320,
                      "height":80}},
                  "adaptiveStyles":{
                    "a":{
}},
                  "objects":[{
                      "id":"3f7b70f7066c460da584421896906e98",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"5f2120e5124f47b99636cbcab0476759",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":320,
                          "height":80}},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"images/项目详情/u8.png"}},
{
                  "id":"8fd1341b64994e259ab267eb1907ef71",
                  "label":"",
                  "parentDynamicPanel":"5f2120e5124f47b99636cbcab0476759",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"48px",
                    "location":{
                      "x":12,
                      "y":12},
                    "size":{
                      "width":128,
                      "height":55}},
                  "adaptiveStyles":{
                    "a":{
                      "location":{
                        "x":12,
                        "y":12},
                      "size":{
                        "width":128,
                        "height":55}}},
                  "objects":[{
                      "id":"be16b0ad46ea43759d8f2dcdc91ee418",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"5f2120e5124f47b99636cbcab0476759",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"48px",
                        "location":{
                          "x":12,
                          "y":12},
                        "size":{
                          "width":128,
                          "height":55}},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "normal~a":"resources/images/transparent.gif"}},
{
                  "id":"cd60d6f432634cbd9914534954161133",
                  "label":"",
                  "parentDynamicPanel":"5f2120e5124f47b99636cbcab0476759",
                  "type":"button",
                  "styleType":"button",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":210,
                      "y":27.5},
                    "size":{
                      "width":100,
                      "height":25}},
                  "adaptiveStyles":{
                    "a":{
}}}]}]},
{
          "id":"8e3c093ddbe748f6a0d8f50918395950",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":240},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
            "a":{
}},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"1c0874d0abd64dffbec3398a380c162d",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"1c8aeae1ce9f4af5bf3257cb76cc478f",
                  "label":"",
                  "parentDynamicPanel":"8e3c093ddbe748f6a0d8f50918395950",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":320,
                      "height":80}},
                  "adaptiveStyles":{
                    "a":{
}},
                  "objects":[{
                      "id":"3bf69e7fb9e44a4899d556f2085aaf4e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"8e3c093ddbe748f6a0d8f50918395950",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":320,
                          "height":80}},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"images/项目详情/u8.png"}},
{
                  "id":"2cb91938c4fd4dfb8779dbc5e5a44ccb",
                  "label":"",
                  "parentDynamicPanel":"8e3c093ddbe748f6a0d8f50918395950",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"48px",
                    "location":{
                      "x":12,
                      "y":12},
                    "size":{
                      "width":128,
                      "height":55}},
                  "adaptiveStyles":{
                    "a":{
                      "location":{
                        "x":12,
                        "y":12},
                      "size":{
                        "width":128,
                        "height":55}}},
                  "objects":[{
                      "id":"30530824687642c9a194ed2fe26ce5af",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"8e3c093ddbe748f6a0d8f50918395950",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"48px",
                        "location":{
                          "x":12,
                          "y":12},
                        "size":{
                          "width":128,
                          "height":55}},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "normal~a":"resources/images/transparent.gif"}},
{
                  "id":"00cf6b0b3004402ea72788710b4ade05",
                  "label":"",
                  "parentDynamicPanel":"8e3c093ddbe748f6a0d8f50918395950",
                  "type":"button",
                  "styleType":"button",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":210,
                      "y":27.5},
                    "size":{
                      "width":100,
                      "height":25}},
                  "adaptiveStyles":{
                    "a":{
}}}]}]},
{
          "id":"8c8ed020b0314d2ab71d57c5f481064a",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":210,
              "y":14},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
            "a":{
}},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 兑换优惠码",
                      "target":{
                        "targetType":"page",
                        "url":"兑换优惠码.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
    "c0462b19eeab412787c3050c808291eb":{
      "packageId":"c0462b19eeab412787c3050c808291eb",
      "type":"Axure:Master",
      "name":"上返回栏",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
        "a":{
}},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"193809c55b604a239711248fd3b92b17",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "size":{
                "width":320,
                "height":480}},
            "adaptiveStyles":{
              "a":{
}},
            "objects":[{
                "id":"fb301888262643c4b28fcad2d5ca7aa9",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":320,
                    "height":480}},
                "adaptiveStyles":{
                  "a":{
}}}],
            "images":{
              "normal~":"images/主页/u1_a.png"}},
{
            "id":"3a8352b0bdb94ce9a3089c99ad30d525",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "size":{
                "width":200,
                "height":100},
              "limbo":true},
            "adaptiveStyles":{
              "a":{
                "size":{
                  "width":320,
                  "height":50},
                "limbo":false}},
            "objects":[{
                "id":"5e026ecd19c44faaaf17922e877148fb",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":200,
                    "height":100},
                  "limbo":true},
                "adaptiveStyles":{
                  "a":{
}}}],
            "images":{
              "normal~":"images/主页/u9.png",
              "normal~a":"images/主页/u9_a.png"}},
{
            "id":"9b46f5ced4cd494bb946afb473a1d17b",
            "label":"",
            "type":"button",
            "styleType":"button",
            "visible":true,
            "style":{
              "location":{
                "x":211,
                "y":13},
              "size":{
                "width":100,
                "height":25},
              "limbo":true},
            "adaptiveStyles":{
              "a":{
                "location":{
                  "x":10,
                  "y":12.5},
                "size":{
                  "width":71,
                  "height":25},
                "limbo":false}},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 返回",
                        "target":{
                          "targetType":"backUrl",
                          "includeVariables":false},
                        "linkType":"current"}]}]}},
            "tabbable":true}]}}},
  "objectPaths":{
    "f13e1caf332440a29f2b2779dd8a1618":{
      "scriptId":"u0",
      "193809c55b604a239711248fd3b92b17":{
        "scriptId":"u1"},
      "fb301888262643c4b28fcad2d5ca7aa9":{
        "scriptId":"u2"},
      "3a8352b0bdb94ce9a3089c99ad30d525":{
        "scriptId":"u3"},
      "5e026ecd19c44faaaf17922e877148fb":{
        "scriptId":"u4"},
      "9b46f5ced4cd494bb946afb473a1d17b":{
        "scriptId":"u5"}},
    "a19fcb81cbe14192922a054b9d1a386d":{
      "scriptId":"u6"},
    "ab3e67c904a24569addd096132098c3a":{
      "scriptId":"u7"},
    "1f671d2bccbc4270902bfe375c593ff5":{
      "scriptId":"u8"},
    "39c27a82260d4fa8971288afd7e1d422":{
      "scriptId":"u9"},
    "811a9898d62e4edcbfcf29d91e54c760":{
      "scriptId":"u10"},
    "8a606b36aa66436f9f37c444c6ff2d39":{
      "scriptId":"u11"},
    "bbe224c442bc4b19a9d948fd9c7f0495":{
      "scriptId":"u12"},
    "ae2365ff94b0473dbc3c7cf71e84801f":{
      "scriptId":"u13"},
    "5f2120e5124f47b99636cbcab0476759":{
      "scriptId":"u14"},
    "7022a7380c2744c5a9788f785994eb26":{
      "scriptId":"u15"},
    "3f7b70f7066c460da584421896906e98":{
      "scriptId":"u16"},
    "8fd1341b64994e259ab267eb1907ef71":{
      "scriptId":"u17"},
    "be16b0ad46ea43759d8f2dcdc91ee418":{
      "scriptId":"u18"},
    "cd60d6f432634cbd9914534954161133":{
      "scriptId":"u19"},
    "8e3c093ddbe748f6a0d8f50918395950":{
      "scriptId":"u20"},
    "1c8aeae1ce9f4af5bf3257cb76cc478f":{
      "scriptId":"u21"},
    "3bf69e7fb9e44a4899d556f2085aaf4e":{
      "scriptId":"u22"},
    "2cb91938c4fd4dfb8779dbc5e5a44ccb":{
      "scriptId":"u23"},
    "30530824687642c9a194ed2fe26ce5af":{
      "scriptId":"u24"},
    "00cf6b0b3004402ea72788710b4ade05":{
      "scriptId":"u25"},
    "8c8ed020b0314d2ab71d57c5f481064a":{
      "scriptId":"u26"}}});