$axure.loadCurrentPage({
  "url":"订单.html",
  "generationDate":new Date(1421169781395.08),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"isLogin"],
  "page":{
    "packageId":"a73797f4d59b432ba96a4d15bf85f12d",
    "type":"Axure:Page",
    "name":"订单",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
      "a":{
}},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"9587e7045ade48a19d21a8420a1f22b7",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "limbo":true},
          "adaptiveStyles":{
            "a":{
              "limbo":false}},
          "masterId":"e423deecdca540d69784293e6582ba81"},
{
          "id":"b5ad8e2a823b46d9bae404629920d49c",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "limbo":true},
          "adaptiveStyles":{
            "a":{
              "limbo":false}},
          "masterId":"95d57cbcfde44948b7548a4f84555e79"},
{
          "id":"bfbfe13e6ed349e488eadfb8635aa266",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":144,
              "y":17},
            "size":{
              "width":27,
              "height":16},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
              "fontSize":"20px",
              "location":{
                "x":140,
                "y":14},
              "size":{
                "width":41,
                "height":23},
              "limbo":false}},
          "objects":[{
              "id":"e3ca2c294cf04d80a667d32191105cfb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":144,
                  "y":17},
                "size":{
                  "width":27,
                  "height":16},
                "limbo":true},
              "adaptiveStyles":{
                "a":{
}}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "normal~a":"resources/images/transparent.gif"}},
{
          "id":"bb5330eccb874a85890b14a84c1ba8c5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":50},
            "size":{
              "width":200,
              "height":100},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
              "size":{
                "width":320,
                "height":40},
              "limbo":false}},
          "objects":[{
              "id":"8c52a29052ac421eb400030749804719",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":50},
                "size":{
                  "width":200,
                  "height":100},
                "limbo":true},
              "adaptiveStyles":{
                "a":{
}}}],
          "images":{
            "normal~":"images/主页/u9.png",
            "normal~a":"images/订单/u15_a.png"}},
{
          "id":"41c779c9184e4946856683bb7224bc01",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":50},
            "size":{
              "width":100,
              "height":25},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
              "location":{
                "x":0,
                "y":57.5},
              "limbo":false}},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setPanelState",
                      "description":"设置 (动态面板) to 状态1",
                      "panelsToStates":[{
                          "panelPath":["21b195516061480db6d64cd21a92fc73"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":1,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "compress":false}}}]}]}]}},
          "tabbable":true},
{
          "id":"48961c2611c049abb830edf188f2d297",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":60},
            "size":{
              "width":100,
              "height":25},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
              "location":{
                "x":110,
                "y":57.5},
              "limbo":false}},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setPanelState",
                      "description":"设置 (动态面板) to 状态1",
                      "panelsToStates":[{
                          "panelPath":["21b195516061480db6d64cd21a92fc73"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":1,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "compress":false}}}]}]}]}},
          "tabbable":true},
{
          "id":"45dad1698f6b490fb3754ecade2bf852",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":70},
            "size":{
              "width":100,
              "height":25},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
              "location":{
                "x":220,
                "y":57.5},
              "limbo":false}},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setPanelState",
                      "description":"设置 (动态面板) to 状态3",
                      "panelsToStates":[{
                          "panelPath":["21b195516061480db6d64cd21a92fc73"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":2,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "compress":false}}}]}]}]}},
          "tabbable":true},
{
          "id":"21b195516061480db6d64cd21a92fc73",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":93},
            "size":{
              "width":10,
              "height":10},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
              "limbo":false}},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"2aa4e6703d3e4e1bb494e91d1ed7f38d",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"813fe14f82994ddda65c4077da53b7ba",
                  "label":"",
                  "parentDynamicPanel":"21b195516061480db6d64cd21a92fc73",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":200,
                      "height":100},
                    "limbo":true},
                  "adaptiveStyles":{
                    "a":{
                      "size":{
                        "width":320,
                        "height":237},
                      "limbo":false}},
                  "objects":[{
                      "id":"d857a6c2ba1144d88e53b2356e814bb7",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"21b195516061480db6d64cd21a92fc73",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":200,
                          "height":100},
                        "limbo":true},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"images/主页/u9.png",
                    "normal~a":"images/订单/u21_a.png"}},
{
                  "id":"15bab34f387e4d249532f63b0da1dab7",
                  "label":"",
                  "parentDynamicPanel":"21b195516061480db6d64cd21a92fc73",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":37},
                    "size":{
                      "width":200,
                      "height":10},
                    "limbo":true},
                  "adaptiveStyles":{
                    "a":{
                      "size":{
                        "width":320,
                        "height":10},
                      "limbo":false}},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/订单/u23_line.png",
                    "start~a":"resources/images/transparent.gif",
                    "end~a":"resources/images/transparent.gif",
                    "line~a":"images/订单/u23_line_a.png",
                    "start~a":"resources/images/transparent.gif",
                    "end~a":"resources/images/transparent.gif",
                    "line~a":"images/订单/u23_line_a.png"}},
{
                  "id":"0625d5dbd9444402b737decb074bf757",
                  "label":"",
                  "parentDynamicPanel":"21b195516061480db6d64cd21a92fc73",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":10,
                      "y":47},
                    "size":{
                      "width":200,
                      "height":10},
                    "limbo":true},
                  "adaptiveStyles":{
                    "a":{
                      "location":{
                        "x":0,
                        "y":142},
                      "size":{
                        "width":320,
                        "height":10},
                      "limbo":false}},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/订单/u23_line.png",
                    "start~a":"resources/images/transparent.gif",
                    "end~a":"resources/images/transparent.gif",
                    "line~a":"images/订单/u23_line_a.png",
                    "start~a":"resources/images/transparent.gif",
                    "end~a":"resources/images/transparent.gif",
                    "line~a":"images/订单/u23_line_a.png"}},
{
                  "id":"fbb0ec9a8d924e15821383f02136b679",
                  "label":"",
                  "parentDynamicPanel":"21b195516061480db6d64cd21a92fc73",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":20,
                      "y":57},
                    "size":{
                      "width":200,
                      "height":10},
                    "limbo":true},
                  "adaptiveStyles":{
                    "a":{
                      "location":{
                        "x":0,
                        "y":177},
                      "size":{
                        "width":320,
                        "height":10},
                      "limbo":false}},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/订单/u23_line.png",
                    "start~a":"resources/images/transparent.gif",
                    "end~a":"resources/images/transparent.gif",
                    "line~a":"images/订单/u23_line_a.png",
                    "start~a":"resources/images/transparent.gif",
                    "end~a":"resources/images/transparent.gif",
                    "line~a":"images/订单/u23_line_a.png"}},
{
                  "id":"e9107688314f496b8bf8d7525a807ead",
                  "label":"",
                  "parentDynamicPanel":"21b195516061480db6d64cd21a92fc73",
                  "type":"button",
                  "styleType":"button",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":130,
                      "y":187},
                    "size":{
                      "width":100,
                      "height":25},
                    "limbo":true},
                  "adaptiveStyles":{
                    "a":{
                      "location":{
                        "x":140,
                        "y":197},
                      "size":{
                        "width":70,
                        "height":25},
                      "limbo":false}}},
{
                  "id":"baf6c289f8cc486daf3eb4e3f87b66d1",
                  "label":"",
                  "parentDynamicPanel":"21b195516061480db6d64cd21a92fc73",
                  "type":"button",
                  "styleType":"button",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":150,
                      "y":207},
                    "size":{
                      "width":100,
                      "height":25},
                    "limbo":true},
                  "adaptiveStyles":{
                    "a":{
                      "location":{
                        "x":230,
                        "y":197},
                      "size":{
                        "width":70,
                        "height":25},
                      "limbo":false}}},
{
                  "id":"76a67abc3c614b4990967d7bbcf26c95",
                  "label":"",
                  "parentDynamicPanel":"21b195516061480db6d64cd21a92fc73",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":230,
                      "y":157},
                    "size":{
                      "width":84,
                      "height":16},
                    "limbo":true},
                  "adaptiveStyles":{
                    "a":{
                      "fontSize":"16px",
                      "location":{
                        "x":194,
                        "y":157},
                      "size":{
                        "width":106,
                        "height":18},
                      "limbo":false}},
                  "objects":[{
                      "id":"4265c6cc7fee46d7b1768ccc89d3af97",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"21b195516061480db6d64cd21a92fc73",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":230,
                          "y":157},
                        "size":{
                          "width":84,
                          "height":16},
                        "limbo":true},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "normal~a":"resources/images/transparent.gif"}},
{
                  "id":"a26fb5f7d63b48c496d0874b1e153779",
                  "label":"",
                  "parentDynamicPanel":"21b195516061480db6d64cd21a92fc73",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":249,
                      "y":11},
                    "size":{
                      "width":53,
                      "height":16},
                    "limbo":true},
                  "adaptiveStyles":{
                    "a":{
                      "location":{
                        "x":249,
                        "y":12},
                      "size":{
                        "width":53,
                        "height":16},
                      "limbo":false}},
                  "objects":[{
                      "id":"5f6be6ddf96e4d6aaccf5bbe138ef905",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"21b195516061480db6d64cd21a92fc73",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":249,
                          "y":11},
                        "size":{
                          "width":53,
                          "height":16},
                        "limbo":true},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "normal~a":"resources/images/transparent.gif"}},
{
                  "id":"3bf8b069216743a6acb6148f02c122df",
                  "label":"",
                  "parentDynamicPanel":"21b195516061480db6d64cd21a92fc73",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":18,
                      "y":11},
                    "size":{
                      "width":105,
                      "height":16},
                    "limbo":true},
                  "adaptiveStyles":{
                    "a":{
                      "fontSize":"16px",
                      "size":{
                        "width":129,
                        "height":16},
                      "limbo":false}},
                  "objects":[{
                      "id":"a460c1a386044172836a1b5884d7aa03",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"21b195516061480db6d64cd21a92fc73",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":18,
                          "y":11},
                        "size":{
                          "width":105,
                          "height":16},
                        "limbo":true},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "normal~a":"resources/images/transparent.gif"}},
{
                  "id":"23cd94f6ac6042ffae5c7bb193ef3ced",
                  "label":"",
                  "parentDynamicPanel":"21b195516061480db6d64cd21a92fc73",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":18,
                      "y":57},
                    "size":{
                      "width":183,
                      "height":32},
                    "limbo":true},
                  "adaptiveStyles":{
                    "a":{
                      "size":{
                        "width":183,
                        "height":32},
                      "limbo":false}},
                  "objects":[{
                      "id":"79fd4d72d80345bcbe184fabe7d01284",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"21b195516061480db6d64cd21a92fc73",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":18,
                          "y":57},
                        "size":{
                          "width":183,
                          "height":32},
                        "limbo":true},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "normal~a":"resources/images/transparent.gif"}}]},
{
              "id":"595d27cdc8ad427ab4fe94808d33bc4e",
              "label":"状态3",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"bc0aa0e119e14b3a8667c8367d477610",
                  "label":"",
                  "parentDynamicPanel":"21b195516061480db6d64cd21a92fc73",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":200,
                      "height":100},
                    "limbo":true},
                  "adaptiveStyles":{
                    "a":{
                      "size":{
                        "width":320,
                        "height":237},
                      "limbo":false}},
                  "objects":[{
                      "id":"ad4337d7058f469e971daf87949d4132",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"21b195516061480db6d64cd21a92fc73",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":200,
                          "height":100},
                        "limbo":true},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"images/主页/u9.png",
                    "normal~a":"images/订单/u21_a.png"}},
{
                  "id":"3a104f57a98d458bab8ae44bdcee13c3",
                  "label":"",
                  "parentDynamicPanel":"21b195516061480db6d64cd21a92fc73",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":37},
                    "size":{
                      "width":200,
                      "height":10},
                    "limbo":true},
                  "adaptiveStyles":{
                    "a":{
                      "size":{
                        "width":320,
                        "height":10},
                      "limbo":false}},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/订单/u23_line.png",
                    "start~a":"resources/images/transparent.gif",
                    "end~a":"resources/images/transparent.gif",
                    "line~a":"images/订单/u23_line_a.png",
                    "start~a":"resources/images/transparent.gif",
                    "end~a":"resources/images/transparent.gif",
                    "line~a":"images/订单/u23_line_a.png"}},
{
                  "id":"b5a30057acbf48d0aef8e224379b2ed8",
                  "label":"",
                  "parentDynamicPanel":"21b195516061480db6d64cd21a92fc73",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":10,
                      "y":47},
                    "size":{
                      "width":200,
                      "height":10},
                    "limbo":true},
                  "adaptiveStyles":{
                    "a":{
                      "location":{
                        "x":0,
                        "y":142},
                      "size":{
                        "width":320,
                        "height":10},
                      "limbo":false}},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/订单/u23_line.png",
                    "start~a":"resources/images/transparent.gif",
                    "end~a":"resources/images/transparent.gif",
                    "line~a":"images/订单/u23_line_a.png",
                    "start~a":"resources/images/transparent.gif",
                    "end~a":"resources/images/transparent.gif",
                    "line~a":"images/订单/u23_line_a.png"}},
{
                  "id":"6ab32cd5b91047a9a9d862cc490fedab",
                  "label":"",
                  "parentDynamicPanel":"21b195516061480db6d64cd21a92fc73",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":20,
                      "y":57},
                    "size":{
                      "width":200,
                      "height":10},
                    "limbo":true},
                  "adaptiveStyles":{
                    "a":{
                      "location":{
                        "x":0,
                        "y":177},
                      "size":{
                        "width":320,
                        "height":10},
                      "limbo":false}},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/订单/u23_line.png",
                    "start~a":"resources/images/transparent.gif",
                    "end~a":"resources/images/transparent.gif",
                    "line~a":"images/订单/u23_line_a.png",
                    "start~a":"resources/images/transparent.gif",
                    "end~a":"resources/images/transparent.gif",
                    "line~a":"images/订单/u23_line_a.png"}},
{
                  "id":"d392f270c1634b7fb87fb410783f9c44",
                  "label":"",
                  "parentDynamicPanel":"21b195516061480db6d64cd21a92fc73",
                  "type":"button",
                  "styleType":"button",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":130,
                      "y":187},
                    "size":{
                      "width":100,
                      "height":25},
                    "limbo":true},
                  "adaptiveStyles":{
                    "a":{
                      "location":{
                        "x":140,
                        "y":197},
                      "size":{
                        "width":70,
                        "height":25},
                      "visible":false,
                      "limbo":false}}},
{
                  "id":"f1ea3560273d4b0eb6fa63efa14c896f",
                  "label":"",
                  "parentDynamicPanel":"21b195516061480db6d64cd21a92fc73",
                  "type":"button",
                  "styleType":"button",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":150,
                      "y":207},
                    "size":{
                      "width":100,
                      "height":25},
                    "limbo":true},
                  "adaptiveStyles":{
                    "a":{
                      "location":{
                        "x":230,
                        "y":197},
                      "size":{
                        "width":70,
                        "height":25},
                      "limbo":false}}},
{
                  "id":"99de44e288b04e55b057cdbf1e5060e6",
                  "label":"",
                  "parentDynamicPanel":"21b195516061480db6d64cd21a92fc73",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":230,
                      "y":157},
                    "size":{
                      "width":84,
                      "height":16},
                    "limbo":true},
                  "adaptiveStyles":{
                    "a":{
                      "fontSize":"16px",
                      "location":{
                        "x":194,
                        "y":157},
                      "size":{
                        "width":106,
                        "height":18},
                      "limbo":false}},
                  "objects":[{
                      "id":"1d6b55e10970487484975d5031a6e742",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"21b195516061480db6d64cd21a92fc73",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":230,
                          "y":157},
                        "size":{
                          "width":84,
                          "height":16},
                        "limbo":true},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "normal~a":"resources/images/transparent.gif"}},
{
                  "id":"a4c7ea560c0e4e43bd9f47a0283b1cf0",
                  "label":"",
                  "parentDynamicPanel":"21b195516061480db6d64cd21a92fc73",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":249,
                      "y":11},
                    "size":{
                      "width":40,
                      "height":16},
                    "limbo":true},
                  "adaptiveStyles":{
                    "a":{
                      "location":{
                        "x":249,
                        "y":12},
                      "size":{
                        "width":40,
                        "height":16},
                      "limbo":false}},
                  "objects":[{
                      "id":"8bb8529e6ce04cb698977271cf7a5c34",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"21b195516061480db6d64cd21a92fc73",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":249,
                          "y":11},
                        "size":{
                          "width":40,
                          "height":16},
                        "limbo":true},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "normal~a":"resources/images/transparent.gif"}},
{
                  "id":"f02ae2db0db44d1e8b92c6ac70b8b5b5",
                  "label":"",
                  "parentDynamicPanel":"21b195516061480db6d64cd21a92fc73",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":18,
                      "y":11},
                    "size":{
                      "width":105,
                      "height":16},
                    "limbo":true},
                  "adaptiveStyles":{
                    "a":{
                      "fontSize":"16px",
                      "size":{
                        "width":129,
                        "height":16},
                      "limbo":false}},
                  "objects":[{
                      "id":"6cab6f1751c44ba484e2b54686e668c0",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"21b195516061480db6d64cd21a92fc73",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":18,
                          "y":11},
                        "size":{
                          "width":105,
                          "height":16},
                        "limbo":true},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "normal~a":"resources/images/transparent.gif"}},
{
                  "id":"c3e252c2165943b3af9f05e558dd240e",
                  "label":"",
                  "parentDynamicPanel":"21b195516061480db6d64cd21a92fc73",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":18,
                      "y":57},
                    "size":{
                      "width":183,
                      "height":32},
                    "limbo":true},
                  "adaptiveStyles":{
                    "a":{
                      "size":{
                        "width":183,
                        "height":32},
                      "limbo":false}},
                  "objects":[{
                      "id":"5b2798c69fb845ffa01ab92bac14c979",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"21b195516061480db6d64cd21a92fc73",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":18,
                          "y":57},
                        "size":{
                          "width":183,
                          "height":32},
                        "limbo":true},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "normal~a":"resources/images/transparent.gif"}}]}]}]}},
  "masters":{
    "e423deecdca540d69784293e6582ba81":{
      "packageId":"e423deecdca540d69784293e6582ba81",
      "type":"Axure:Master",
      "name":"下导航栏",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
        "a":{
}},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"46b38d34c95741f384d5e4d38e3120ee",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":0,
                "y":420},
              "size":{
                "width":320,
                "height":60}},
            "adaptiveStyles":{
              "a":{
                "location":{
                  "x":0,
                  "y":0},
                "size":{
                  "width":320,
                  "height":480}}},
            "objects":[{
                "id":"eee4e22156fe41d98e86bfcfbba3e560",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":0,
                    "y":420},
                  "size":{
                    "width":320,
                    "height":60}},
                "adaptiveStyles":{
                  "a":{
}}}],
            "images":{
              "normal~":"images/主页/u1.png",
              "normal~a":"images/主页/u1_a.png"}},
{
            "id":"a219148e8a9a42acb89b27adba3bd693",
            "label":"",
            "type":"button",
            "styleType":"button",
            "visible":true,
            "style":{
              "location":{
                "x":0,
                "y":420},
              "size":{
                "width":100,
                "height":25},
              "limbo":true},
            "adaptiveStyles":{
              "a":{
                "size":{
                  "width":64,
                  "height":60},
                "limbo":false}},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 主页",
                        "target":{
                          "targetType":"page",
                          "url":"主页.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true},
{
            "id":"6d76ed98f8af41ef971bb4aeeadd04f1",
            "label":"",
            "type":"button",
            "styleType":"button",
            "visible":true,
            "style":{
              "location":{
                "x":10,
                "y":430},
              "size":{
                "width":100,
                "height":25},
              "limbo":true},
            "adaptiveStyles":{
              "a":{
                "location":{
                  "x":64,
                  "y":420},
                "size":{
                  "width":64,
                  "height":60},
                "limbo":false}},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 订单",
                        "target":{
                          "targetType":"page",
                          "url":"订单.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true},
{
            "id":"5a6a8b09d0fa44cb996ec710d732c51a",
            "label":"",
            "type":"button",
            "styleType":"button",
            "visible":true,
            "style":{
              "location":{
                "x":20,
                "y":440},
              "size":{
                "width":100,
                "height":25},
              "limbo":true},
            "adaptiveStyles":{
              "a":{
                "location":{
                  "x":128,
                  "y":420},
                "size":{
                  "width":64,
                  "height":60},
                "limbo":false}},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 我的",
                        "target":{
                          "targetType":"page",
                          "url":"我的.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true},
{
            "id":"c346be56b3b148c394d01867f96020ed",
            "label":"",
            "type":"button",
            "styleType":"button",
            "visible":true,
            "style":{
              "location":{
                "x":30,
                "y":450},
              "size":{
                "width":100,
                "height":25},
              "limbo":true},
            "adaptiveStyles":{
              "a":{
                "location":{
                  "x":192,
                  "y":420},
                "size":{
                  "width":64,
                  "height":60},
                "limbo":false}},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 生活",
                        "target":{
                          "targetType":"page",
                          "url":"生活.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true},
{
            "id":"bee383944d00498cb4790c08da5a6c34",
            "label":"",
            "type":"button",
            "styleType":"button",
            "visible":true,
            "style":{
              "location":{
                "x":40,
                "y":460},
              "size":{
                "width":100,
                "height":25},
              "limbo":true},
            "adaptiveStyles":{
              "a":{
                "location":{
                  "x":256,
                  "y":420},
                "size":{
                  "width":64,
                  "height":60},
                "limbo":false}},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 更多",
                        "target":{
                          "targetType":"page",
                          "url":"更多.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true}]}},
    "95d57cbcfde44948b7548a4f84555e79":{
      "packageId":"95d57cbcfde44948b7548a4f84555e79",
      "type":"Axure:Master",
      "name":"上导航栏",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
        "a":{
}},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"3a8352b0bdb94ce9a3089c99ad30d525",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "size":{
                "width":200,
                "height":100},
              "limbo":true},
            "adaptiveStyles":{
              "a":{
                "size":{
                  "width":320,
                  "height":50},
                "limbo":false}},
            "objects":[{
                "id":"5e026ecd19c44faaaf17922e877148fb",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":200,
                    "height":100},
                  "limbo":true},
                "adaptiveStyles":{
                  "a":{
}}}],
            "images":{
              "normal~":"images/主页/u9.png",
              "normal~a":"images/主页/u9_a.png"}},
{
            "id":"daf03b54e1b54a3e931b529609a504e5",
            "label":"",
            "type":"button",
            "styleType":"button",
            "visible":true,
            "style":{
              "location":{
                "x":10,
                "y":12.5},
              "size":{
                "width":100,
                "height":25},
              "limbo":true},
            "adaptiveStyles":{
              "a":{
                "location":{
                  "x":10,
                  "y":14},
                "size":{
                  "width":70,
                  "height":23},
                "limbo":false}},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 选择城市",
                        "target":{
                          "targetType":"page",
                          "url":"选择城市.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true},
{
            "id":"9b46f5ced4cd494bb946afb473a1d17b",
            "label":"",
            "type":"button",
            "styleType":"button",
            "visible":true,
            "style":{
              "location":{
                "x":211,
                "y":13},
              "size":{
                "width":100,
                "height":25},
              "limbo":true},
            "adaptiveStyles":{
              "a":{
                "location":{
                  "x":240,
                  "y":13},
                "size":{
                  "width":71,
                  "height":25},
                "limbo":false}}}]}}},
  "objectPaths":{
    "9587e7045ade48a19d21a8420a1f22b7":{
      "scriptId":"u0",
      "46b38d34c95741f384d5e4d38e3120ee":{
        "scriptId":"u1"},
      "eee4e22156fe41d98e86bfcfbba3e560":{
        "scriptId":"u2"},
      "a219148e8a9a42acb89b27adba3bd693":{
        "scriptId":"u3"},
      "6d76ed98f8af41ef971bb4aeeadd04f1":{
        "scriptId":"u4"},
      "5a6a8b09d0fa44cb996ec710d732c51a":{
        "scriptId":"u5"},
      "c346be56b3b148c394d01867f96020ed":{
        "scriptId":"u6"},
      "bee383944d00498cb4790c08da5a6c34":{
        "scriptId":"u7"}},
    "b5ad8e2a823b46d9bae404629920d49c":{
      "scriptId":"u8",
      "3a8352b0bdb94ce9a3089c99ad30d525":{
        "scriptId":"u9"},
      "5e026ecd19c44faaaf17922e877148fb":{
        "scriptId":"u10"},
      "daf03b54e1b54a3e931b529609a504e5":{
        "scriptId":"u11"},
      "9b46f5ced4cd494bb946afb473a1d17b":{
        "scriptId":"u12"}},
    "bfbfe13e6ed349e488eadfb8635aa266":{
      "scriptId":"u13"},
    "e3ca2c294cf04d80a667d32191105cfb":{
      "scriptId":"u14"},
    "bb5330eccb874a85890b14a84c1ba8c5":{
      "scriptId":"u15"},
    "8c52a29052ac421eb400030749804719":{
      "scriptId":"u16"},
    "41c779c9184e4946856683bb7224bc01":{
      "scriptId":"u17"},
    "48961c2611c049abb830edf188f2d297":{
      "scriptId":"u18"},
    "45dad1698f6b490fb3754ecade2bf852":{
      "scriptId":"u19"},
    "21b195516061480db6d64cd21a92fc73":{
      "scriptId":"u20"},
    "813fe14f82994ddda65c4077da53b7ba":{
      "scriptId":"u21"},
    "d857a6c2ba1144d88e53b2356e814bb7":{
      "scriptId":"u22"},
    "15bab34f387e4d249532f63b0da1dab7":{
      "scriptId":"u23"},
    "0625d5dbd9444402b737decb074bf757":{
      "scriptId":"u24"},
    "fbb0ec9a8d924e15821383f02136b679":{
      "scriptId":"u25"},
    "e9107688314f496b8bf8d7525a807ead":{
      "scriptId":"u26"},
    "baf6c289f8cc486daf3eb4e3f87b66d1":{
      "scriptId":"u27"},
    "76a67abc3c614b4990967d7bbcf26c95":{
      "scriptId":"u28"},
    "4265c6cc7fee46d7b1768ccc89d3af97":{
      "scriptId":"u29"},
    "a26fb5f7d63b48c496d0874b1e153779":{
      "scriptId":"u30"},
    "5f6be6ddf96e4d6aaccf5bbe138ef905":{
      "scriptId":"u31"},
    "3bf8b069216743a6acb6148f02c122df":{
      "scriptId":"u32"},
    "a460c1a386044172836a1b5884d7aa03":{
      "scriptId":"u33"},
    "23cd94f6ac6042ffae5c7bb193ef3ced":{
      "scriptId":"u34"},
    "79fd4d72d80345bcbe184fabe7d01284":{
      "scriptId":"u35"},
    "bc0aa0e119e14b3a8667c8367d477610":{
      "scriptId":"u36"},
    "ad4337d7058f469e971daf87949d4132":{
      "scriptId":"u37"},
    "3a104f57a98d458bab8ae44bdcee13c3":{
      "scriptId":"u38"},
    "b5a30057acbf48d0aef8e224379b2ed8":{
      "scriptId":"u39"},
    "6ab32cd5b91047a9a9d862cc490fedab":{
      "scriptId":"u40"},
    "d392f270c1634b7fb87fb410783f9c44":{
      "scriptId":"u41"},
    "f1ea3560273d4b0eb6fa63efa14c896f":{
      "scriptId":"u42"},
    "99de44e288b04e55b057cdbf1e5060e6":{
      "scriptId":"u43"},
    "1d6b55e10970487484975d5031a6e742":{
      "scriptId":"u44"},
    "a4c7ea560c0e4e43bd9f47a0283b1cf0":{
      "scriptId":"u45"},
    "8bb8529e6ce04cb698977271cf7a5c34":{
      "scriptId":"u46"},
    "f02ae2db0db44d1e8b92c6ac70b8b5b5":{
      "scriptId":"u47"},
    "6cab6f1751c44ba484e2b54686e668c0":{
      "scriptId":"u48"},
    "c3e252c2165943b3af9f05e558dd240e":{
      "scriptId":"u49"},
    "5b2798c69fb845ffa01ab92bac14c979":{
      "scriptId":"u50"}}});