$axure.loadCurrentPage({
  "url":"技师的可用时间选择界面.html",
  "generationDate":new Date(1421557103530.35),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"isLogin"],
  "page":{
    "packageId":"dfaeca51146f42bb8da66772a0984189",
    "type":"Axure:Page",
    "name":"技师的可用时间选择界面",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
      "a":{
}},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"bc00a0d2941d49b39db9b9cece12c9c6",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
            "a":{
}},
          "masterId":"c0462b19eeab412787c3050c808291eb"},
{
          "id":"68e204906e65476e848f9096f98c7e12",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":50},
            "size":{
              "width":320,
              "height":70}},
          "adaptiveStyles":{
            "a":{
}},
          "objects":[{
              "id":"e5514ef1c59747f1aabc8b1dade32bcd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":50},
                "size":{
                  "width":320,
                  "height":70}},
              "adaptiveStyles":{
                "a":{
}}}],
          "images":{
            "normal~":"images/技师展示界面/u28.png"}},
{
          "id":"621f76e844aa433989a855dcde2b5b3f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":134,
              "y":60},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
            "a":{
              "size":{
                "width":53,
                "height":16}}},
          "objects":[{
              "id":"c8a89d0677e34524b1a97c200a5b4fe1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":134,
                  "y":60},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
                "a":{
}}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "normal~a":"resources/images/transparent.gif"}},
{
          "id":"921e177042b241f3950d489e4ca9135f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":120,
              "y":14},
            "size":{
              "width":81,
              "height":23}},
          "adaptiveStyles":{
            "a":{
}},
          "objects":[{
              "id":"8c709ffa219c42b8b68f4f4f66de07f8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":120,
                  "y":14},
                "size":{
                  "width":81,
                  "height":23}},
              "adaptiveStyles":{
                "a":{
}}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6f7d75061b0442558204db43d31fe1c2",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":90},
            "size":{
              "width":80,
              "height":30}},
          "adaptiveStyles":{
            "a":{
}}},
{
          "id":"1c5ca5b1c55348f18f3879abfb5855c2",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":90},
            "size":{
              "width":80,
              "height":30}},
          "adaptiveStyles":{
            "a":{
}}},
{
          "id":"e84b71a00cda4890b966709fe1c02adf",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":160,
              "y":90},
            "size":{
              "width":80,
              "height":30}},
          "adaptiveStyles":{
            "a":{
}}},
{
          "id":"bcc90f5166b14ff896e0930aa4ff034c",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":240,
              "y":90},
            "size":{
              "width":80,
              "height":30}},
          "adaptiveStyles":{
            "a":{
}}},
{
          "id":"14a8766b93084f1887c0238c4c66855c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":120},
            "size":{
              "width":320,
              "height":50}},
          "adaptiveStyles":{
            "a":{
}},
          "objects":[{
              "id":"b1900c285d364d65916bcbf0cc61e356",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":120},
                "size":{
                  "width":320,
                  "height":50}},
              "adaptiveStyles":{
                "a":{
}}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 技师展示界面",
                      "target":{
                        "targetType":"page",
                        "url":"技师展示界面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/主页/u9_a.png"}},
{
          "id":"50af00bba9a64fd38a60dc58280a890b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":170},
            "size":{
              "width":320,
              "height":50}},
          "adaptiveStyles":{
            "a":{
}},
          "objects":[{
              "id":"6698659534134bfda4315fec693f63cd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":170},
                "size":{
                  "width":320,
                  "height":50}},
              "adaptiveStyles":{
                "a":{
}}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 技师展示界面",
                      "target":{
                        "targetType":"page",
                        "url":"技师展示界面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/主页/u9_a.png"}},
{
          "id":"94409a49f66e47ab8fc5a644473982ba",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":220},
            "size":{
              "width":320,
              "height":50}},
          "adaptiveStyles":{
            "a":{
}},
          "objects":[{
              "id":"a33588c47d6845dcb288c0d048136f9d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":220},
                "size":{
                  "width":320,
                  "height":50}},
              "adaptiveStyles":{
                "a":{
}}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 技师展示界面",
                      "target":{
                        "targetType":"page",
                        "url":"技师展示界面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/主页/u9_a.png"}},
{
          "id":"9415689125164c68b1da2b02d6e23888",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":270},
            "size":{
              "width":320,
              "height":50}},
          "adaptiveStyles":{
            "a":{
}},
          "objects":[{
              "id":"d82716b4e68345bba4325ec0a33dd401",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":270},
                "size":{
                  "width":320,
                  "height":50}},
              "adaptiveStyles":{
                "a":{
}}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 技师展示界面",
                      "target":{
                        "targetType":"page",
                        "url":"技师展示界面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/主页/u9_a.png"}},
{
          "id":"cc6b36beaff34d6cacd061f71c73ed7f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":320},
            "size":{
              "width":320,
              "height":50}},
          "adaptiveStyles":{
            "a":{
}},
          "objects":[{
              "id":"d54dd42a79ae48f7aa0afbc3b3ae00d7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":320},
                "size":{
                  "width":320,
                  "height":50}},
              "adaptiveStyles":{
                "a":{
}}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 技师展示界面",
                      "target":{
                        "targetType":"page",
                        "url":"技师展示界面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/主页/u9_a.png"}}]}},
  "masters":{
    "c0462b19eeab412787c3050c808291eb":{
      "packageId":"c0462b19eeab412787c3050c808291eb",
      "type":"Axure:Master",
      "name":"上返回栏",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
        "a":{
}},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"193809c55b604a239711248fd3b92b17",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "size":{
                "width":320,
                "height":480}},
            "adaptiveStyles":{
              "a":{
}},
            "objects":[{
                "id":"fb301888262643c4b28fcad2d5ca7aa9",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":320,
                    "height":480}},
                "adaptiveStyles":{
                  "a":{
}}}],
            "images":{
              "normal~":"images/主页/u1_a.png"}},
{
            "id":"3a8352b0bdb94ce9a3089c99ad30d525",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "size":{
                "width":200,
                "height":100},
              "limbo":true},
            "adaptiveStyles":{
              "a":{
                "size":{
                  "width":320,
                  "height":50},
                "limbo":false}},
            "objects":[{
                "id":"5e026ecd19c44faaaf17922e877148fb",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":200,
                    "height":100},
                  "limbo":true},
                "adaptiveStyles":{
                  "a":{
}}}],
            "images":{
              "normal~":"images/主页/u9.png",
              "normal~a":"images/主页/u9_a.png"}},
{
            "id":"9b46f5ced4cd494bb946afb473a1d17b",
            "label":"",
            "type":"button",
            "styleType":"button",
            "visible":true,
            "style":{
              "location":{
                "x":211,
                "y":13},
              "size":{
                "width":100,
                "height":25},
              "limbo":true},
            "adaptiveStyles":{
              "a":{
                "location":{
                  "x":10,
                  "y":12.5},
                "size":{
                  "width":71,
                  "height":25},
                "limbo":false}},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 返回",
                        "target":{
                          "targetType":"backUrl",
                          "includeVariables":false},
                        "linkType":"current"}]}]}},
            "tabbable":true}]}}},
  "objectPaths":{
    "bc00a0d2941d49b39db9b9cece12c9c6":{
      "scriptId":"u0",
      "193809c55b604a239711248fd3b92b17":{
        "scriptId":"u1"},
      "fb301888262643c4b28fcad2d5ca7aa9":{
        "scriptId":"u2"},
      "3a8352b0bdb94ce9a3089c99ad30d525":{
        "scriptId":"u3"},
      "5e026ecd19c44faaaf17922e877148fb":{
        "scriptId":"u4"},
      "9b46f5ced4cd494bb946afb473a1d17b":{
        "scriptId":"u5"}},
    "68e204906e65476e848f9096f98c7e12":{
      "scriptId":"u6"},
    "e5514ef1c59747f1aabc8b1dade32bcd":{
      "scriptId":"u7"},
    "621f76e844aa433989a855dcde2b5b3f":{
      "scriptId":"u8"},
    "c8a89d0677e34524b1a97c200a5b4fe1":{
      "scriptId":"u9"},
    "921e177042b241f3950d489e4ca9135f":{
      "scriptId":"u10"},
    "8c709ffa219c42b8b68f4f4f66de07f8":{
      "scriptId":"u11"},
    "6f7d75061b0442558204db43d31fe1c2":{
      "scriptId":"u12"},
    "1c5ca5b1c55348f18f3879abfb5855c2":{
      "scriptId":"u13"},
    "e84b71a00cda4890b966709fe1c02adf":{
      "scriptId":"u14"},
    "bcc90f5166b14ff896e0930aa4ff034c":{
      "scriptId":"u15"},
    "14a8766b93084f1887c0238c4c66855c":{
      "scriptId":"u16"},
    "b1900c285d364d65916bcbf0cc61e356":{
      "scriptId":"u17"},
    "50af00bba9a64fd38a60dc58280a890b":{
      "scriptId":"u18"},
    "6698659534134bfda4315fec693f63cd":{
      "scriptId":"u19"},
    "94409a49f66e47ab8fc5a644473982ba":{
      "scriptId":"u20"},
    "a33588c47d6845dcb288c0d048136f9d":{
      "scriptId":"u21"},
    "9415689125164c68b1da2b02d6e23888":{
      "scriptId":"u22"},
    "d82716b4e68345bba4325ec0a33dd401":{
      "scriptId":"u23"},
    "cc6b36beaff34d6cacd061f71c73ed7f":{
      "scriptId":"u24"},
    "d54dd42a79ae48f7aa0afbc3b3ae00d7":{
      "scriptId":"u25"}}});