$axure.loadCurrentPage({
  "url":"单个流程介绍.html",
  "generationDate":new Date(1421169787617.56),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"isLogin"],
  "page":{
    "packageId":"4a63f8ccbf75408dac4b74b350cb88c4",
    "type":"Axure:Page",
    "name":"单个流程介绍",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
      "a":{
}},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"66cc956b91dc4926b4e5a58086091f5c",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
            "a":{
}},
          "masterId":"c0462b19eeab412787c3050c808291eb"},
{
          "id":"5a8fdfd0baad458aaa886c7d010d8378",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":120,
              "y":14},
            "size":{
              "width":81,
              "height":23}},
          "adaptiveStyles":{
            "a":{
}},
          "objects":[{
              "id":"7c877b184930409fa670d4209bee5e89",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":120,
                  "y":14},
                "size":{
                  "width":81,
                  "height":23}},
              "adaptiveStyles":{
                "a":{
}}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a7dc838ed7ef471e870d9b9d8cc64be8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":70},
            "size":{
              "width":260,
              "height":200}},
          "adaptiveStyles":{
            "a":{
}},
          "objects":[{
              "id":"c56870b22cdf4f9f87892dd41084d25d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":70},
                "size":{
                  "width":260,
                  "height":200}},
              "adaptiveStyles":{
                "a":{
}}}],
          "images":{
            "normal~":"images/单个流程介绍/u6.png"}},
{
          "id":"787d1c6d972041238515e852a9390e92",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":294},
            "size":{
              "width":79,
              "height":16}},
          "adaptiveStyles":{
            "a":{
              "size":{
                "width":79,
                "height":16}}},
          "objects":[{
              "id":"e30fc335eea8472aa54a947f1db23123",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":294},
                "size":{
                  "width":79,
                  "height":16}},
              "adaptiveStyles":{
                "a":{
}}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "normal~a":"resources/images/transparent.gif"}},
{
          "id":"abe725d36dd148a1a3fe384a2965238d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":350},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
            "a":{
              "size":{
                "width":53,
                "height":16}}},
          "objects":[{
              "id":"373b426eed6b475fb90b22004680dbb9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":350},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
                "a":{
}}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "normal~a":"resources/images/transparent.gif"}},
{
          "id":"768f33047be94dc8a581dda64fbb9fcc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":400},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
            "a":{
              "size":{
                "width":53,
                "height":16}}},
          "objects":[{
              "id":"560468adfcf64de6941b725756872de0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":400},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
                "a":{
}}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "normal~a":"resources/images/transparent.gif"}}]}},
  "masters":{
    "c0462b19eeab412787c3050c808291eb":{
      "packageId":"c0462b19eeab412787c3050c808291eb",
      "type":"Axure:Master",
      "name":"上返回栏",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
        "a":{
}},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"3a8352b0bdb94ce9a3089c99ad30d525",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "size":{
                "width":200,
                "height":100},
              "limbo":true},
            "adaptiveStyles":{
              "a":{
                "size":{
                  "width":320,
                  "height":50},
                "limbo":false}},
            "objects":[{
                "id":"5e026ecd19c44faaaf17922e877148fb",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":200,
                    "height":100},
                  "limbo":true},
                "adaptiveStyles":{
                  "a":{
}}}],
            "images":{
              "normal~":"images/主页/u9.png",
              "normal~a":"images/主页/u9_a.png"}},
{
            "id":"9b46f5ced4cd494bb946afb473a1d17b",
            "label":"",
            "type":"button",
            "styleType":"button",
            "visible":true,
            "style":{
              "location":{
                "x":211,
                "y":13},
              "size":{
                "width":100,
                "height":25},
              "limbo":true},
            "adaptiveStyles":{
              "a":{
                "location":{
                  "x":10,
                  "y":12.5},
                "size":{
                  "width":71,
                  "height":25},
                "limbo":false}},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 返回",
                        "target":{
                          "targetType":"backUrl",
                          "includeVariables":false},
                        "linkType":"current"}]}]}},
            "tabbable":true}]}}},
  "objectPaths":{
    "66cc956b91dc4926b4e5a58086091f5c":{
      "scriptId":"u0",
      "3a8352b0bdb94ce9a3089c99ad30d525":{
        "scriptId":"u1"},
      "5e026ecd19c44faaaf17922e877148fb":{
        "scriptId":"u2"},
      "9b46f5ced4cd494bb946afb473a1d17b":{
        "scriptId":"u3"}},
    "5a8fdfd0baad458aaa886c7d010d8378":{
      "scriptId":"u4"},
    "7c877b184930409fa670d4209bee5e89":{
      "scriptId":"u5"},
    "a7dc838ed7ef471e870d9b9d8cc64be8":{
      "scriptId":"u6"},
    "c56870b22cdf4f9f87892dd41084d25d":{
      "scriptId":"u7"},
    "787d1c6d972041238515e852a9390e92":{
      "scriptId":"u8"},
    "e30fc335eea8472aa54a947f1db23123":{
      "scriptId":"u9"},
    "abe725d36dd148a1a3fe384a2965238d":{
      "scriptId":"u10"},
    "373b426eed6b475fb90b22004680dbb9":{
      "scriptId":"u11"},
    "768f33047be94dc8a581dda64fbb9fcc":{
      "scriptId":"u12"},
    "560468adfcf64de6941b725756872de0":{
      "scriptId":"u13"}}});