$axure.loadCurrentPage({
  "url":"拨打电话.html",
  "generationDate":new Date(1421169783264.24),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"isLogin"],
  "page":{
    "packageId":"e315cd31d4ac460380a4784d2dfe545b",
    "type":"Axure:Page",
    "name":"拨打电话",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
      "a":{
}},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"406ec3fe115a48d18e824bbbbf1f7440",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":180},
            "size":{
              "width":200,
              "height":100},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
              "limbo":false}},
          "objects":[{
              "id":"716656a7bc6248af8ef5b6eaa29ed4e9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":180},
                "size":{
                  "width":200,
                  "height":100},
                "limbo":true},
              "adaptiveStyles":{
                "a":{
}}}],
          "images":{
            "normal~":"images/主页/u9.png",
            "normal~a":"images/主页/u9.png"}},
{
          "id":"418e34d88a754059957d7946146aa04f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":144,
              "y":194},
            "size":{
              "width":105,
              "height":16},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
              "fontSize":"18px",
              "location":{
                "x":88,
                "y":199},
              "size":{
                "width":145,
                "height":21},
              "limbo":false}},
          "objects":[{
              "id":"48e633d95765488999be329ccd917841",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":144,
                  "y":194},
                "size":{
                  "width":105,
                  "height":16},
                "limbo":true},
              "adaptiveStyles":{
                "a":{
}}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "normal~a":"resources/images/transparent.gif"}},
{
          "id":"089c79fbed4949ffac6ae6f300c6109c",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":245},
            "size":{
              "width":100,
              "height":25},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
              "location":{
                "x":80,
                "y":235},
              "size":{
                "width":70,
                "height":25},
              "limbo":false}},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"},
{
                      "action":"closeCurrent",
                      "description":"关闭当前窗口"}]}]}},
          "tabbable":true},
{
          "id":"67c59b069ccf40c8bd425958b6580357",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":255},
            "size":{
              "width":100,
              "height":25},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
              "location":{
                "x":170,
                "y":235},
              "size":{
                "width":70,
                "height":25},
              "limbo":false}}}]}},
  "masters":{
},
  "objectPaths":{
    "406ec3fe115a48d18e824bbbbf1f7440":{
      "scriptId":"u0"},
    "716656a7bc6248af8ef5b6eaa29ed4e9":{
      "scriptId":"u1"},
    "418e34d88a754059957d7946146aa04f":{
      "scriptId":"u2"},
    "48e633d95765488999be329ccd917841":{
      "scriptId":"u3"},
    "089c79fbed4949ffac6ae6f300c6109c":{
      "scriptId":"u4"},
    "67c59b069ccf40c8bd425958b6580357":{
      "scriptId":"u5"}}});