$axure.loadCurrentPage({
  "url":"我的.html",
  "generationDate":new Date(1421557096962.73),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"isLogin"],
  "page":{
    "packageId":"08ffaec5ee2d4262acb0b1ed9455890c",
    "type":"Axure:Page",
    "name":"我的",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
      "a":{
}},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"eda8ee8b59c34ab1b29c67bbad663d1a",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "limbo":true},
          "adaptiveStyles":{
            "a":{
              "limbo":false}},
          "masterId":"e423deecdca540d69784293e6582ba81"},
{
          "id":"c2157d7c785241d489901cbe921e59f3",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "limbo":true},
          "adaptiveStyles":{
            "a":{
              "limbo":false}},
          "masterId":"95d57cbcfde44948b7548a4f84555e79"},
{
          "id":"acd67f364f014cf189fc451dbeb1a2b7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":144,
              "y":17},
            "size":{
              "width":53,
              "height":16},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
              "fontSize":"20px",
              "location":{
                "x":120,
                "y":14},
              "size":{
                "width":81,
                "height":23},
              "limbo":false}},
          "objects":[{
              "id":"9b647120646c4016bfa52ce59c080e45",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":144,
                  "y":17},
                "size":{
                  "width":53,
                  "height":16},
                "limbo":true},
              "adaptiveStyles":{
                "a":{
}}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "normal~a":"resources/images/transparent.gif"}},
{
          "id":"90424ecd72c54de7b9efab1d69a8ed7f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":50},
            "size":{
              "width":200,
              "height":100},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
              "size":{
                "width":320,
                "height":110},
              "limbo":false}},
          "objects":[{
              "id":"58d36597a19441549033f29461ffe037",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":50},
                "size":{
                  "width":200,
                  "height":100},
                "limbo":true},
              "adaptiveStyles":{
                "a":{
}}}],
          "images":{
            "normal~":"images/主页/u9.png",
            "normal~a":"images/我的/u15_a.png"}},
{
          "id":"a27787977ed8449aa91150708469762b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":70},
            "size":{
              "width":50,
              "height":50},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
              "size":{
                "width":70,
                "height":70},
              "limbo":false}},
          "objects":[{
              "id":"e925d8641d904e00bf510e2b5c7c7c08",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":70},
                "size":{
                  "width":50,
                  "height":50},
                "limbo":true},
              "adaptiveStyles":{
                "a":{
}}}],
          "images":{
            "normal~":"images/我的/u17.png",
            "normal~a":"images/我的/u17_a.png"}},
{
          "id":"394c18b899e1415ebc34fec732699f39",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":120,
              "y":70},
            "size":{
              "width":53,
              "height":16},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
              "size":{
                "width":53,
                "height":16},
              "limbo":false}},
          "objects":[{
              "id":"1d3101d5b88e48c3a882bced7f1f6d6b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":120,
                  "y":70},
                "size":{
                  "width":53,
                  "height":16},
                "limbo":true},
              "adaptiveStyles":{
                "a":{
}}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "normal~a":"resources/images/transparent.gif"}},
{
          "id":"1758beca3e374998abe3be5cadccac70",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":120,
              "y":110},
            "size":{
              "width":53,
              "height":16},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
              "location":{
                "x":120,
                "y":96},
              "size":{
                "width":53,
                "height":16},
              "limbo":false}},
          "objects":[{
              "id":"61537509d27b4dc19940b8d5664e0b5b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":120,
                  "y":110},
                "size":{
                  "width":53,
                  "height":16},
                "limbo":true},
              "adaptiveStyles":{
                "a":{
}}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "normal~a":"resources/images/transparent.gif"}},
{
          "id":"4aada5e592d542439a64a7b46b8bc5a3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":120,
              "y":124},
            "size":{
              "width":53,
              "height":16},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
              "size":{
                "width":53,
                "height":16},
              "limbo":false}},
          "objects":[{
              "id":"157323ac9a894a79b5409a2499d1fc9c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":120,
                  "y":124},
                "size":{
                  "width":53,
                  "height":16},
                "limbo":true},
              "adaptiveStyles":{
                "a":{
}}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "normal~a":"resources/images/transparent.gif"}},
{
          "id":"4b7ce84c11a1443c9933ee76bfb0da5d",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":240,
              "y":87},
            "size":{
              "width":100,
              "height":25},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
              "location":{
                "x":250,
                "y":83.5},
              "size":{
                "width":60,
                "height":43},
              "limbo":false}}},
{
          "id":"ff7facf9ab6446ce991af2b4da1f4b8a",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":70},
            "size":{
              "width":10,
              "height":10},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
              "location":{
                "x":0,
                "y":180},
              "limbo":false}},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"f6d12b74f582428d8bbdcd0be9f6ccaa",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"c4399b0816fb400abf4c55dc05c49e9a",
                  "label":"",
                  "parentDynamicPanel":"ff7facf9ab6446ce991af2b4da1f4b8a",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":200,
                      "height":100},
                    "limbo":true},
                  "adaptiveStyles":{
                    "a":{
                      "horizontalAlignment":"left",
                      "size":{
                        "width":320,
                        "height":40},
                      "limbo":false}},
                  "objects":[{
                      "id":"31317407e91e4720b35764b223e5e996",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ff7facf9ab6446ce991af2b4da1f4b8a",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":200,
                          "height":100},
                        "limbo":true},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"images/主页/u9.png",
                    "normal~a":"images/订单/u15_a.png"}},
{
                  "id":"0ba11f00547f4a22833174604e14b6d5",
                  "label":"",
                  "parentDynamicPanel":"ff7facf9ab6446ce991af2b4da1f4b8a",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":210,
                      "y":5},
                    "size":{
                      "width":100,
                      "height":30},
                    "limbo":true,
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
                    "a":{
                      "location":{
                        "x":270,
                        "y":8},
                      "size":{
                        "width":30,
                        "height":25},
                      "limbo":false,
                      "borderWidth":"-1",
                      "linePattern":"none"}},
                  "objects":[{
                      "id":"0fcde0c4c56e475d82ae9e2a3727e64f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ff7facf9ab6446ce991af2b4da1f4b8a",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":210,
                          "y":5},
                        "size":{
                          "width":100,
                          "height":30},
                        "limbo":true,
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"images/我的/u29.png",
                    "normal~a":"images/我的/u29_a.png"}}]}]},
{
          "id":"0f2f6ebcfa584050a0fdcd38ba201053",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":190},
            "size":{
              "width":10,
              "height":10},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
              "location":{
                "x":0,
                "y":220},
              "limbo":false}},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"b9720428fc62419c8e0ebc36096fed95",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"08649a4b8a1a48d1849069231010b7b0",
                  "label":"",
                  "parentDynamicPanel":"0f2f6ebcfa584050a0fdcd38ba201053",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":200,
                      "height":100},
                    "limbo":true},
                  "adaptiveStyles":{
                    "a":{
                      "horizontalAlignment":"left",
                      "size":{
                        "width":320,
                        "height":40},
                      "limbo":false}},
                  "objects":[{
                      "id":"474169634f2c4f70986279b27846cd62",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0f2f6ebcfa584050a0fdcd38ba201053",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":200,
                          "height":100},
                        "limbo":true},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"images/主页/u9.png",
                    "normal~a":"images/订单/u15_a.png"}},
{
                  "id":"119aca57174846318cba94d3303b0f89",
                  "label":"",
                  "parentDynamicPanel":"0f2f6ebcfa584050a0fdcd38ba201053",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":210,
                      "y":5},
                    "size":{
                      "width":100,
                      "height":30},
                    "limbo":true,
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
                    "a":{
                      "location":{
                        "x":270,
                        "y":8},
                      "size":{
                        "width":30,
                        "height":25},
                      "limbo":false,
                      "borderWidth":"-1",
                      "linePattern":"none"}},
                  "objects":[{
                      "id":"b6d675f6355c47f5954a9d3c74c7b4a8",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0f2f6ebcfa584050a0fdcd38ba201053",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":210,
                          "y":5},
                        "size":{
                          "width":100,
                          "height":30},
                        "limbo":true,
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"images/我的/u29.png",
                    "normal~a":"images/我的/u29_a.png"}}]}]},
{
          "id":"2411bdfbb6864264bd4c7bbd57f927ee",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":200},
            "size":{
              "width":10,
              "height":10},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
              "location":{
                "x":0,
                "y":260},
              "limbo":false}},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 常用地址",
                      "target":{
                        "targetType":"page",
                        "url":"常用地址.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"2fc12acd1fea40aca9ae02899abf382c",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"8a2e912d5d7a4e3389f7bb37c404416c",
                  "label":"",
                  "parentDynamicPanel":"2411bdfbb6864264bd4c7bbd57f927ee",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":200,
                      "height":100},
                    "limbo":true},
                  "adaptiveStyles":{
                    "a":{
                      "horizontalAlignment":"left",
                      "size":{
                        "width":320,
                        "height":40},
                      "limbo":false}},
                  "objects":[{
                      "id":"2fc8a22157be418f9b179bd89198c607",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2411bdfbb6864264bd4c7bbd57f927ee",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":200,
                          "height":100},
                        "limbo":true},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"images/主页/u9.png",
                    "normal~a":"images/订单/u15_a.png"}},
{
                  "id":"24dd7d90a902460183a570b14b0a308c",
                  "label":"",
                  "parentDynamicPanel":"2411bdfbb6864264bd4c7bbd57f927ee",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":210,
                      "y":5},
                    "size":{
                      "width":100,
                      "height":30},
                    "limbo":true,
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
                    "a":{
                      "location":{
                        "x":270,
                        "y":8},
                      "size":{
                        "width":30,
                        "height":25},
                      "limbo":false,
                      "borderWidth":"-1",
                      "linePattern":"none"}},
                  "objects":[{
                      "id":"b0ce4bce622640b38f04edb2d0ed2bc0",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2411bdfbb6864264bd4c7bbd57f927ee",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":210,
                          "y":5},
                        "size":{
                          "width":100,
                          "height":30},
                        "limbo":true,
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"images/我的/u29.png",
                    "normal~a":"images/我的/u29_a.png"}}]}]},
{
          "id":"48ce860920da45bf89fc44cec77a4c93",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":360,
              "y":96},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
            "a":{
}},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 登录界面",
                      "target":{
                        "targetType":"page",
                        "url":"登录界面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"70bdb859298449dea0e4cf9c23afd6ff",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":360,
              "y":70},
            "size":{
              "width":157,
              "height":16}},
          "adaptiveStyles":{
            "a":{
              "size":{
                "width":157,
                "height":16}}},
          "objects":[{
              "id":"ca383af15c70461fb436ae58fb5b95d3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":360,
                  "y":70},
                "size":{
                  "width":157,
                  "height":16}},
              "adaptiveStyles":{
                "a":{
}}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "normal~a":"resources/images/transparent.gif"}}]}},
  "masters":{
    "e423deecdca540d69784293e6582ba81":{
      "packageId":"e423deecdca540d69784293e6582ba81",
      "type":"Axure:Master",
      "name":"下导航栏",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
        "a":{
}},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"46b38d34c95741f384d5e4d38e3120ee",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":0,
                "y":420},
              "size":{
                "width":320,
                "height":60}},
            "adaptiveStyles":{
              "a":{
                "location":{
                  "x":0,
                  "y":0},
                "size":{
                  "width":320,
                  "height":480}}},
            "objects":[{
                "id":"eee4e22156fe41d98e86bfcfbba3e560",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":0,
                    "y":420},
                  "size":{
                    "width":320,
                    "height":60}},
                "adaptiveStyles":{
                  "a":{
}}}],
            "images":{
              "normal~":"images/主页/u1.png",
              "normal~a":"images/主页/u1_a.png"}},
{
            "id":"a219148e8a9a42acb89b27adba3bd693",
            "label":"",
            "type":"button",
            "styleType":"button",
            "visible":true,
            "style":{
              "location":{
                "x":0,
                "y":420},
              "size":{
                "width":100,
                "height":25},
              "limbo":true},
            "adaptiveStyles":{
              "a":{
                "size":{
                  "width":64,
                  "height":60},
                "limbo":false}},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 主页",
                        "target":{
                          "targetType":"page",
                          "url":"主页.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true},
{
            "id":"6d76ed98f8af41ef971bb4aeeadd04f1",
            "label":"",
            "type":"button",
            "styleType":"button",
            "visible":true,
            "style":{
              "location":{
                "x":10,
                "y":430},
              "size":{
                "width":100,
                "height":25},
              "limbo":true},
            "adaptiveStyles":{
              "a":{
                "location":{
                  "x":64,
                  "y":420},
                "size":{
                  "width":64,
                  "height":60},
                "limbo":false}},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 订单",
                        "target":{
                          "targetType":"page",
                          "url":"订单.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true},
{
            "id":"5a6a8b09d0fa44cb996ec710d732c51a",
            "label":"",
            "type":"button",
            "styleType":"button",
            "visible":true,
            "style":{
              "location":{
                "x":20,
                "y":440},
              "size":{
                "width":100,
                "height":25},
              "limbo":true},
            "adaptiveStyles":{
              "a":{
                "location":{
                  "x":128,
                  "y":420},
                "size":{
                  "width":64,
                  "height":60},
                "limbo":false}},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 我的",
                        "target":{
                          "targetType":"page",
                          "url":"我的.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true},
{
            "id":"c346be56b3b148c394d01867f96020ed",
            "label":"",
            "type":"button",
            "styleType":"button",
            "visible":true,
            "style":{
              "location":{
                "x":30,
                "y":450},
              "size":{
                "width":100,
                "height":25},
              "limbo":true},
            "adaptiveStyles":{
              "a":{
                "location":{
                  "x":192,
                  "y":420},
                "size":{
                  "width":64,
                  "height":60},
                "limbo":false}},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 生活",
                        "target":{
                          "targetType":"page",
                          "url":"生活.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true},
{
            "id":"bee383944d00498cb4790c08da5a6c34",
            "label":"",
            "type":"button",
            "styleType":"button",
            "visible":true,
            "style":{
              "location":{
                "x":40,
                "y":460},
              "size":{
                "width":100,
                "height":25},
              "limbo":true},
            "adaptiveStyles":{
              "a":{
                "location":{
                  "x":256,
                  "y":420},
                "size":{
                  "width":64,
                  "height":60},
                "limbo":false}},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 更多",
                        "target":{
                          "targetType":"page",
                          "url":"更多.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true}]}},
    "95d57cbcfde44948b7548a4f84555e79":{
      "packageId":"95d57cbcfde44948b7548a4f84555e79",
      "type":"Axure:Master",
      "name":"上导航栏",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
        "a":{
}},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"3a8352b0bdb94ce9a3089c99ad30d525",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "size":{
                "width":200,
                "height":100},
              "limbo":true},
            "adaptiveStyles":{
              "a":{
                "size":{
                  "width":320,
                  "height":50},
                "limbo":false}},
            "objects":[{
                "id":"5e026ecd19c44faaaf17922e877148fb",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":200,
                    "height":100},
                  "limbo":true},
                "adaptiveStyles":{
                  "a":{
}}}],
            "images":{
              "normal~":"images/主页/u9.png",
              "normal~a":"images/主页/u9_a.png"}},
{
            "id":"daf03b54e1b54a3e931b529609a504e5",
            "label":"",
            "type":"button",
            "styleType":"button",
            "visible":true,
            "style":{
              "location":{
                "x":10,
                "y":12.5},
              "size":{
                "width":100,
                "height":25},
              "limbo":true},
            "adaptiveStyles":{
              "a":{
                "location":{
                  "x":10,
                  "y":14},
                "size":{
                  "width":70,
                  "height":23},
                "limbo":false}},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 选择城市",
                        "target":{
                          "targetType":"page",
                          "url":"选择城市.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true},
{
            "id":"9b46f5ced4cd494bb946afb473a1d17b",
            "label":"",
            "type":"button",
            "styleType":"button",
            "visible":true,
            "style":{
              "location":{
                "x":211,
                "y":13},
              "size":{
                "width":100,
                "height":25},
              "limbo":true},
            "adaptiveStyles":{
              "a":{
                "location":{
                  "x":240,
                  "y":13},
                "size":{
                  "width":71,
                  "height":25},
                "limbo":false}}}]}}},
  "objectPaths":{
    "eda8ee8b59c34ab1b29c67bbad663d1a":{
      "scriptId":"u0",
      "46b38d34c95741f384d5e4d38e3120ee":{
        "scriptId":"u1"},
      "eee4e22156fe41d98e86bfcfbba3e560":{
        "scriptId":"u2"},
      "a219148e8a9a42acb89b27adba3bd693":{
        "scriptId":"u3"},
      "6d76ed98f8af41ef971bb4aeeadd04f1":{
        "scriptId":"u4"},
      "5a6a8b09d0fa44cb996ec710d732c51a":{
        "scriptId":"u5"},
      "c346be56b3b148c394d01867f96020ed":{
        "scriptId":"u6"},
      "bee383944d00498cb4790c08da5a6c34":{
        "scriptId":"u7"}},
    "c2157d7c785241d489901cbe921e59f3":{
      "scriptId":"u8",
      "3a8352b0bdb94ce9a3089c99ad30d525":{
        "scriptId":"u9"},
      "5e026ecd19c44faaaf17922e877148fb":{
        "scriptId":"u10"},
      "daf03b54e1b54a3e931b529609a504e5":{
        "scriptId":"u11"},
      "9b46f5ced4cd494bb946afb473a1d17b":{
        "scriptId":"u12"}},
    "acd67f364f014cf189fc451dbeb1a2b7":{
      "scriptId":"u13"},
    "9b647120646c4016bfa52ce59c080e45":{
      "scriptId":"u14"},
    "90424ecd72c54de7b9efab1d69a8ed7f":{
      "scriptId":"u15"},
    "58d36597a19441549033f29461ffe037":{
      "scriptId":"u16"},
    "a27787977ed8449aa91150708469762b":{
      "scriptId":"u17"},
    "e925d8641d904e00bf510e2b5c7c7c08":{
      "scriptId":"u18"},
    "394c18b899e1415ebc34fec732699f39":{
      "scriptId":"u19"},
    "1d3101d5b88e48c3a882bced7f1f6d6b":{
      "scriptId":"u20"},
    "1758beca3e374998abe3be5cadccac70":{
      "scriptId":"u21"},
    "61537509d27b4dc19940b8d5664e0b5b":{
      "scriptId":"u22"},
    "4aada5e592d542439a64a7b46b8bc5a3":{
      "scriptId":"u23"},
    "157323ac9a894a79b5409a2499d1fc9c":{
      "scriptId":"u24"},
    "4b7ce84c11a1443c9933ee76bfb0da5d":{
      "scriptId":"u25"},
    "ff7facf9ab6446ce991af2b4da1f4b8a":{
      "scriptId":"u26"},
    "c4399b0816fb400abf4c55dc05c49e9a":{
      "scriptId":"u27"},
    "31317407e91e4720b35764b223e5e996":{
      "scriptId":"u28"},
    "0ba11f00547f4a22833174604e14b6d5":{
      "scriptId":"u29"},
    "0fcde0c4c56e475d82ae9e2a3727e64f":{
      "scriptId":"u30"},
    "0f2f6ebcfa584050a0fdcd38ba201053":{
      "scriptId":"u31"},
    "08649a4b8a1a48d1849069231010b7b0":{
      "scriptId":"u32"},
    "474169634f2c4f70986279b27846cd62":{
      "scriptId":"u33"},
    "119aca57174846318cba94d3303b0f89":{
      "scriptId":"u34"},
    "b6d675f6355c47f5954a9d3c74c7b4a8":{
      "scriptId":"u35"},
    "2411bdfbb6864264bd4c7bbd57f927ee":{
      "scriptId":"u36"},
    "8a2e912d5d7a4e3389f7bb37c404416c":{
      "scriptId":"u37"},
    "2fc8a22157be418f9b179bd89198c607":{
      "scriptId":"u38"},
    "24dd7d90a902460183a570b14b0a308c":{
      "scriptId":"u39"},
    "b0ce4bce622640b38f04edb2d0ed2bc0":{
      "scriptId":"u40"},
    "48ce860920da45bf89fc44cec77a4c93":{
      "scriptId":"u41"},
    "70bdb859298449dea0e4cf9c23afd6ff":{
      "scriptId":"u42"},
    "ca383af15c70461fb436ae58fb5b95d3":{
      "scriptId":"u43"}}});