$axure.loadCurrentPage({
  "url":"技师浏览.html",
  "generationDate":new Date(1421557098565.9),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"isLogin"],
  "page":{
    "packageId":"def945ff1b5147b58fd0ac150b11633d",
    "type":"Axure:Page",
    "name":"技师浏览",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
      "a":{
}},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"b4350bb9bd854a3da8d52e859b7c7dc1",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "limbo":true},
          "adaptiveStyles":{
            "a":{
              "limbo":false}},
          "masterId":"c0462b19eeab412787c3050c808291eb"},
{
          "id":"f7116dd89d024c91aaa8fdbf792f106b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":144,
              "y":17},
            "size":{
              "width":40,
              "height":16},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
              "fontSize":"20px",
              "location":{
                "x":130,
                "y":14},
              "size":{
                "width":61,
                "height":23},
              "limbo":false}},
          "objects":[{
              "id":"8c1f51fea32a419bab98b8e31d314a10",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":144,
                  "y":17},
                "size":{
                  "width":40,
                  "height":16},
                "limbo":true},
              "adaptiveStyles":{
                "a":{
}}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "normal~a":"resources/images/transparent.gif"}},
{
          "id":"2a352a2289a044a39584feb86dbab10b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":29,
              "y":62},
            "size":{
              "width":200,
              "height":100},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
              "location":{
                "x":0,
                "y":50},
              "size":{
                "width":320,
                "height":40},
              "limbo":false}},
          "objects":[{
              "id":"0da5aa8c41364316abb4e63e78f5d591",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":29,
                  "y":62},
                "size":{
                  "width":200,
                  "height":100},
                "limbo":true},
              "adaptiveStyles":{
                "a":{
}}}],
          "images":{
            "normal~":"images/主页/u9.png",
            "normal~a":"images/订单/u15_a.png"}},
{
          "id":"c2bb90b1f19143a19eaed025e1fe2f70",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":29,
              "y":70},
            "size":{
              "width":100,
              "height":25},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
              "location":{
                "x":0,
                "y":58},
              "limbo":false}}},
{
          "id":"39aca551d32340ea8fbeb7cc87738b5e",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":139,
              "y":70},
            "size":{
              "width":100,
              "height":25},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
              "location":{
                "x":110,
                "y":58},
              "limbo":false}}},
{
          "id":"f593bff3168542c2912735614a601db8",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":249,
              "y":70},
            "size":{
              "width":100,
              "height":25},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
              "location":{
                "x":220,
                "y":58},
              "limbo":false}}},
{
          "id":"65cb012e2a194bbab6f6d7dc6c88149e",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":100},
            "size":{
              "width":10,
              "height":10},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
              "limbo":false}},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 技师展示界面",
                      "target":{
                        "targetType":"page",
                        "url":"技师展示界面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"1f6c56fc2afe484ea739fd4c2800fa59",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"e4015d9f8c3e4fb6b00d4bccc8a8c87a",
                  "label":"",
                  "parentDynamicPanel":"65cb012e2a194bbab6f6d7dc6c88149e",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":200,
                      "height":100},
                    "limbo":true},
                  "adaptiveStyles":{
                    "a":{
                      "size":{
                        "width":320,
                        "height":90},
                      "limbo":false}},
                  "objects":[{
                      "id":"32cc4cd6e7c5403198eea1caaf9c56fd",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"65cb012e2a194bbab6f6d7dc6c88149e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":200,
                          "height":100},
                        "limbo":true},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"images/主页/u9.png",
                    "normal~a":"images/技师浏览/u14_a.png"}},
{
                  "id":"54a1d5e66b1443799702faa2baeeb60b",
                  "label":"",
                  "parentDynamicPanel":"65cb012e2a194bbab6f6d7dc6c88149e",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":20,
                      "y":20},
                    "size":{
                      "width":50,
                      "height":50},
                    "limbo":true},
                  "adaptiveStyles":{
                    "a":{
                      "location":{
                        "x":20,
                        "y":10},
                      "size":{
                        "width":58,
                        "height":60},
                      "limbo":false}},
                  "objects":[{
                      "id":"882bd9f7198b4b91b6953e5f4b28123e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"65cb012e2a194bbab6f6d7dc6c88149e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":20,
                          "y":20},
                        "size":{
                          "width":50,
                          "height":50},
                        "limbo":true},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"images/我的/u17.png",
                    "normal~a":"images/技师浏览/u16_a.png"}},
{
                  "id":"b004d154c33f4026b7596079e6425ae7",
                  "label":"",
                  "parentDynamicPanel":"65cb012e2a194bbab6f6d7dc6c88149e",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":88,
                      "y":20},
                    "size":{
                      "width":53,
                      "height":16},
                    "limbo":true},
                  "adaptiveStyles":{
                    "a":{
                      "location":{
                        "x":97,
                        "y":10},
                      "size":{
                        "width":53,
                        "height":16},
                      "limbo":false}},
                  "objects":[{
                      "id":"2b318d9a0d28478485ce80982abe2669",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"65cb012e2a194bbab6f6d7dc6c88149e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":88,
                          "y":20},
                        "size":{
                          "width":53,
                          "height":16},
                        "limbo":true},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "normal~a":"resources/images/transparent.gif"}},
{
                  "id":"ca387f517bda466fb292a76dc89ff5cc",
                  "label":"",
                  "parentDynamicPanel":"65cb012e2a194bbab6f6d7dc6c88149e",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":88,
                      "y":54},
                    "size":{
                      "width":53,
                      "height":16},
                    "limbo":true},
                  "adaptiveStyles":{
                    "a":{
                      "location":{
                        "x":97,
                        "y":54},
                      "size":{
                        "width":53,
                        "height":16},
                      "limbo":false}},
                  "objects":[{
                      "id":"ffa2cc24a06f4d81b5ab790c5cadf726",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"65cb012e2a194bbab6f6d7dc6c88149e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":88,
                          "y":54},
                        "size":{
                          "width":53,
                          "height":16},
                        "limbo":true},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "normal~a":"resources/images/transparent.gif"}},
{
                  "id":"ef58a38b2eff4a54946beaa5a0880dc7",
                  "label":"",
                  "parentDynamicPanel":"65cb012e2a194bbab6f6d7dc6c88149e",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":97,
                      "y":32},
                    "size":{
                      "width":53,
                      "height":16},
                    "limbo":true},
                  "adaptiveStyles":{
                    "a":{
                      "size":{
                        "width":53,
                        "height":16},
                      "limbo":false}},
                  "objects":[{
                      "id":"6c29625dd2674cf3843d2d7727023415",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"65cb012e2a194bbab6f6d7dc6c88149e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":97,
                          "y":32},
                        "size":{
                          "width":53,
                          "height":16},
                        "limbo":true},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "normal~a":"resources/images/transparent.gif"}},
{
                  "id":"4894d910d3dc47e9a4af6cd98cb222ec",
                  "label":"",
                  "parentDynamicPanel":"65cb012e2a194bbab6f6d7dc6c88149e",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":254,
                      "y":54},
                    "size":{
                      "width":27,
                      "height":16},
                    "limbo":true},
                  "adaptiveStyles":{
                    "a":{
                      "size":{
                        "width":27,
                        "height":16},
                      "limbo":false}},
                  "objects":[{
                      "id":"cb0dd726064843d7b391f2bba877953d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"65cb012e2a194bbab6f6d7dc6c88149e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":254,
                          "y":54},
                        "size":{
                          "width":27,
                          "height":16},
                        "limbo":true},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "normal~a":"resources/images/transparent.gif"}}]}]},
{
          "id":"a09c0a23cbea4ac1a531314bc9f04921",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":110},
            "size":{
              "width":10,
              "height":10},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
              "location":{
                "x":0,
                "y":190},
              "limbo":false}},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 技师展示界面",
                      "target":{
                        "targetType":"page",
                        "url":"技师展示界面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"39c3c8f53d3742ee9db7945f1bd7fc4e",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"630d84758fb7445ca920996570e50e19",
                  "label":"",
                  "parentDynamicPanel":"a09c0a23cbea4ac1a531314bc9f04921",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":200,
                      "height":100},
                    "limbo":true},
                  "adaptiveStyles":{
                    "a":{
                      "size":{
                        "width":320,
                        "height":90},
                      "limbo":false}},
                  "objects":[{
                      "id":"8e69126fb99e46e5ae60b9561476fcd2",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"a09c0a23cbea4ac1a531314bc9f04921",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":200,
                          "height":100},
                        "limbo":true},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"images/主页/u9.png",
                    "normal~a":"images/技师浏览/u14_a.png"}},
{
                  "id":"9d8d9928af354ef4960c5723da997322",
                  "label":"",
                  "parentDynamicPanel":"a09c0a23cbea4ac1a531314bc9f04921",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":20,
                      "y":20},
                    "size":{
                      "width":50,
                      "height":50},
                    "limbo":true},
                  "adaptiveStyles":{
                    "a":{
                      "location":{
                        "x":20,
                        "y":10},
                      "size":{
                        "width":58,
                        "height":60},
                      "limbo":false}},
                  "objects":[{
                      "id":"3beb83f6b1034e0eb8705c89e33d5cf9",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"a09c0a23cbea4ac1a531314bc9f04921",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":20,
                          "y":20},
                        "size":{
                          "width":50,
                          "height":50},
                        "limbo":true},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"images/我的/u17.png",
                    "normal~a":"images/技师浏览/u16_a.png"}},
{
                  "id":"381f90d9a9964187b98c34bcc417440d",
                  "label":"",
                  "parentDynamicPanel":"a09c0a23cbea4ac1a531314bc9f04921",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":88,
                      "y":20},
                    "size":{
                      "width":53,
                      "height":16},
                    "limbo":true},
                  "adaptiveStyles":{
                    "a":{
                      "location":{
                        "x":97,
                        "y":10},
                      "size":{
                        "width":53,
                        "height":16},
                      "limbo":false}},
                  "objects":[{
                      "id":"2e5375e54a634f74823106d2e872d44f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"a09c0a23cbea4ac1a531314bc9f04921",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":88,
                          "y":20},
                        "size":{
                          "width":53,
                          "height":16},
                        "limbo":true},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "normal~a":"resources/images/transparent.gif"}},
{
                  "id":"2dae660b00954d56b51d5e89f0a4c7a1",
                  "label":"",
                  "parentDynamicPanel":"a09c0a23cbea4ac1a531314bc9f04921",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":88,
                      "y":54},
                    "size":{
                      "width":53,
                      "height":16},
                    "limbo":true},
                  "adaptiveStyles":{
                    "a":{
                      "location":{
                        "x":97,
                        "y":54},
                      "size":{
                        "width":53,
                        "height":16},
                      "limbo":false}},
                  "objects":[{
                      "id":"c9f0c2bc5fe24a72af296226372b308f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"a09c0a23cbea4ac1a531314bc9f04921",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":88,
                          "y":54},
                        "size":{
                          "width":53,
                          "height":16},
                        "limbo":true},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "normal~a":"resources/images/transparent.gif"}},
{
                  "id":"322fd8100aa44171a0c710f27815a719",
                  "label":"",
                  "parentDynamicPanel":"a09c0a23cbea4ac1a531314bc9f04921",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":97,
                      "y":32},
                    "size":{
                      "width":53,
                      "height":16},
                    "limbo":true},
                  "adaptiveStyles":{
                    "a":{
                      "size":{
                        "width":53,
                        "height":16},
                      "limbo":false}},
                  "objects":[{
                      "id":"2a97b8e9404342189724a9dba2c95ac6",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"a09c0a23cbea4ac1a531314bc9f04921",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":97,
                          "y":32},
                        "size":{
                          "width":53,
                          "height":16},
                        "limbo":true},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "normal~a":"resources/images/transparent.gif"}},
{
                  "id":"fdd299a7cf604b46987d8d276b3bd18a",
                  "label":"",
                  "parentDynamicPanel":"a09c0a23cbea4ac1a531314bc9f04921",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":254,
                      "y":54},
                    "size":{
                      "width":27,
                      "height":16},
                    "limbo":true},
                  "adaptiveStyles":{
                    "a":{
                      "size":{
                        "width":27,
                        "height":16},
                      "limbo":false}},
                  "objects":[{
                      "id":"8925c313c3e345399f5a510e72120963",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"a09c0a23cbea4ac1a531314bc9f04921",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":254,
                          "y":54},
                        "size":{
                          "width":27,
                          "height":16},
                        "limbo":true},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "normal~a":"resources/images/transparent.gif"}}]}]},
{
          "id":"31ff45ef46174889aac8d865176378f2",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":120},
            "size":{
              "width":10,
              "height":10},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
              "location":{
                "x":0,
                "y":280},
              "limbo":false}},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 技师展示界面",
                      "target":{
                        "targetType":"page",
                        "url":"技师展示界面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"12f7cba477ad457dae911927da70b83b",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"a2314da93a994a24a1c2d0acc56884ce",
                  "label":"",
                  "parentDynamicPanel":"31ff45ef46174889aac8d865176378f2",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":200,
                      "height":100},
                    "limbo":true},
                  "adaptiveStyles":{
                    "a":{
                      "size":{
                        "width":320,
                        "height":90},
                      "limbo":false}},
                  "objects":[{
                      "id":"bd1920c4bafc40a6bca3c463fc93be55",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"31ff45ef46174889aac8d865176378f2",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":200,
                          "height":100},
                        "limbo":true},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"images/主页/u9.png",
                    "normal~a":"images/技师浏览/u14_a.png"}},
{
                  "id":"5cd672043a7240a8b3c21f0f5941aaae",
                  "label":"",
                  "parentDynamicPanel":"31ff45ef46174889aac8d865176378f2",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":20,
                      "y":20},
                    "size":{
                      "width":50,
                      "height":50},
                    "limbo":true},
                  "adaptiveStyles":{
                    "a":{
                      "location":{
                        "x":20,
                        "y":10},
                      "size":{
                        "width":58,
                        "height":60},
                      "limbo":false}},
                  "objects":[{
                      "id":"a65edaf92aa046f18d2442672d54125e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"31ff45ef46174889aac8d865176378f2",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":20,
                          "y":20},
                        "size":{
                          "width":50,
                          "height":50},
                        "limbo":true},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"images/我的/u17.png",
                    "normal~a":"images/技师浏览/u16_a.png"}},
{
                  "id":"7c6961dbf8a944a0bcf1c2fd24be655f",
                  "label":"",
                  "parentDynamicPanel":"31ff45ef46174889aac8d865176378f2",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":88,
                      "y":20},
                    "size":{
                      "width":53,
                      "height":16},
                    "limbo":true},
                  "adaptiveStyles":{
                    "a":{
                      "location":{
                        "x":97,
                        "y":10},
                      "size":{
                        "width":53,
                        "height":16},
                      "limbo":false}},
                  "objects":[{
                      "id":"e96899aa33f74545901dc1c304598018",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"31ff45ef46174889aac8d865176378f2",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":88,
                          "y":20},
                        "size":{
                          "width":53,
                          "height":16},
                        "limbo":true},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "normal~a":"resources/images/transparent.gif"}},
{
                  "id":"6d0ec5d113c441b48802028d9657c87d",
                  "label":"",
                  "parentDynamicPanel":"31ff45ef46174889aac8d865176378f2",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":88,
                      "y":54},
                    "size":{
                      "width":53,
                      "height":16},
                    "limbo":true},
                  "adaptiveStyles":{
                    "a":{
                      "location":{
                        "x":97,
                        "y":54},
                      "size":{
                        "width":53,
                        "height":16},
                      "limbo":false}},
                  "objects":[{
                      "id":"6cf22ecd704c4fee8593aa35f4d33536",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"31ff45ef46174889aac8d865176378f2",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":88,
                          "y":54},
                        "size":{
                          "width":53,
                          "height":16},
                        "limbo":true},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "normal~a":"resources/images/transparent.gif"}},
{
                  "id":"37d514f9fa8c48f984f12031b5edbd8e",
                  "label":"",
                  "parentDynamicPanel":"31ff45ef46174889aac8d865176378f2",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":97,
                      "y":32},
                    "size":{
                      "width":53,
                      "height":16},
                    "limbo":true},
                  "adaptiveStyles":{
                    "a":{
                      "size":{
                        "width":53,
                        "height":16},
                      "limbo":false}},
                  "objects":[{
                      "id":"c7db90f883224c76a3d207f5e60a55ce",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"31ff45ef46174889aac8d865176378f2",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":97,
                          "y":32},
                        "size":{
                          "width":53,
                          "height":16},
                        "limbo":true},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "normal~a":"resources/images/transparent.gif"}},
{
                  "id":"0875bb03968b404c8b3fe95a977131ec",
                  "label":"",
                  "parentDynamicPanel":"31ff45ef46174889aac8d865176378f2",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":254,
                      "y":54},
                    "size":{
                      "width":27,
                      "height":16},
                    "limbo":true},
                  "adaptiveStyles":{
                    "a":{
                      "size":{
                        "width":27,
                        "height":16},
                      "limbo":false}},
                  "objects":[{
                      "id":"a9bf29e1c36c423ab32f470331533055",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"31ff45ef46174889aac8d865176378f2",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":254,
                          "y":54},
                        "size":{
                          "width":27,
                          "height":16},
                        "limbo":true},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "normal~a":"resources/images/transparent.gif"}}]}]},
{
          "id":"3813f5668f2f44b0a6eecac4af98003c",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":130},
            "size":{
              "width":10,
              "height":10},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
              "location":{
                "x":0,
                "y":370},
              "limbo":false}},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 技师展示界面",
                      "target":{
                        "targetType":"page",
                        "url":"技师展示界面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"f979f20631754705924be73169925028",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"756853ab4d2346d8bbc32e23f89d3fdd",
                  "label":"",
                  "parentDynamicPanel":"3813f5668f2f44b0a6eecac4af98003c",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":200,
                      "height":100},
                    "limbo":true},
                  "adaptiveStyles":{
                    "a":{
                      "size":{
                        "width":320,
                        "height":90},
                      "limbo":false}},
                  "objects":[{
                      "id":"90fd0f27fb844c1da1e66f49f17827ba",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"3813f5668f2f44b0a6eecac4af98003c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":200,
                          "height":100},
                        "limbo":true},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"images/主页/u9.png",
                    "normal~a":"images/技师浏览/u14_a.png"}},
{
                  "id":"30ff16f3cf1a43a5b54e4a536f64156b",
                  "label":"",
                  "parentDynamicPanel":"3813f5668f2f44b0a6eecac4af98003c",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":20,
                      "y":20},
                    "size":{
                      "width":50,
                      "height":50},
                    "limbo":true},
                  "adaptiveStyles":{
                    "a":{
                      "location":{
                        "x":20,
                        "y":10},
                      "size":{
                        "width":58,
                        "height":60},
                      "limbo":false}},
                  "objects":[{
                      "id":"7e2d219808f1403ca9f324d3fb07ca12",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"3813f5668f2f44b0a6eecac4af98003c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":20,
                          "y":20},
                        "size":{
                          "width":50,
                          "height":50},
                        "limbo":true},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"images/我的/u17.png",
                    "normal~a":"images/技师浏览/u16_a.png"}},
{
                  "id":"8e0c0383064a4d3997b9ac1c71a9c51a",
                  "label":"",
                  "parentDynamicPanel":"3813f5668f2f44b0a6eecac4af98003c",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":88,
                      "y":20},
                    "size":{
                      "width":53,
                      "height":16},
                    "limbo":true},
                  "adaptiveStyles":{
                    "a":{
                      "location":{
                        "x":97,
                        "y":10},
                      "size":{
                        "width":53,
                        "height":16},
                      "limbo":false}},
                  "objects":[{
                      "id":"a75664b556ae402da6b94aa1b0dbe6f1",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"3813f5668f2f44b0a6eecac4af98003c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":88,
                          "y":20},
                        "size":{
                          "width":53,
                          "height":16},
                        "limbo":true},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "normal~a":"resources/images/transparent.gif"}},
{
                  "id":"b31671a05cbc42c4b10c95944baa82ce",
                  "label":"",
                  "parentDynamicPanel":"3813f5668f2f44b0a6eecac4af98003c",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":88,
                      "y":54},
                    "size":{
                      "width":53,
                      "height":16},
                    "limbo":true},
                  "adaptiveStyles":{
                    "a":{
                      "location":{
                        "x":97,
                        "y":54},
                      "size":{
                        "width":53,
                        "height":16},
                      "limbo":false}},
                  "objects":[{
                      "id":"b26595e367414a3f83878e43cc2834b0",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"3813f5668f2f44b0a6eecac4af98003c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":88,
                          "y":54},
                        "size":{
                          "width":53,
                          "height":16},
                        "limbo":true},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "normal~a":"resources/images/transparent.gif"}},
{
                  "id":"330fe56dedcc45439e1cafeb8d701ff3",
                  "label":"",
                  "parentDynamicPanel":"3813f5668f2f44b0a6eecac4af98003c",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":97,
                      "y":32},
                    "size":{
                      "width":53,
                      "height":16},
                    "limbo":true},
                  "adaptiveStyles":{
                    "a":{
                      "size":{
                        "width":53,
                        "height":16},
                      "limbo":false}},
                  "objects":[{
                      "id":"cc424b5806dc4cfd8d49ea71ed0e5a35",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"3813f5668f2f44b0a6eecac4af98003c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":97,
                          "y":32},
                        "size":{
                          "width":53,
                          "height":16},
                        "limbo":true},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "normal~a":"resources/images/transparent.gif"}},
{
                  "id":"274ca124c6e5448f9ef10427f1dcb6ee",
                  "label":"",
                  "parentDynamicPanel":"3813f5668f2f44b0a6eecac4af98003c",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":254,
                      "y":54},
                    "size":{
                      "width":27,
                      "height":16},
                    "limbo":true},
                  "adaptiveStyles":{
                    "a":{
                      "size":{
                        "width":27,
                        "height":16},
                      "limbo":false}},
                  "objects":[{
                      "id":"3eac29ca7d574e7cb57f962e65ee52d5",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"3813f5668f2f44b0a6eecac4af98003c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":254,
                          "y":54},
                        "size":{
                          "width":27,
                          "height":16},
                        "limbo":true},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "normal~a":"resources/images/transparent.gif"}}]}]}]}},
  "masters":{
    "c0462b19eeab412787c3050c808291eb":{
      "packageId":"c0462b19eeab412787c3050c808291eb",
      "type":"Axure:Master",
      "name":"上返回栏",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
        "a":{
}},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"193809c55b604a239711248fd3b92b17",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "size":{
                "width":320,
                "height":480}},
            "adaptiveStyles":{
              "a":{
}},
            "objects":[{
                "id":"fb301888262643c4b28fcad2d5ca7aa9",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":320,
                    "height":480}},
                "adaptiveStyles":{
                  "a":{
}}}],
            "images":{
              "normal~":"images/主页/u1_a.png"}},
{
            "id":"3a8352b0bdb94ce9a3089c99ad30d525",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "size":{
                "width":200,
                "height":100},
              "limbo":true},
            "adaptiveStyles":{
              "a":{
                "size":{
                  "width":320,
                  "height":50},
                "limbo":false}},
            "objects":[{
                "id":"5e026ecd19c44faaaf17922e877148fb",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":200,
                    "height":100},
                  "limbo":true},
                "adaptiveStyles":{
                  "a":{
}}}],
            "images":{
              "normal~":"images/主页/u9.png",
              "normal~a":"images/主页/u9_a.png"}},
{
            "id":"9b46f5ced4cd494bb946afb473a1d17b",
            "label":"",
            "type":"button",
            "styleType":"button",
            "visible":true,
            "style":{
              "location":{
                "x":211,
                "y":13},
              "size":{
                "width":100,
                "height":25},
              "limbo":true},
            "adaptiveStyles":{
              "a":{
                "location":{
                  "x":10,
                  "y":12.5},
                "size":{
                  "width":71,
                  "height":25},
                "limbo":false}},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 返回",
                        "target":{
                          "targetType":"backUrl",
                          "includeVariables":false},
                        "linkType":"current"}]}]}},
            "tabbable":true}]}}},
  "objectPaths":{
    "b4350bb9bd854a3da8d52e859b7c7dc1":{
      "scriptId":"u0",
      "193809c55b604a239711248fd3b92b17":{
        "scriptId":"u1"},
      "fb301888262643c4b28fcad2d5ca7aa9":{
        "scriptId":"u2"},
      "3a8352b0bdb94ce9a3089c99ad30d525":{
        "scriptId":"u3"},
      "5e026ecd19c44faaaf17922e877148fb":{
        "scriptId":"u4"},
      "9b46f5ced4cd494bb946afb473a1d17b":{
        "scriptId":"u5"}},
    "f7116dd89d024c91aaa8fdbf792f106b":{
      "scriptId":"u6"},
    "8c1f51fea32a419bab98b8e31d314a10":{
      "scriptId":"u7"},
    "2a352a2289a044a39584feb86dbab10b":{
      "scriptId":"u8"},
    "0da5aa8c41364316abb4e63e78f5d591":{
      "scriptId":"u9"},
    "c2bb90b1f19143a19eaed025e1fe2f70":{
      "scriptId":"u10"},
    "39aca551d32340ea8fbeb7cc87738b5e":{
      "scriptId":"u11"},
    "f593bff3168542c2912735614a601db8":{
      "scriptId":"u12"},
    "65cb012e2a194bbab6f6d7dc6c88149e":{
      "scriptId":"u13"},
    "e4015d9f8c3e4fb6b00d4bccc8a8c87a":{
      "scriptId":"u14"},
    "32cc4cd6e7c5403198eea1caaf9c56fd":{
      "scriptId":"u15"},
    "54a1d5e66b1443799702faa2baeeb60b":{
      "scriptId":"u16"},
    "882bd9f7198b4b91b6953e5f4b28123e":{
      "scriptId":"u17"},
    "b004d154c33f4026b7596079e6425ae7":{
      "scriptId":"u18"},
    "2b318d9a0d28478485ce80982abe2669":{
      "scriptId":"u19"},
    "ca387f517bda466fb292a76dc89ff5cc":{
      "scriptId":"u20"},
    "ffa2cc24a06f4d81b5ab790c5cadf726":{
      "scriptId":"u21"},
    "ef58a38b2eff4a54946beaa5a0880dc7":{
      "scriptId":"u22"},
    "6c29625dd2674cf3843d2d7727023415":{
      "scriptId":"u23"},
    "4894d910d3dc47e9a4af6cd98cb222ec":{
      "scriptId":"u24"},
    "cb0dd726064843d7b391f2bba877953d":{
      "scriptId":"u25"},
    "a09c0a23cbea4ac1a531314bc9f04921":{
      "scriptId":"u26"},
    "630d84758fb7445ca920996570e50e19":{
      "scriptId":"u27"},
    "8e69126fb99e46e5ae60b9561476fcd2":{
      "scriptId":"u28"},
    "9d8d9928af354ef4960c5723da997322":{
      "scriptId":"u29"},
    "3beb83f6b1034e0eb8705c89e33d5cf9":{
      "scriptId":"u30"},
    "381f90d9a9964187b98c34bcc417440d":{
      "scriptId":"u31"},
    "2e5375e54a634f74823106d2e872d44f":{
      "scriptId":"u32"},
    "2dae660b00954d56b51d5e89f0a4c7a1":{
      "scriptId":"u33"},
    "c9f0c2bc5fe24a72af296226372b308f":{
      "scriptId":"u34"},
    "322fd8100aa44171a0c710f27815a719":{
      "scriptId":"u35"},
    "2a97b8e9404342189724a9dba2c95ac6":{
      "scriptId":"u36"},
    "fdd299a7cf604b46987d8d276b3bd18a":{
      "scriptId":"u37"},
    "8925c313c3e345399f5a510e72120963":{
      "scriptId":"u38"},
    "31ff45ef46174889aac8d865176378f2":{
      "scriptId":"u39"},
    "a2314da93a994a24a1c2d0acc56884ce":{
      "scriptId":"u40"},
    "bd1920c4bafc40a6bca3c463fc93be55":{
      "scriptId":"u41"},
    "5cd672043a7240a8b3c21f0f5941aaae":{
      "scriptId":"u42"},
    "a65edaf92aa046f18d2442672d54125e":{
      "scriptId":"u43"},
    "7c6961dbf8a944a0bcf1c2fd24be655f":{
      "scriptId":"u44"},
    "e96899aa33f74545901dc1c304598018":{
      "scriptId":"u45"},
    "6d0ec5d113c441b48802028d9657c87d":{
      "scriptId":"u46"},
    "6cf22ecd704c4fee8593aa35f4d33536":{
      "scriptId":"u47"},
    "37d514f9fa8c48f984f12031b5edbd8e":{
      "scriptId":"u48"},
    "c7db90f883224c76a3d207f5e60a55ce":{
      "scriptId":"u49"},
    "0875bb03968b404c8b3fe95a977131ec":{
      "scriptId":"u50"},
    "a9bf29e1c36c423ab32f470331533055":{
      "scriptId":"u51"},
    "3813f5668f2f44b0a6eecac4af98003c":{
      "scriptId":"u52"},
    "756853ab4d2346d8bbc32e23f89d3fdd":{
      "scriptId":"u53"},
    "90fd0f27fb844c1da1e66f49f17827ba":{
      "scriptId":"u54"},
    "30ff16f3cf1a43a5b54e4a536f64156b":{
      "scriptId":"u55"},
    "7e2d219808f1403ca9f324d3fb07ca12":{
      "scriptId":"u56"},
    "8e0c0383064a4d3997b9ac1c71a9c51a":{
      "scriptId":"u57"},
    "a75664b556ae402da6b94aa1b0dbe6f1":{
      "scriptId":"u58"},
    "b31671a05cbc42c4b10c95944baa82ce":{
      "scriptId":"u59"},
    "b26595e367414a3f83878e43cc2834b0":{
      "scriptId":"u60"},
    "330fe56dedcc45439e1cafeb8d701ff3":{
      "scriptId":"u61"},
    "cc424b5806dc4cfd8d49ea71ed0e5a35":{
      "scriptId":"u62"},
    "274ca124c6e5448f9ef10427f1dcb6ee":{
      "scriptId":"u63"},
    "3eac29ca7d574e7cb57f962e65ee52d5":{
      "scriptId":"u64"}}});