$axure.loadCurrentPage({
  "url":"大地址联想.html",
  "generationDate":new Date(1421169785236.41),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"isLogin"],
  "page":{
    "packageId":"39c4d9361c2e4e35b86b76365a650302",
    "type":"Axure:Page",
    "name":"大地址联想",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
      "a":{
}},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"4e7a4d7398014fa796d2a720d4e79d5c",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
            "a":{
}},
          "masterId":"c0462b19eeab412787c3050c808291eb"},
{
          "id":"01d683645d044588b96a49c09bf5fe7f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":120,
              "y":14},
            "size":{
              "width":81,
              "height":23}},
          "adaptiveStyles":{
            "a":{
              "location":{
                "x":120,
                "y":14},
              "size":{
                "width":81,
                "height":23}}},
          "objects":[{
              "id":"40505151038a4a86bf69a3c2e5c13dda",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":120,
                  "y":14},
                "size":{
                  "width":81,
                  "height":23}},
              "adaptiveStyles":{
                "a":{
}}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "normal~a":"resources/images/transparent.gif"}},
{
          "id":"46cb6a5bf9a84d6ebdde66d8161a17d4",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":70},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
            "a":{
}},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"b71ea8f647ce45389c1683f5d2fdefa1",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"ab99601d4baa47eb830c681f26ef6503",
                  "label":"",
                  "parentDynamicPanel":"46cb6a5bf9a84d6ebdde66d8161a17d4",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":270,
                      "height":40}},
                  "adaptiveStyles":{
                    "a":{
}},
                  "objects":[{
                      "id":"2e3b4c91b49d467ab2e310e95eb7fd46",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"46cb6a5bf9a84d6ebdde66d8161a17d4",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":270,
                          "height":40}},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"images/预约界面/u5.png"}},
{
                  "id":"cca414270db2442bbebdeb314eaf6754",
                  "label":"",
                  "parentDynamicPanel":"46cb6a5bf9a84d6ebdde66d8161a17d4",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":10,
                      "y":5},
                    "size":{
                      "width":30,
                      "height":30}},
                  "adaptiveStyles":{
                    "a":{
}},
                  "objects":[{
                      "id":"804cf15d3c71434a972dff15e7ddf7e3",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"46cb6a5bf9a84d6ebdde66d8161a17d4",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":10,
                          "y":5},
                        "size":{
                          "width":30,
                          "height":30}},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"images/预约界面/u7.png"}},
{
                  "id":"97b2f4baa5e147b9b3b240519fc5961f",
                  "label":"",
                  "parentDynamicPanel":"46cb6a5bf9a84d6ebdde66d8161a17d4",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":50,
                      "y":12},
                    "size":{
                      "width":103,
                      "height":16}},
                  "adaptiveStyles":{
                    "a":{
                      "size":{
                        "width":103,
                        "height":16}}},
                  "objects":[{
                      "id":"e7ff702f7e0f4247a51098c0f9e33245",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"46cb6a5bf9a84d6ebdde66d8161a17d4",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":50,
                          "y":12},
                        "size":{
                          "width":103,
                          "height":16}},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "normal~a":"resources/images/transparent.gif"}}]}]}]}},
  "masters":{
    "c0462b19eeab412787c3050c808291eb":{
      "packageId":"c0462b19eeab412787c3050c808291eb",
      "type":"Axure:Master",
      "name":"上返回栏",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
        "a":{
}},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"3a8352b0bdb94ce9a3089c99ad30d525",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "size":{
                "width":200,
                "height":100},
              "limbo":true},
            "adaptiveStyles":{
              "a":{
                "size":{
                  "width":320,
                  "height":50},
                "limbo":false}},
            "objects":[{
                "id":"5e026ecd19c44faaaf17922e877148fb",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":200,
                    "height":100},
                  "limbo":true},
                "adaptiveStyles":{
                  "a":{
}}}],
            "images":{
              "normal~":"images/主页/u9.png",
              "normal~a":"images/主页/u9_a.png"}},
{
            "id":"9b46f5ced4cd494bb946afb473a1d17b",
            "label":"",
            "type":"button",
            "styleType":"button",
            "visible":true,
            "style":{
              "location":{
                "x":211,
                "y":13},
              "size":{
                "width":100,
                "height":25},
              "limbo":true},
            "adaptiveStyles":{
              "a":{
                "location":{
                  "x":10,
                  "y":12.5},
                "size":{
                  "width":71,
                  "height":25},
                "limbo":false}},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 返回",
                        "target":{
                          "targetType":"backUrl",
                          "includeVariables":false},
                        "linkType":"current"}]}]}},
            "tabbable":true}]}}},
  "objectPaths":{
    "4e7a4d7398014fa796d2a720d4e79d5c":{
      "scriptId":"u0",
      "3a8352b0bdb94ce9a3089c99ad30d525":{
        "scriptId":"u1"},
      "5e026ecd19c44faaaf17922e877148fb":{
        "scriptId":"u2"},
      "9b46f5ced4cd494bb946afb473a1d17b":{
        "scriptId":"u3"}},
    "01d683645d044588b96a49c09bf5fe7f":{
      "scriptId":"u4"},
    "40505151038a4a86bf69a3c2e5c13dda":{
      "scriptId":"u5"},
    "46cb6a5bf9a84d6ebdde66d8161a17d4":{
      "scriptId":"u6"},
    "ab99601d4baa47eb830c681f26ef6503":{
      "scriptId":"u7"},
    "2e3b4c91b49d467ab2e310e95eb7fd46":{
      "scriptId":"u8"},
    "cca414270db2442bbebdeb314eaf6754":{
      "scriptId":"u9"},
    "804cf15d3c71434a972dff15e7ddf7e3":{
      "scriptId":"u10"},
    "97b2f4baa5e147b9b3b240519fc5961f":{
      "scriptId":"u11"},
    "e7ff702f7e0f4247a51098c0f9e33245":{
      "scriptId":"u12"}}});