$axure.loadCurrentPage({
  "url":"main_page.html",
  "generationDate":new Date(1420944053142.47),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"3edc26cefaf44ce6b9718c5c5eea7742",
    "type":"Axure:Page",
    "name":"main page",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"center",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
      "a":{
}},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"a4c9832434df42d79d1a32f90fffd4ee",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":200,
              "height":100},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
              "size":{
                "width":320,
                "height":50},
              "limbo":false}},
          "objects":[{
              "id":"e885e64a8ba64595b884b40f8a63674f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":200,
                  "height":100},
                "limbo":true},
              "adaptiveStyles":{
                "a":{
}}}],
          "images":{
            "normal~":"images/main_page/u0.png",
            "normal~a":"images/main_page/u0_a.png"}},
{
          "id":"c260370229334aafa9d7cc0d80bc8e65",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":380},
            "size":{
              "width":200,
              "height":100},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
              "location":{
                "x":0,
                "y":420},
              "size":{
                "width":320,
                "height":60},
              "limbo":false}},
          "objects":[{
              "id":"7c011b4ae4f44f9188ef83d525414d5b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":380},
                "size":{
                  "width":200,
                  "height":100},
                "limbo":true},
              "adaptiveStyles":{
                "a":{
}}}],
          "images":{
            "normal~":"images/main_page/u0.png",
            "normal~a":"images/main_page/u2_a.png"}},
{
          "id":"7a34780efcca42ce98b23c57c9f5bec0",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":12.5},
            "size":{
              "width":100,
              "height":25},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
              "location":{
                "x":10,
                "y":14},
              "size":{
                "width":70,
                "height":23},
              "limbo":false}}},
{
          "id":"b8291c478a154fe6abe01b92faa785ad",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":118,
              "y":18},
            "size":{
              "width":32,
              "height":16},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
              "fontSize":"20px",
              "horizontalAlignment":"center",
              "location":{
                "x":119,
                "y":14},
              "size":{
                "width":82,
                "height":22},
              "limbo":false}},
          "objects":[{
              "id":"f9cc0e5bf2c745a786e97b3cc1e65632",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":118,
                  "y":18},
                "size":{
                  "width":32,
                  "height":16},
                "limbo":true},
              "adaptiveStyles":{
                "a":{
}}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "normal~a":"resources/images/transparent.gif"}},
{
          "id":"3f4cec9a9eba4b3a83f65806bd54acbe",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":211,
              "y":13},
            "size":{
              "width":100,
              "height":25},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
              "location":{
                "x":240,
                "y":13},
              "size":{
                "width":71,
                "height":25},
              "limbo":false}}},
{
          "id":"5c3497d816d149c2bf896f115c903cd6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":430},
            "size":{
              "width":100,
              "height":30},
            "limbo":true,
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
            "a":{
              "location":{
                "x":0,
                "y":420},
              "size":{
                "width":64,
                "height":60},
              "limbo":false}},
          "objects":[{
              "id":"c5e91a79c8424fc68bb77cdb59e7d139",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":430},
                "size":{
                  "width":100,
                  "height":30},
                "limbo":true,
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
                "a":{
}}}],
          "images":{
            "normal~":"images/main_page/u8.png",
            "normal~a":"images/main_page/u8_a.png"}},
{
          "id":"e44ff22a03274b469f8dc521e90729e7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":430},
            "size":{
              "width":100,
              "height":30},
            "limbo":true,
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
            "a":{
              "location":{
                "x":128,
                "y":420},
              "size":{
                "width":64,
                "height":60},
              "limbo":false}},
          "objects":[{
              "id":"84c962beb5fd4d1cb2cf8af9028e9dd8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":430},
                "size":{
                  "width":100,
                  "height":30},
                "limbo":true,
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
                "a":{
}}}],
          "images":{
            "normal~":"images/main_page/u8.png",
            "normal~a":"images/main_page/u8_a.png"}},
{
          "id":"4f0d8dc330ba444893bdb3d1081189fd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":440},
            "size":{
              "width":100,
              "height":30},
            "limbo":true,
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
            "a":{
              "location":{
                "x":192,
                "y":420},
              "size":{
                "width":64,
                "height":60},
              "limbo":false}},
          "objects":[{
              "id":"058a2568340a4aac8662c04051e4a3fa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":440},
                "size":{
                  "width":100,
                  "height":30},
                "limbo":true,
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
                "a":{
}}}],
          "images":{
            "normal~":"images/main_page/u8.png",
            "normal~a":"images/main_page/u8_a.png"}},
{
          "id":"f1d4cc3d49f649478f421ccea7bdae4d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":450},
            "size":{
              "width":100,
              "height":30},
            "limbo":true,
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
            "a":{
              "location":{
                "x":256,
                "y":420},
              "size":{
                "width":64,
                "height":60},
              "limbo":false}},
          "objects":[{
              "id":"3fa43e3fcbd64b4c9609db5ccf658977",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":450},
                "size":{
                  "width":100,
                  "height":30},
                "limbo":true,
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
                "a":{
}}}],
          "images":{
            "normal~":"images/main_page/u8.png",
            "normal~a":"images/main_page/u8_a.png"}},
{
          "id":"ca407e24020446989f903c218e27a540",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":150,
              "y":430},
            "size":{
              "width":100,
              "height":30},
            "limbo":true,
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
            "a":{
              "location":{
                "x":64,
                "y":420},
              "size":{
                "width":64,
                "height":60},
              "limbo":false}},
          "objects":[{
              "id":"6c1844e3adde4298b3889b5d126096e8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":150,
                  "y":430},
                "size":{
                  "width":100,
                  "height":30},
                "limbo":true,
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
                "a":{
}}}],
          "images":{
            "normal~":"images/main_page/u8.png",
            "normal~a":"images/main_page/u8_a.png"}},
{
          "id":"fac7e104ab7b4785bc532a0aa88abe0a",
          "label":"轮播图",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":50},
            "size":{
              "width":200,
              "height":200},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
              "size":{
                "width":320,
                "height":90},
              "limbo":false}},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"c36c89775bba4e3b8c5c813173be39bc",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[]}]},
{
          "id":"30fff619d0934613857dd4698fc66e23",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":101,
              "y":117},
            "size":{
              "width":100,
              "height":16},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
              "location":{
                "x":117,
                "y":114},
              "size":{
                "width":9,
                "height":16},
              "limbo":false}},
          "objects":[{
              "id":"330ca45a8d16474ba356c531127f6420",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":101,
                  "y":117},
                "size":{
                  "width":100,
                  "height":16},
                "limbo":true},
              "adaptiveStyles":{
                "a":{
}}}]},
{
          "id":"06d1e06245e54aa1931ff2ef4b643fa0",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":111,
              "y":127},
            "size":{
              "width":100,
              "height":16},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
              "location":{
                "x":136,
                "y":114},
              "size":{
                "width":9,
                "height":16},
              "limbo":false}},
          "objects":[{
              "id":"57321fd69b7f44999f2251316fcaa372",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":111,
                  "y":127},
                "size":{
                  "width":100,
                  "height":16},
                "limbo":true},
              "adaptiveStyles":{
                "a":{
}}}]},
{
          "id":"39f79badf3cc4ad0b1149cb7cd86b639",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":121,
              "y":137},
            "size":{
              "width":100,
              "height":16},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
              "location":{
                "x":156,
                "y":114},
              "size":{
                "width":9,
                "height":16},
              "limbo":false}},
          "objects":[{
              "id":"a0f9decb4df44d1ea7d8624a92fe834f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":121,
                  "y":137},
                "size":{
                  "width":100,
                  "height":16},
                "limbo":true},
              "adaptiveStyles":{
                "a":{
}}}]},
{
          "id":"f13a9c3fa2284afab371dab8c8c314cf",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":131,
              "y":147},
            "size":{
              "width":100,
              "height":16},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
              "location":{
                "x":174,
                "y":114},
              "size":{
                "width":9,
                "height":16},
              "limbo":false}},
          "objects":[{
              "id":"674a38aaeb4148a0ae50695d71f9482e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":131,
                  "y":147},
                "size":{
                  "width":100,
                  "height":16},
                "limbo":true},
              "adaptiveStyles":{
                "a":{
}}}]},
{
          "id":"66b29badf5ce43dd893790d6ba12878b",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":141,
              "y":157},
            "size":{
              "width":100,
              "height":16},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
              "location":{
                "x":193,
                "y":114},
              "size":{
                "width":9,
                "height":16},
              "limbo":false}},
          "objects":[{
              "id":"e997010aab6d40889f4507a18a5e5259",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":141,
                  "y":157},
                "size":{
                  "width":100,
                  "height":16},
                "limbo":true},
              "adaptiveStyles":{
                "a":{
}}}]},
{
          "id":"985b7ca85ca842e3ade98faac90e1164",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":144,
              "y":64},
            "size":{
              "width":40,
              "height":16},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
              "size":{
                "width":40,
                "height":16},
              "limbo":false}},
          "objects":[{
              "id":"89bef0360d3043c68f96b17b49cd37fd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":144,
                  "y":64},
                "size":{
                  "width":40,
                  "height":16},
                "limbo":true},
              "adaptiveStyles":{
                "a":{
}}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "normal~a":"resources/images/transparent.gif"}},
{
          "id":"d00dbdd60b5c49f6823e716b8cc0b259",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":150},
            "size":{
              "width":100,
              "height":25},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
              "size":{
                "width":140,
                "height":260},
              "limbo":false}}},
{
          "id":"e8ffa0246b574f17be38625682ba784a",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":160,
              "y":150},
            "size":{
              "width":100,
              "height":25},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
              "size":{
                "width":151,
                "height":130},
              "limbo":false}}},
{
          "id":"a5f37de9eba84c2ab13fe13440bce57e",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":160,
              "y":280},
            "size":{
              "width":100,
              "height":25},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
              "location":{
                "x":160,
                "y":290},
              "size":{
                "width":151,
                "height":120},
              "limbo":false}}}]}},
  "masters":{
},
  "objectPaths":{
    "a4c9832434df42d79d1a32f90fffd4ee":{
      "scriptId":"u0"},
    "e885e64a8ba64595b884b40f8a63674f":{
      "scriptId":"u1"},
    "c260370229334aafa9d7cc0d80bc8e65":{
      "scriptId":"u2"},
    "7c011b4ae4f44f9188ef83d525414d5b":{
      "scriptId":"u3"},
    "7a34780efcca42ce98b23c57c9f5bec0":{
      "scriptId":"u4"},
    "b8291c478a154fe6abe01b92faa785ad":{
      "scriptId":"u5"},
    "f9cc0e5bf2c745a786e97b3cc1e65632":{
      "scriptId":"u6"},
    "3f4cec9a9eba4b3a83f65806bd54acbe":{
      "scriptId":"u7"},
    "5c3497d816d149c2bf896f115c903cd6":{
      "scriptId":"u8"},
    "c5e91a79c8424fc68bb77cdb59e7d139":{
      "scriptId":"u9"},
    "e44ff22a03274b469f8dc521e90729e7":{
      "scriptId":"u10"},
    "84c962beb5fd4d1cb2cf8af9028e9dd8":{
      "scriptId":"u11"},
    "4f0d8dc330ba444893bdb3d1081189fd":{
      "scriptId":"u12"},
    "058a2568340a4aac8662c04051e4a3fa":{
      "scriptId":"u13"},
    "f1d4cc3d49f649478f421ccea7bdae4d":{
      "scriptId":"u14"},
    "3fa43e3fcbd64b4c9609db5ccf658977":{
      "scriptId":"u15"},
    "ca407e24020446989f903c218e27a540":{
      "scriptId":"u16"},
    "6c1844e3adde4298b3889b5d126096e8":{
      "scriptId":"u17"},
    "fac7e104ab7b4785bc532a0aa88abe0a":{
      "scriptId":"u18"},
    "30fff619d0934613857dd4698fc66e23":{
      "scriptId":"u19"},
    "330ca45a8d16474ba356c531127f6420":{
      "scriptId":"u20"},
    "06d1e06245e54aa1931ff2ef4b643fa0":{
      "scriptId":"u21"},
    "57321fd69b7f44999f2251316fcaa372":{
      "scriptId":"u22"},
    "39f79badf3cc4ad0b1149cb7cd86b639":{
      "scriptId":"u23"},
    "a0f9decb4df44d1ea7d8624a92fe834f":{
      "scriptId":"u24"},
    "f13a9c3fa2284afab371dab8c8c314cf":{
      "scriptId":"u25"},
    "674a38aaeb4148a0ae50695d71f9482e":{
      "scriptId":"u26"},
    "66b29badf5ce43dd893790d6ba12878b":{
      "scriptId":"u27"},
    "e997010aab6d40889f4507a18a5e5259":{
      "scriptId":"u28"},
    "985b7ca85ca842e3ade98faac90e1164":{
      "scriptId":"u29"},
    "89bef0360d3043c68f96b17b49cd37fd":{
      "scriptId":"u30"},
    "d00dbdd60b5c49f6823e716b8cc0b259":{
      "scriptId":"u31"},
    "e8ffa0246b574f17be38625682ba784a":{
      "scriptId":"u32"},
    "a5f37de9eba84c2ab13fe13440bce57e":{
      "scriptId":"u33"}}});